// Formulas of the kind Claude writes, for the Unicode renderer's snapshot.
export const CORPUS: readonly string[] = [
  // calculus
  String.raw`f'(x) = \lim_{h \to 0} \frac{f(x+h) - f(x)}{h}`,
  String.raw`\int_a^b f(x)\,dx = F(b) - F(a)`,
  String.raw`\frac{d}{dx}\left[ x^n \right] = n x^{n-1}`,
  String.raw`\mathcal{L}\{f\}(s) = \int_0^{\infty} e^{-st} f(t)\,dt`,
  String.raw`f(x) = \sum_{n=0}^{\infty} \frac{f^{(n)}(a)}{n!}(x-a)^n`,
  String.raw`\frac{\partial^2 u}{\partial t^2} = c^2 \nabla^2 u`,
  String.raw`\oint_C \mathbf{F} \cdot d\mathbf{r} = \iint_S (\nabla \times \mathbf{F}) \cdot d\mathbf{S}`,
  String.raw`\lim_{n\to\infty} \left(1 + \frac{1}{n}\right)^n = e`,
  String.raw`\int_{-\infty}^{\infty} e^{-x^2}\,dx = \sqrt{\pi}`,
  String.raw`\frac{d}{dx} \int_a^x f(t)\,dt = f(x)`,
  String.raw`\sum_{n=1}^{\infty} \frac{1}{n^2} = \frac{\pi^2}{6}`,
  String.raw`e^{i\theta} = \cos\theta + i\sin\theta`,
  String.raw`\nabla f = \left( \frac{\partial f}{\partial x}, \frac{\partial f}{\partial y}, \frac{\partial f}{\partial z} \right)`,
  String.raw`\int_0^1 \frac{dx}{1 + x^2} = \frac{\pi}{4}`,
  // linear algebra
  String.raw`A\mathbf{x} = \mathbf{b}`,
  String.raw`\det(A - \lambda I) = 0`,
  String.raw`A = \begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix}`,
  String.raw`I_3 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}`,
  String.raw`\begin{vmatrix} a & b \\ c & d \end{vmatrix} = ad - bc`,
  String.raw`A^{-1} = \frac{1}{\det A} \operatorname{adj}(A)`,
  String.raw`\|\mathbf{v}\|_2 = \sqrt{\sum_{i=1}^n v_i^2}`,
  String.raw`\langle \mathbf{u}, \mathbf{v} \rangle = \mathbf{u}^\top \mathbf{v}`,
  String.raw`A = U \Sigma V^T`,
  String.raw`\mathbf{x} = \begin{pmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{pmatrix}`,
  String.raw`\operatorname{tr}(AB) = \operatorname{tr}(BA)`,
  String.raw`\begin{pmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{pmatrix} \begin{pmatrix} x \\ y \end{pmatrix}`,
  // probability and statistics
  String.raw`P(A \mid B) = \frac{P(B \mid A)\,P(A)}{P(B)}`,
  String.raw`\mathbb{E}[X] = \sum_{x} x\,p(x)`,
  String.raw`\operatorname{Var}(X) = \mathbb{E}[X^2] - (\mathbb{E}[X])^2`,
  String.raw`f(x) = \frac{1}{\sigma\sqrt{2\pi}} e^{-\frac{(x-\mu)^2}{2\sigma^2}}`,
  String.raw`X \sim \mathcal{N}(\mu, \sigma^2)`,
  String.raw`P(X = k) = \binom{n}{k} p^k (1-p)^{n-k}`,
  String.raw`\bar{x} = \frac{1}{n}\sum_{i=1}^n x_i`,
  String.raw`H(X) = -\sum_{i} p_i \log_2 p_i`,
  String.raw`\hat{\theta} = \arg\max_\theta \mathcal{L}(\theta)`,
  String.raw`D_{\mathrm{KL}}(P \parallel Q) = \sum_x P(x) \log \frac{P(x)}{Q(x)}`,
  // physics
  String.raw`E = mc^2`,
  String.raw`\mathbf{F} = m\mathbf{a}`,
  String.raw`i\hbar \frac{\partial}{\partial t} \Psi(\mathbf{r}, t) = \hat{H} \Psi(\mathbf{r}, t)`,
  String.raw`\begin{aligned} \nabla\cdot\mathbf{E} &= \frac{\rho}{\varepsilon_0} \\ \nabla\times\mathbf{B} &= \mu_0\mathbf{J} + \mu_0\varepsilon_0\frac{\partial\mathbf{E}}{\partial t} \end{aligned}`,
  String.raw`\Delta x \, \Delta p \ge \frac{\hbar}{2}`,
  String.raw`F = G \frac{m_1 m_2}{r^2}`,
  String.raw`\vec{v} = \frac{d\vec{r}}{dt}`,
  String.raw`E_k = \tfrac{1}{2} m v^2`,
  String.raw`\gamma = \frac{1}{\sqrt{1 - v^2/c^2}}`,
  String.raw`T_{\text{eff}} = \left( \frac{L}{4\pi\sigma R^2} \right)^{1/4}`,
  // sets and logic
  String.raw`A \cup B = \{ x : x \in A \lor x \in B \}`,
  String.raw`\forall \varepsilon > 0\; \exists \delta > 0 : |x - a| < \delta \implies |f(x) - f(a)| < \varepsilon`,
  String.raw`\mathbb{N} \subset \mathbb{Z} \subset \mathbb{Q} \subset \mathbb{R} \subset \mathbb{C}`,
  String.raw`\left\{ x \in \mathbb{R} \;\middle|\; x^2 < 2 \right\}`,
  String.raw`|A \times B| = |A| \cdot |B|`,
  String.raw`\neg (p \land q) \iff \neg p \lor \neg q`,
  // piecewise
  String.raw`f(x) = \begin{cases} x^2 & \text{if } x \ge 0 \\ -x & \text{if } x < 0 \end{cases}`,
  String.raw`|x| = \begin{cases} x, & x \geq 0, \\ -x, & x < 0. \end{cases}`,
  String.raw`\operatorname{sgn}(x) = \begin{cases} -1 & x < 0 \\ 0 & x = 0 \\ 1 & x > 0 \end{cases}`,
  String.raw`H(x) = \begin{cases} \frac{1}{2} & x = 0 \\ 1 & x > 0 \end{cases}`,
  // aligned derivations
  String.raw`\begin{aligned} (a+b)^2 &= (a+b)(a+b) \\ &= a^2 + 2ab + b^2 \end{aligned}`,
  String.raw`\begin{aligned} \int x e^x\,dx &= x e^x - \int e^x\,dx \\ &= (x - 1) e^x + C \end{aligned}`,
  String.raw`\begin{aligned} f(x) &= \frac{x^2 - 1}{x - 1} \\ &= x + 1 \end{aligned}`,
  String.raw`\begin{aligned} x + y &= 5 & 2x - y &= 1 \end{aligned}`,
  // algorithms and misc
  String.raw`O(n \log n)`,
  String.raw`T(n) = 2T\left(\frac{n}{2}\right) + O(n)`,
  String.raw`a \equiv b \pmod{n}`,
  String.raw`\gcd(a, b) = \gcd(b, a \bmod b)`,
  String.raw`\sqrt[n]{x^m} = x^{m/n}`,
  String.raw`\frac{1}{1 + \frac{1}{x}}`,
  String.raw`\overline{z} = a - bi`,
  String.raw`\underbrace{1 + 1 + \cdots + 1}_{n} = n`,
  String.raw`x \xrightarrow{f} y`,
  String.raw`\boxed{E = mc^2}`,
  String.raw`\lfloor x \rfloor + \lceil x \rceil`,
  String.raw`\sum_{\substack{0 \le i \le m \\ 0 < j < n}} P(i, j)`,
  String.raw`\mathcal{O}, \mathfrak{g}, \mathsf{T}, \mathtt{x}, \mathbf{0}`,
  String.raw`\frac{a}{b} \cdot \frac{c}{d} = \frac{ac}{bd}`,
  String.raw`\frac{\cancel{x} y}{\cancel{x}} = y`,
  String.raw`\left[\begin{array}{cc|c} 1 & 2 & 3 \\ 4 & 5 & 6 \end{array}\right]`,
  String.raw`x_{n+1} = x_n - \frac{f(x_n)}{f'(x_n)}`,
  String.raw`\sigma(z) = \frac{1}{1 + e^{-z}}`,
  String.raw`\text{softmax}(z)_i = \frac{e^{z_i}}{\sum_j e^{z_j}}`,
  String.raw`\theta \leftarrow \theta - \eta \nabla_\theta J(\theta)`,
  String.raw`\alpha, \beta, \gamma \in \{1, 2, \ldots, n\}`,
  String.raw`\overbrace{a + b}^{\text{sum}} \cdot \hat{n}`,
]
