import type { CellAdjust, CellSize, KittyAdjust, KittyMetric, MetricAdjust, Probe } from '../types.js'
import type { FontMetrics } from './fontfile.js'

// The cell probes. A child of Claude Code has no controlling terminal (opening
// /dev/tty fails with ENXIO), so each probe walks up from its parent to the
// first ancestor that has a terminal on stdin, stdout or stderr, opens that
// terminal with O_NOCTTY (so it doesn't become ours) and asks its size with the
// TIOCGWINSZ ioctl. struct winsize is four unsigned shorts (rows, columns,
// xpixels, ypixels) on Linux and macOS alike; terminals that report pixels
// (kitty, Ghostty, WezTerm, iTerm2) fill in the last two, others leave them 0.
//
// Ancestors and their terminals: /proc/<pid>/fd/{0,1,2} and /proc/<pid>/stat on
// Linux; `ps -o ppid=,tty= -p <pid>` elsewhere (macOS prints ttys003, or ?? for
// none). Both print "rows columns xpixels ypixels" and exit 0, or exit 1 when no
// ancestor has a terminal. They never write to the terminal.

// TIOCGWINSZ is _IOR('t', 104, struct winsize): 0x40087468 on macOS and the
// BSDs, 0x5413 on Linux. Spelled out because sys/ioctl.ph is often missing (it
// is generated by h2ph, which many perl installs never ran).
const CELL_PROBE_PERL = String.raw`
use strict;
use Fcntl qw(O_RDONLY O_NOCTTY);
my $req = ($^O eq 'darwin' || $^O =~ /bsd/i) ? 0x40087468 : 0x5413;
my $proc = -d '/proc/self/fd';
sub tty_path {
  my ($t) = @_;
  return unless defined $t && $t =~ m{^(?:/dev/)?(pts/\d+|tty\w+|s\d+)$};
  my $n = $1;
  return '/dev/' . ($n =~ /^s\d/ ? "tty$n" : $n);
}
sub try_size {
  my $t = tty_path($_[0]) or return;
  sysopen(my $h, $t, O_RDONLY | O_NOCTTY) or return;
  my $ws = "\0" x 8;
  ioctl($h, $req, $ws) or return;
  my ($r, $c, $x, $y) = unpack('S4', $ws);
  print "$r $c $x $y\n";
  exit 0;
}
my $p = getppid();
for (1 .. 64) {
  last if !$p || $p <= 1;
  my $next;
  if ($proc) {
    try_size(readlink("/proc/$p/fd/$_")) for 0 .. 2;
    open(my $s, '<', "/proc/$p/stat") or last;
    my ($rest) = (scalar(<$s>) =~ /\)\s+(.*)/s);
    last unless defined $rest;
    $next = (split ' ', $rest)[1];
  } else {
    open(my $ps, '-|', 'ps', '-o', 'ppid=,tty=', '-p', $p) or last;
    my $line = <$ps>;
    close $ps;
    last unless defined $line && $line =~ /^\s*(\d+)\s+(\S+)/;
    $next = $1;
    try_size($2);
  }
  $p = $next;
}
exit 1;
`

// The same walk in Python, for systems without perl. termios.TIOCGWINSZ has the
// right value on every platform.
const CELL_PROBE_PYTHON = String.raw`
import fcntl, os, re, struct, subprocess, sys, termios
def tty_path(t):
    m = re.fullmatch(r'(?:/dev/)?(pts/\d+|tty\w+|s\d+)', t or '')
    if not m:
        return None
    n = m.group(1)
    return '/dev/' + ('tty' + n if re.match(r's\d', n) else n)
def try_size(t):
    t = tty_path(t)
    if not t:
        return
    try:
        fd = os.open(t, os.O_RDONLY | os.O_NOCTTY)
    except OSError:
        return
    try:
        r, c, x, y = struct.unpack('4H', fcntl.ioctl(fd, termios.TIOCGWINSZ, b'\0' * 8))
    except OSError:
        return
    finally:
        os.close(fd)
    print(r, c, x, y)
    sys.exit(0)
proc = os.path.isdir('/proc/self/fd')
p = os.getppid()
for _ in range(64):
    if p <= 1:
        break
    if proc:
        for fd in (0, 1, 2):
            try:
                try_size(os.readlink('/proc/%d/fd/%d' % (p, fd)))
            except OSError:
                pass
        try:
            with open('/proc/%d/stat' % p) as f:
                p = int(f.read().rsplit(')', 1)[1].split()[1])
        except (OSError, ValueError, IndexError):
            break
    else:
        try:
            out = subprocess.run(['ps', '-o', 'ppid=,tty=', '-p', str(p)], capture_output=True, text=True).stdout.split()
            p = int(out[0])
        except (OSError, ValueError, IndexError):
            break
        if len(out) > 1:
            try_size(out[1])
sys.exit(1)
`

/**
 * Reads "rows columns xpixels ypixels" (TIOCGWINSZ). Undefined unless all four
 * are positive integers: terminals that don't report pixels (tmux, screen,
 * Terminal.app, most Linux terminals) leave the pixel fields 0.
 */
export function parseWinsize(stdout: string): CellSize | undefined {
  const match = /^\s*(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s*$/m.exec(stdout)
  if (!match) return undefined
  const [rows, columns, xpixels, ypixels] = match.slice(1).map(Number) as [number, number, number, number]
  if (!(rows > 0 && columns > 0 && xpixels > 0 && ypixels > 0)) return undefined
  // Terminals draw whole-pixel cells, but some report the whole drawing area,
  // padding included (Ghostty: 681 px over 68 columns of 10 px). Dividing gives
  // a fraction of a pixel too much per cell, and an image drawn for 10.01 px
  // cells is rescaled by the terminal into its 10 px cells, blurring all of it.
  const cellWidth = Math.floor(xpixels / columns)
  const cellHeight = Math.floor(ypixels / rows)
  if (cellWidth < 1 || cellHeight < 1) return undefined
  return { cellWidth, cellHeight, columns, rows }
}

/** Measures the terminal's cells in pixels with perl (Linux and macOS). */
export const cellProbe: Probe<CellSize> = {
  argv: ['perl', '-e', CELL_PROBE_PERL],
  parse: parseWinsize,
}

/** The same measurement with python3 (-I: no user site, no cwd on sys.path). */
export const cellProbePython: Probe<CellSize> = {
  argv: ['python3', '-I', '-c', CELL_PROBE_PYTHON],
  parse: parseWinsize,
}

/** Cell probes to try in order until one runs (cellProbeRan): perl, then python3. */
export const cellProbes: readonly Probe<CellSize>[] = [cellProbe, cellProbePython]

/**
 * Whether a cell probe ran and answered, so the next one would say the same:
 * the size (exit 0, pixels or none: a terminal that doesn't report them), or
 * no terminal among its ancestors (exit 1). Only a probe that couldn't run
 * (its interpreter missing or broken) calls for the next: macOS always has
 * perl, and its python3 is a stub that, without the developer tools, opens a
 * dialog offering to install them.
 */
export function cellProbeRan(exitCode: number, stdout: string): boolean {
  return exitCode === 1 || (exitCode === 0 && /^\s*\d+\s+\d+\s+\d+\s+\d+\s*$/m.test(stdout))
}

/**
 * Pixels per em for math set next to text in cells of this size.
 *
 * Monospace fonts advance about 0.6 em per cell (DejaVu Sans Mono, Menlo,
 * JetBrains Mono, Roboto Mono 1229/2048, SF Mono), so the text font's em is
 * cellWidth / 0.6. Computer Modern has a smaller x-height than those fonts
 * (0.43 em against 0.50-0.55 em), so emScale 1.15 lifts the math to match the
 * text. The cell height is no help: it includes the font's line gap and the
 * terminal's own adjustments (kitty's modify_font). No terminal reports its font
 * metrics to a child process; the font size alone wouldn't do either, since
 * converting points to pixels needs the monitor's DPI and scale.
 */
export function emPxForCell(cell: Pick<CellSize, 'cellWidth' | 'cellHeight'>, emScale = 1.15): number {
  return (cell.cellWidth / 0.6) * emScale
}

type CellPixels = Pick<CellSize, 'cellWidth' | 'cellHeight'>

/**
 * The cell the terminal's font alone gives, before the terminal set it off
 * (Ghostty's adjust-cell-width and adjust-cell-height). Ghostty rounds the
 * font's advance and line height to whole pixels and then applies each
 * adjustment (round(n × factor), or n + px); this undoes that to the nearest
 * pixel. The font's em is what emPxForCell needs: with adjust-cell-width =
 * 20%, measuring the em from the adjusted cell drew the math 20% larger than
 * the text.
 */
export function fontCell(cell: CellPixels, adjust?: CellAdjust): CellPixels {
  return { cellWidth: unadjust(cell.cellWidth, adjust?.width), cellHeight: unadjust(cell.cellHeight, adjust?.height) }
}

function unadjust(n: number, adjust: MetricAdjust | undefined): number {
  if (!adjust) return n
  const font = 'factor' in adjust ? (adjust.factor > 0 ? n / adjust.factor : n) : n - adjust.px
  return Number.isFinite(font) ? Math.max(1, Math.round(font)) : n
}

/**
 * The text's baseline in a cell `cellHeight` pixels tall, in pixels from its
 * top: `fraction` of the font's own cell height (fontCell), moved the way
 * Ghostty (font/Metrics.zig) moves it when it adjusts the cell. Rows added to
 * or taken from the cell's height are split between its top and bottom, so
 * the text stays centred (an odd row goes where the face needs it; here, on
 * top: a pixel either way), then adjust-font-baseline changes the baseline's
 * distance from the cell's bottom. Without adjustments, round(cellHeight ×
 * fraction).
 */
export function textBaseline(cellHeight: number, fraction: number, adjust?: CellAdjust): number {
  const font = unadjust(cellHeight, adjust?.height)
  return adjustedBaseline(cellHeight, Math.round(font * fraction), font, adjust)
}

/** A baseline `top` px down the font's own cell (`font` px tall), moved as Ghostty's adjustments move it in the cell. */
function adjustedBaseline(cellHeight: number, fontTop: number, font: number, adjust?: CellAdjust): number {
  let top = fontTop + Math.ceil((cellHeight - font) / 2)
  const shift = adjust?.baseline
  if (shift) {
    const fromBottom = cellHeight - top
    top = cellHeight - ('factor' in shift ? Math.round(fromBottom * shift.factor) : fromBottom + shift.px)
  }
  return Math.min(cellHeight, Math.max(0, top))
}

// ─── the text font's own layout ──────────────────────────────────────────────

/** Computer Modern's x-height, in em: the math font's lowercase letters stand this tall. */
export const MATH_X_HEIGHT = 0.4306

/**
 * The math's x-height against the text font's (both in design units: the
 * font's sxHeight, CM's 0.431 em). What emPxForCell's 1.15 gives next to
 * Roboto Mono, against which kittex's sizes were tuned by eye (in ink, the
 * stroke weight included, the math's x stands about as tall as the text's);
 * DejaVu Sans Mono and JetBrains Mono read 0.90 there, Source Code Pro 1.02,
 * Iosevka (half an em wide) 0.76.
 */
export const X_HEIGHT_RATIO = 0.92

/** Where the terminal sets its text font in a cell, from the font's own metrics. */
export interface TextLayout {
  /** The text's em, in pixels. */
  emPx: number
  /** The text's baseline, in pixels from the top of the cell. */
  baselinePx: number
  /** The text's x-height, in pixels (before hinting), when the font gives one. */
  xHeightPx?: number
}

export interface TextLayoutOptions {
  /** The configured size, in points: with the cell, it tells the screen's DPI (and so the exact em). */
  sizePt?: number
  /** Ghostty's adjust-cell-height and adjust-font-baseline. */
  adjust?: CellAdjust
  /** kitty's modify_font. */
  kittyAdjust?: KittyAdjust
  /** `darwin` (points at 72 DPI times the display's scale), else 96 DPI times the scale; both when not given. */
  platform?: string
}

/** Screen DPIs a terminal converts points with: 96 (Linux, Windows) or 72 (macOS) times the display's scale. */
function dpis(platform: string | undefined): number[] {
  const bases = platform === undefined ? [96, 72] : platform === 'darwin' ? [72] : [96]
  return bases.flatMap(base => [1, 1.25, 1.5, 1.75, 2, 2.25, 2.5, 3, 4].map(scale => base * scale))
}

/**
 * How kitty or Ghostty lay out this font in a cell of this size: the em, the
 * baseline and the x-height in pixels, computed as each terminal computes its
 * cell from the font's metrics (both through FreeType on Linux: the font's
 * line height rounded to whole pixels, the baseline from its ascender), with
 * the config's adjustments. The em comes from the configured size at the DPI
 * that gives this cell; when none does (a font zoomed at run time, an
 * unexpected DPI), from the cell's height alone. Undefined for other
 * terminals and for metrics that make no cell.
 */
export function textLayout(kind: string, font: FontMetrics, cell: CellPixels, options: TextLayoutOptions = {}): TextLayout | undefined {
  const upm = font.unitsPerEm
  const height = (font.ascender - font.descender + font.lineGap) / upm
  if (!(upm > 0 && height > 0.5 && height < 4 && cell.cellHeight >= 2)) return undefined
  const layout = kind === 'kitty' ? kittyLayout(font, height, cell, options) : kind === 'ghostty' ? ghosttyLayout(font, height, cell, options) : undefined
  if (!layout || !Number.isFinite(layout.emPx) || layout.emPx <= 0) return undefined
  if (font.xHeight) layout.xHeightPx = (font.xHeight / upm) * layout.emPx
  layout.baselinePx = Math.min(cell.cellHeight, Math.max(1, layout.baselinePx))
  return layout
}

/**
 * Pixels per em for math set next to this text: the math's x-height
 * X_HEIGHT_RATIO of the text's, held within 0.75 to 1.35 times what the cell
 * alone suggests (emPxForCell) against odd metrics.
 */
export function mathEmPx(layout: TextLayout, cell: CellPixels): number {
  const byCell = emPxForCell(cell)
  const byFont = layout.xHeightPx ? (X_HEIGHT_RATIO * layout.xHeightPx) / MATH_X_HEIGHT : layout.emPx * 1.15
  return Math.min(byCell * 1.35, Math.max(byCell * 0.75, byFont))
}

// kitty (fonts.c, freetype.c, 0.49): the cell is ceil(line height), grown to
// fit the underscore when a font draws it lower (DejaVu Sans Mono: a pixel),
// and as wide as the widest ASCII advance; the baseline is ceil(ascender) from
// the top. modify_font then sets the cell's height (a percentage of it, or
// pixels or points added), moves the baseline up by its `baseline` (kept inside
// the cell), and, when the cell grew by more than a pixel, moves the baseline
// down by half the rows added.
//
// On macOS kitty measures the font with CoreText (core_text.m): the cell is
// the ascent, descent and leading each rounded to whole pixels, then added (a
// line CoreText lays out), and the baseline is the ascent rounded, so Menlo
// 11 pt is 7×13 px with its baseline 10 px down where FreeType's ceil gives 11.
function kittyLayout(font: FontMetrics, height: number, cell: CellPixels, options: TextLayoutOptions): TextLayout | undefined {
  const upm = font.unitsPerEm
  const adjust = options.kittyAdjust
  // FreeType's FT_MulFix to 26.6 fixed point, then kitty's ceil to whole pixels.
  const ceilPx = (units: number, em: number) => Math.ceil(Math.round((units / upm) * em * 64) / 64)
  const lineUnits = font.ascender - font.descender + font.lineGap
  const coreText = options.platform === 'darwin'
  const roundPx = (units: number, em: number) => Math.round((units / upm) * em)
  /** The font's own cell height at `em` (before modify_font): FreeType's ceil of the line, or CoreText's rounded parts. */
  const lineAt = (em: number) => (coreText ? roundPx(font.ascender, em) + roundPx(-font.descender, em) + roundPx(Math.max(0, font.lineGap), em) : ceilPx(lineUnits, em))
  const wide = (em: number) => !font.advance || adjust?.cellWidth !== undefined || Math.abs(ceilPx(font.advance, em) - cell.cellWidth) <= 1
  let em: number | undefined
  let own: number | undefined
  let dpi = 96
  if (options.sizePt && options.sizePt > 0) {
    // The DPI that gives this cell: the line height exactly, else one or two rows more (an underscore drawn lower).
    // (CoreText's cell is its line alone: no underscore below it.)
    search: for (const extra of coreText ? [0] : [0, 1, 2]) {
      for (const d of dpis(options.platform)) {
        const e = (options.sizePt * d) / 72
        const h = lineAt(e) + extra
        if (wide(e) && kittyMetric(h, adjust?.cellHeight, d) === cell.cellHeight) {
          ;[em, own, dpi] = [e, h, d]
          break search
        }
      }
    }
  }
  if (em === undefined || own === undefined) {
    // From the cell alone: the font's own cell height (before modify_font), then the ems that give it and the cell's width.
    own = adjust?.cellHeight ? unkittyMetric(cell.cellHeight, adjust.cellHeight, dpi) : cell.cellHeight
    let low = (own - 1) / height
    let high = own / height
    if (font.advance && !adjust?.cellWidth) {
      const advance = font.advance / upm
      const [l, h] = [(cell.cellWidth - 1.5) / advance, (cell.cellWidth + 0.5) / advance]
      if (Math.max(low, l) < Math.min(high, h)) [low, high] = [Math.max(low, l), Math.min(high, h)]
    }
    em = (low + high) / 2
  }
  const cellHeight = cell.cellHeight
  let baseline = coreText ? roundPx(font.ascender, em) : ceilPx(font.ascender, em)
  if (adjust?.baseline) {
    const moved = kittyMetric(baseline, adjust.baseline, dpi) - baseline
    const shift = moved >= 0 ? Math.min(moved, baseline - 1) : Math.max(moved, baseline - cellHeight + 1)
    baseline -= shift
  }
  const added = cellHeight - own
  if (added > 1) baseline += Math.min(cellHeight - 1, Math.floor(added / 2))
  return { emPx: em, baselinePx: baseline }
}

/** kitty's adjust_metric: a percentage of the value, or pixels or points (at `dpi`) added. */
function kittyMetric(value: number, metric: KittyMetric | undefined, dpi: number): number {
  if (!metric || metric.value === 0) return value
  if (metric.unit === '%') return Math.round((Math.abs(metric.value) * value) / 100)
  const add = metric.unit === 'px' ? Math.round(metric.value) : Math.round((metric.value * dpi) / 72)
  return add < 0 && -add > value ? 0 : value + add
}

function unkittyMetric(value: number, metric: KittyMetric, dpi: number): number {
  if (metric.value === 0) return value
  if (metric.unit === '%') return Math.max(1, Math.round((value * 100) / Math.abs(metric.value)))
  const add = metric.unit === 'px' ? Math.round(metric.value) : Math.round((metric.value * dpi) / 72)
  return Math.max(1, value - add)
}

// Ghostty (font/Metrics.zig, font/face/freetype.zig, 1.3): FreeType's whole
// pixels per em (the size rounded; on macOS CoreText's, the size as it is:
// face/coretext.zig), the cell round(line height) tall and
// round(widest ASCII advance) wide, the baseline round(half the line gap -
// descender - half the rounding of the height) up from the bottom; then
// adjust-cell-height and adjust-font-baseline as textBaseline applies them.
function ghosttyLayout(font: FontMetrics, height: number, cell: CellPixels, options: TextLayoutOptions): TextLayout | undefined {
  const upm = font.unitsPerEm
  const own = unadjust(cell.cellHeight, options.adjust?.height)
  const ownWidth = unadjust(cell.cellWidth, options.adjust?.width)
  const fits = (ppem: number) =>
    Math.round(height * ppem) === own && (!font.advance || Math.abs(Math.round((font.advance / upm) * ppem) - ownWidth) <= 1)
  let ppem: number | undefined
  let em: number | undefined
  if (options.sizePt && options.sizePt > 0) {
    for (const d of dpis(options.platform)) {
      const exact = (options.sizePt * d) / 72
      const p = options.platform === 'darwin' ? exact : Math.round((Math.round(options.sizePt * 64) * d) / 72 / 64)
      if (p > 0 && fits(p)) {
        ppem = p
        em = exact
        break
      }
    }
  }
  ppem ??= Math.max(1, Math.round(own / height))
  em ??= ppem
  const faceHeight = height * ppem
  const fromBottom = Math.round(((font.lineGap / 2 - font.descender) / upm) * ppem - (own - faceHeight) / 2)
  return { emPx: em, baselinePx: adjustedBaseline(cell.cellHeight, own - fromBottom, own, options.adjust) }
}
