import type { CellSize, Probe } from '../types.js'

// The cell probes. A child of Claude Code has no controlling terminal (opening
// /dev/tty fails with ENXIO), so each probe walks up from its parent to the
// first ancestor that has a terminal on stdin, stdout or stderr, opens that
// terminal with O_NOCTTY (so it doesn't become ours) and asks its size with the
// TIOCGWINSZ ioctl. struct winsize is four unsigned shorts (rows, columns,
// xpixels, ypixels) on Linux and macOS alike; terminals that report pixels
// (kitty, Ghostty, WezTerm, iTerm2) fill in the last two, others leave them 0.
//
// Ancestors and their terminals: /proc/<pid>/fd/{0,1,2} and /proc/<pid>/stat on
// Linux; `ps -o ppid=,tty= -p <pid>` elsewhere (macOS prints ttys003, or ?? for
// none). Both print "rows columns xpixels ypixels" and exit 0, or exit 1 when no
// ancestor has a terminal. They never write to the terminal.

// TIOCGWINSZ is _IOR('t', 104, struct winsize): 0x40087468 on macOS and the
// BSDs, 0x5413 on Linux. Spelled out because sys/ioctl.ph is often missing (it
// is generated by h2ph, which many perl installs never ran).
const CELL_PROBE_PERL = String.raw`
use strict;
use Fcntl qw(O_RDONLY O_NOCTTY);
my $req = ($^O eq 'darwin' || $^O =~ /bsd/i) ? 0x40087468 : 0x5413;
my $proc = -d '/proc/self/fd';
sub tty_path {
  my ($t) = @_;
  return unless defined $t && $t =~ m{^(?:/dev/)?(pts/\d+|tty\w+|s\d+)$};
  my $n = $1;
  return '/dev/' . ($n =~ /^s\d/ ? "tty$n" : $n);
}
sub try_size {
  my $t = tty_path($_[0]) or return;
  sysopen(my $h, $t, O_RDONLY | O_NOCTTY) or return;
  my $ws = "\0" x 8;
  ioctl($h, $req, $ws) or return;
  my ($r, $c, $x, $y) = unpack('S4', $ws);
  print "$r $c $x $y\n";
  exit 0;
}
my $p = getppid();
for (1 .. 64) {
  last if !$p || $p <= 1;
  my $next;
  if ($proc) {
    try_size(readlink("/proc/$p/fd/$_")) for 0 .. 2;
    open(my $s, '<', "/proc/$p/stat") or last;
    my ($rest) = (scalar(<$s>) =~ /\)\s+(.*)/s);
    last unless defined $rest;
    $next = (split ' ', $rest)[1];
  } else {
    open(my $ps, '-|', 'ps', '-o', 'ppid=,tty=', '-p', $p) or last;
    my $line = <$ps>;
    close $ps;
    last unless defined $line && $line =~ /^\s*(\d+)\s+(\S+)/;
    $next = $1;
    try_size($2);
  }
  $p = $next;
}
exit 1;
`

// The same walk in Python, for systems without perl. termios.TIOCGWINSZ has the
// right value on every platform.
const CELL_PROBE_PYTHON = String.raw`
import fcntl, os, re, struct, subprocess, sys, termios
def tty_path(t):
    m = re.fullmatch(r'(?:/dev/)?(pts/\d+|tty\w+|s\d+)', t or '')
    if not m:
        return None
    n = m.group(1)
    return '/dev/' + ('tty' + n if re.match(r's\d', n) else n)
def try_size(t):
    t = tty_path(t)
    if not t:
        return
    try:
        fd = os.open(t, os.O_RDONLY | os.O_NOCTTY)
    except OSError:
        return
    try:
        r, c, x, y = struct.unpack('4H', fcntl.ioctl(fd, termios.TIOCGWINSZ, b'\0' * 8))
    except OSError:
        return
    finally:
        os.close(fd)
    print(r, c, x, y)
    sys.exit(0)
proc = os.path.isdir('/proc/self/fd')
p = os.getppid()
for _ in range(64):
    if p <= 1:
        break
    if proc:
        for fd in (0, 1, 2):
            try:
                try_size(os.readlink('/proc/%d/fd/%d' % (p, fd)))
            except OSError:
                pass
        try:
            with open('/proc/%d/stat' % p) as f:
                p = int(f.read().rsplit(')', 1)[1].split()[1])
        except (OSError, ValueError, IndexError):
            break
    else:
        try:
            out = subprocess.run(['ps', '-o', 'ppid=,tty=', '-p', str(p)], capture_output=True, text=True).stdout.split()
            p = int(out[0])
        except (OSError, ValueError, IndexError):
            break
        if len(out) > 1:
            try_size(out[1])
sys.exit(1)
`

/**
 * Reads "rows columns xpixels ypixels" (TIOCGWINSZ). Undefined unless all four
 * are positive integers: terminals that don't report pixels (tmux, screen,
 * Terminal.app, most Linux terminals) leave the pixel fields 0.
 */
export function parseWinsize(stdout: string): CellSize | undefined {
  const match = /^\s*(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s*$/m.exec(stdout)
  if (!match) return undefined
  const [rows, columns, xpixels, ypixels] = match.slice(1).map(Number) as [number, number, number, number]
  if (!(rows > 0 && columns > 0 && xpixels > 0 && ypixels > 0)) return undefined
  return { cellWidth: xpixels / columns, cellHeight: ypixels / rows, columns, rows }
}

/** Measures the terminal's cells in pixels with perl (Linux and macOS). */
export const cellProbe: Probe<CellSize> = {
  argv: ['perl', '-e', CELL_PROBE_PERL],
  parse: parseWinsize,
}

/** The same measurement with python3 (-I: no user site, no cwd on sys.path). */
export const cellProbePython: Probe<CellSize> = {
  argv: ['python3', '-I', '-c', CELL_PROBE_PYTHON],
  parse: parseWinsize,
}

/** Cell probes to try in order until one parses: perl, then python3. */
export const cellProbes: readonly Probe<CellSize>[] = [cellProbe, cellProbePython]

/**
 * Pixels per em for math set next to text in cells of this size.
 *
 * Monospace fonts advance about 0.6 em per cell (DejaVu Sans Mono, Menlo,
 * JetBrains Mono, Roboto Mono 1229/2048, SF Mono), so the text font's em is
 * cellWidth / 0.6. Computer Modern has a smaller x-height than those fonts
 * (0.43 em against 0.50-0.55 em), so emScale 1.15 lifts the math to match the
 * text. The cell height is no help: it includes the font's line gap and the
 * terminal's own adjustments (kitty's modify_font). No terminal reports its font
 * metrics to a child process; the font size alone wouldn't do either, since
 * converting points to pixels needs the monitor's DPI and scale.
 */
export function emPxForCell(cell: Pick<CellSize, 'cellWidth' | 'cellHeight'>, emScale = 1.15): number {
  return (cell.cellWidth / 0.6) * emScale
}
