import{z5,Cn,_9,j4,q2,B6,_5,j2,k6,y6,un,sh,Dn,yn,kn,ch,ah,rh,oh,dh,ph,hh,gh,G5,J9,Nn,Eh,Ah,Hn,wh,w7,_n,Bh,Fh,tC}from'./p19.js';export*from'./p19.js';
var H4=new z5;
function N1(e,C){return H4.parse(e,C)}
N1.options=N1.setOptions=function(e){return H4.setOptions(e),N1.defaults=H4.defaults,Cn(N1.defaults),N1};
N1.getDefaults=_9;
N1.defaults=j4;
N1.use=function(...e){return H4.use(...e),N1.defaults=H4.defaults,Cn(N1.defaults),N1};
N1.walkTokens=function(e,C){return H4.walkTokens(e,C)};
N1.parseInline=H4.parseInline;
N1.Parser=q2;
N1.parser=q2.parse;
N1.Renderer=B6;
N1.TextRenderer=_5;
N1.Lexer=j2;
N1.lexer=j2.lex;
N1.Tokenizer=k6;
N1.Hooks=y6;
N1.parse=N1;
var FM=N1.options;
var vM=N1.setOptions;
var SM=N1.use;
var RM=N1.walkTokens;
var TM=N1.parseInline;
var NM=q2.parse;
var OM=j2.lex;
var U9=/(^|[^\w./-])([A-Za-z0-9][\w-]*\/[A-Za-z0-9][\w.-]*)#(\d+)\b/g;
var xn=/[\x00-\x1f\x7f-\x9f]/;
var Jp=/^[a-z][a-z0-9+.-]*:/i;
var Ch=/^(?!.*(?:^|\/)\.\.(?:\/|#|$))[A-Za-z0-9_][A-Za-z0-9._~/=&+@,!*'()$;-]*(?:#[A-Za-z0-9._~/=&+@,!*'()$;:-]*)?$/;
function th(e){return xn.test(e)||e!==e.trim()||/^https:\/\/claude\.ai(?:[/?#]|$)/.test(e)?!1:Jp.test(e)?!/^file:/i.test(e):Ch.test(e)}
function q4(e,C){e.text+=C;for(let t=0;t<C.length;t++)e.source.push(-1)}
function q9(e,C){e.text+=C.text,e.source.push(...C.source)}
function pn(e,C,t,L,n){let{hyperlinks:i}=L;if(i===void 0)return!1;let s=C.href,r=C.title?` ("${C.title}")`:"";if(xn.test(s+r)||s.includes("\u29C9"))return!1;let o=C.raw.indexOf(C.text);if(C.text!==""&&o<0)return!1;if(s.startsWith("mailto:")){let u=s.slice(7);if(C.text!==""){let x={text:C.text,source:Array.from(C.text,(p,h)=>t+o+h)};q9(e,x),C.text!==u&&q4(e,` (${u})`)}else q4(e,u);return q4(e,r),!0}let a={text:"",source:[]};if(!n(a,C.tokens??[],C.text,t+o)||a.text.includes("\u29C9"))return!1;let l=a.text!==""&&a.text!==s;if(i){if(!th(s))return!1;L.linked&&(L.linked.value=!0),a.text!==""?q9(e,a):q4(e,s)}else{let u=a.text===s||s===`http://${a.text}`||s===`https://${a.text}`;l&&!u?(q9(e,a),q4(e,` (${s})`)):q4(e,s)}return q4(e,r),!0}
function hn(e,C){if(!e.includes("#"))return!0;let t=e.replace(U9,(L,n,i,s)=>`${n}\0${i}#${s}\0`);return t===e?!0:t.replace(C,"\xA0$1").replaceAll("\0","")===e.replace(C,"\xA0$1")}
function dn(e){return U9.lastIndex=0,U9.test(e)}
function fn(e){let C=e.FORCE_HYPERLINK;if(C!==void 0)return C.length>0?parseInt(C,10)!==0:void 0;let t=e.TERM_PROGRAM;if(t!==void 0&&un.includes(t)||e.TERMINAL_EMULATOR==="JetBrains-JediTerm"||e.WT_SESSION&&t!=="tmux"&&!e.TMUX)return!0;if(t==="tmux"){let[L,n]=(e.TERM_PROGRAM_VERSION??"").split(".").map(i=>parseInt(i,10));if(L>3||L===3&&n>=4)return!0}if(e.LC_TERMINAL!==void 0&&un.includes(e.LC_TERMINAL)||e.TERM?.includes("kitty")||e.NETLIFY)return!0;if(e.CI||e.TEAMCITY_VERSION)return!1;if(!(e.WT_SESSION||t==="WezTerm"||t==="vscode"||e.VTE_VERSION||e.TERM==="alacritty"))return!1}
var _2=new z5({gfm:!0,tokenizer:{del(e){let C=/^~~(?=[^\s~])((?:\\.|[^\\])*?(?:\\.|[^\s~\\]))~~(?=[^~]|$)/.exec(e),t=C?.[1];if(!(!C||t===void 0))return{type:"del",raw:C[0],text:t,tokens:this.lexer.inlineTokens(t)}},def(){}}});
var Mn=/[#*`|[>\-_~]|\n[\r\n]|\r\r|\r\n[\r\n]|(?:^|[\r\n]) {0,3}(?:\d+[.)]|\+) |(?:^|[\r\n]) {0,3}=+ *(?:[\r\n]|$)|https?:\/\/|www\./;
var Lh=/&(?:nbsp|#0{0,4}160|#[xX]0{0,4}[aA]0);/g;
var nh=/^<(?:[a-zA-Z][a-zA-Z0-9+.-]{1,31}:[^\s\x00-\x1f<>]*|[a-zA-Z0-9.!#$%&'*+/=?_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+(?![-_]))>/;
var mn=/ (\d{1,9}[.)])(?!\w)/g;
function An(e){return Q3(e)!==void 0}
function Q3(e){let C=e.search(/[\t\r\u0000-\u0008\u000b-\u001f\u007f]/);for(let t of e.matchAll(/<[A-Za-z/!?]/g)){if(C>=0&&t.index>=C)break;if(!nh.test(e.slice(t.index))){C=t.index;break}}return C<0?void 0:e.lastIndexOf(`
`,C-1)+1}
function i3(e,C){return e.includes("\u29C9")?!C.linked?.value&&!(C.hyperlinks!==!1&&dn(e)):!0}
var U4=/ {2}|(?:^|\n) /;
function K3(e,C,t=e.text.length){let L=t;for(;L>0&&e.text[L-1]!==" "&&e.text[L-1]!==`
`;)L--;L>0&&L--;for(let n=L;n<e.text.length;n++)e.source[n]>=0&&(C=Math.min(C,e.source[n]));return{text:e.text.slice(0,L),source:e.source.slice(0,L),stop:C}}
function F6(e,C={},t=!1){let L=!Mn.test(e)&&!e.includes("&nbsp;"),n=Q3(e);if(n===void 0)return gn(e,C,t,L,e);if(!t)return null;let i=gn(e.slice(0,n),C,!0,L,e);return i&&{...i,stop:Math.min(i.stop??1/0,n)}}
function gn(e,C,t,L,n){let i={hyperlinks:C.hyperlinks,linked:{value:!1}},s={text:"",source:[]};if(L)w6(s,e,0);else{let u;try{u=_2.lexer(e)}catch{return null}let x=0;for(let p of u){if(e.indexOf(p.raw,x)!==x)return null;if(p.type==="space")s.text+=`
`,s.source.push(-1);else if(p.type==="paragraph"){let d=p;if(!e.startsWith(d.text,x))return null;if(!U2(s,d.tokens,d.text,x,!1,i)){if(!t||s.stop===void 0)return null;break}s.text+=`
`,s.source.push(-1)}else{if(!t)return null;s.stop=x;break}x+=p.raw.length}if(s.stop===void 0&&x!==e.length)return null}if(!i3(n,i))return null;let r=/^\n*/.exec(s.text)[0].length,o=s.text.slice(r).trimEnd().length,a={text:s.text.slice(r,r+o),source:s.source.slice(r,r+o)};s.stop!==void 0&&(a=K3(a,s.stop));let l=U4.exec(a.text);if(l){if(!t)return null;a=K3(a,a.stop??1/0,l.index+1)}return a}
function w6(e,C,t){e.text+=C;for(let L=0;L<C.length;L++)e.source.push(t+L)}
function U2(e,C,t,L,n=!1,i={}){let s=0;for(let r of C){if(!t.startsWith(r.raw,s))return V9(e,e.text.length,L+s);let o=L+s,a=e.text.length;if(!ih(e,r,o,n,i))return V9(e,a,o);s+=r.raw.length}return s===t.length||V9(e,e.text.length,L+s)}
function V9(e,C,t){return e.text=e.text.slice(0,C),e.source.length=C,e.stop=Math.min(e.stop??1/0,t),!1}
function ih(e,C,t,L,n){switch(C.type){case"text":{let i=C;if(i.tokens||i.text!==i.raw)return!1;if(n.inside){w6(e,i.raw,t);break}let s=e.text.length;if(i.escaped===!1){let r=0;for(let o of i.raw.matchAll(Lh))w6(e,i.raw.slice(r,o.index),t+r),e.text+=" ",e.source.push(t+o.index),r=o.index+o[0].length;w6(e,i.raw.slice(r),t+r)}else w6(e,i.raw,t);if(L){let r=e.text.slice(s);if(n.hyperlinks!==!1&&!hn(r,mn))return!1;e.text=e.text.slice(0,s)+r.replace(mn,"\xA0$1")}break}case"escape":{let i=C;if(i.raw.length!==i.text.length+1||!i.raw.endsWith(i.text))return!1;w6(e,i.text,t+1);break}case"codespan":{let i=C;e.text+=i.text;for(let s=0;s<i.text.length;s++)e.source.push(-1);break}case"em":case"strong":case"del":{let i=C,s=i.raw.indexOf(i.text),r=i.raw.length-s-i.text.length;if(s<1||s!==r||!U2(e,i.tokens,i.text,t+s,L,n))return!1;break}case"link":{if(!pn(e,C,t,n,(r,o,a,l)=>U2(r,o,a,l,!1,{...n,inside:!0})))return!1;break}case"br":e.text+=`
`,e.source.push(-1);break;default:return!1}return!0}
function k7(e){if(!Mn.test(e)&&!e.includes("&nbsp;"))return e.trim()===""?[]:[{start:0,end:e.length,paragraph:!0}];let C;try{C=_2.lexer(e)}catch{return null}let t=[],L,n=()=>{if(!L)return;let s=L.types.join(",");t.push({start:L.start,end:L.end,paragraph:s==="paragraph",.../^(?:paragraph,)?list(?:,list)*$/.test(s)?{list:!0}:{},...s==="blockquote"?{quote:!0}:{},...s==="heading"?{heading:!0}:{},.../^(?:paragraph,)?table$/.test(s)?{table:!0}:{}}),L=void 0},i=0;for(let s of C){if(!e.startsWith(s.raw,i))return null;if(s.type==="space"&&/\n[ \t]*\n/.test(e.slice(Math.max(0,i-1),i+s.raw.length)))n();else if(s.type!=="space"||L){L||(L={start:i,end:i,types:[]});let r=s.raw.replace(/(?:\r?\n[ \t]*)+$/,"");L.end=i+(s.type==="space"?s.raw.length:r.length),s.type!=="space"&&L.types.push(s.type),s.type!=="space"&&/\n[ \t]*\n[ \t]*$/.test(s.raw)&&n()}i+=s.raw.length}return i!==e.length?null:(n(),t)}
function V4(e,C){let t=0,L=e.length-1;for(;t<=L;){let n=t+L>>1,[i,s]=e[n];if(C<i)L=n-1;else if(C>s)t=n+1;else return!0}return!1}
function X4(e){return V4(sh,e)?1:V4(Dn,e)?0:V4(yn,e)?2:-1}
var lh=e=>e>=127995&&e<=127999;
var En=e=>e>=127462&&e<=127487;
var uh=e=>e===35||e===42||e>=48&&e<=57;
var X9=e=>e>65535?2:1;
function Bn(e,C,t=!1){let L=e.codePointAt(C),n=C+X9(L),i=X4(L);if(t){let s=xh(e,C);s>n&&(n=s,i=2)}for(;n<e.length&&V4(Dn,e.charCodeAt(n));)(i===2||L===32)&&(i=-1),n+=1;return{start:C,end:n,width:i}}
function xh(e,C){let t=e.codePointAt(C),L=C+X9(t);if(En(t))return En(e.codePointAt(L)??0)?L+2:C;if(uh(t))return e.charCodeAt(L)===kn&&e.charCodeAt(L+1)===ch?L+2:C;let n=bn(e,C,!0);for(;n>C&&e.charCodeAt(n)===ah;){let i=bn(e,n+1,!1);if(i<0)break;n=i}return Math.max(C,n)}
function bn(e,C,t){let L=e.codePointAt(C);if(L===void 0)return-1;let n=C+X9(L),i=V4(yn,L);if(!i&&!V4(rh,L))return-1;let s=e.codePointAt(n)??0;return s===kn?n+1:lh(s)&&V4(oh,L)?n+2:i||!t?n:-1}
function $5(e,C=!1){let t=[];for(let L=0;L<e.length;){let n=Bn(e,L,C);t.push(n),L=n.end}return t}
function l2(e,C=!1){let t=0;for(let L of $5(e,C)){if(L.width<0)return-1;t+=L.width}return t}
function A3(e,C,t=!0,L=!1,n=!1){if(!(C>=1))return null;let i=new Int32Array(e.length),s=new Int32Array(e.length),r=new Uint8Array(e.length),o=new Int8Array(e.length).fill(-1),a=$5(e,L),l=[],u=0,x=0,p;for(let A=0;A<=a.length;A++){let k=a[A];if(k===void 0||k.end-k.start===1&&e.charCodeAt(k.start)===32)l.push({first:u,last:A,width:x}),u=A+1,x=0;else if(k.width<0){if(!n)return null;p=u>0?a[u-1].start:0;break}else x+=k.width}let h=0,d=0,m=0,b=()=>{h+=1,d=0,m=0},B=A=>{for(let k=A.start;k<A.end;k++)i[k]=h,s[k]=d-m;o[A.start]=A.width,d+=A.width};for(let[A,k]of l.entries()){if(A>0){let D=a[k.first-1].start;i[D]=h,s[D]=d,o[D]=1,d>=C&&(b(),m=1,i[D]=h,s[D]=0,r[D]=1),d+=1}if(t&&k.width>C){let D=C-d,v=1+Math.floor((k.width-D-1)/C);Math.floor((k.width-1)/C)<v&&b();for(let y=k.first;y<k.last;y++){let S=a[y];S.width>0&&d>0&&d+S.width>C&&b(),B(S),d===C&&y+1<k.last&&b()}continue}d+k.width>C&&d>0&&k.width>0&&b();for(let D=k.first;D<k.last;D++)B(a[D])}return p===void 0?{rows:h+1,row:i,col:s,hidden:r,cells:o}:{rows:h+1,row:i,col:s,hidden:r,cells:o,known:p}}
function wn(e,C,t=!1){let L=A3(e,C,!0,t);if(!L)return null;let n=Array.from({length:L.rows},()=>"");for(let i=0;i<e.length;i++){let s=L.row[i];L.hidden[i]||(n[s]=n[s]+e[i])}return n}
var E3=class{constructor(C,t=!1,L=!1){this.width=C;this.sequences=t;this.partial=L}width;sequences;partial;text=[];source=[];row=[];col=[];end=[];cells=[];rows=0;stop=1/0;halt(C){this.stop=Math.min(this.stop,C)}put(C,t,L){this.grow(t+1);for(let[n,i]of[...C].entries())this.cells[t][L+n]=i}draw(C,t,L,n){let i=t,s=0;for(let r of C.text.split(`
`)){let o=A3(r,n,!0,this.sequences,this.partial);if(!o)return!1;this.grow(i+o.rows);let a=o.known??r.length;for(let l=0;l<a;l++)this.unit(r[l],C.source[s+l],i+o.row[l],L+o.col[l],!o.hidden[l],o.cells[l]);if(a<r.length){for(let l=s+a;l<C.source.length;l++)C.source[l]>=0&&this.halt(C.source[l]);return C.stop!==void 0&&this.halt(C.stop),!1}this.text.push(`
`),this.source.push(-1),this.row.push(i+o.rows-1),this.col.push(-1),this.end.push(!1),i+=o.rows,s+=r.length+1}return this.text.pop(),this.source.pop(),this.row.pop(),this.col.pop(),this.end.pop(),C.stop!==void 0?(this.halt(C.stop),!1):(this.end.length>0&&(this.end[this.end.length-1]=!0),!0)}unit(C,t,L,n,i=!0,s){if(this.grow(L+1),this.text.push(C),this.source.push(t),this.row.push(L),this.col.push(n),this.end.push(!1),!i)return;let r=this.cells[L],o=C.charCodeAt(0),a;if(s===void 0?o>=56320&&o<=57343:s<0)r[n]=(r[n]??"")+C,a=s===void 0?X4(r[n].codePointAt(0)):0;else if(o<55296&&X4(o)===0){let l=Math.max(0,n-1);r[l]=(r[l]??"")+C;return}else r[n]=C,a=s??X4(o);a===2&&(r[n+1]="")}lines(){return this.grow(this.rows),this.cells.slice(0,this.rows).map(C=>Array.from(C,t=>t??" ").join("").replace(/ +$/,""))}grow(C){for(;this.cells.length<C;)this.cells.push([]);this.rows=Math.max(this.rows,C)}};
function K9(e,C,t={},L=!1){if(!(C>=1))return null;let n=Q3(e);if(n!==void 0){if(!L||n===0)return null;let x=K9(e.slice(0,n),C,t,!0);return x?.halt(n),x}let i={hyperlinks:t.hyperlinks,linked:{value:!1}},s;try{s=_2.lexer(e)}catch{return null}let r=new E3(C,t.emojiSequences===!0,L),o=()=>L&&r.stop<1/0&&i3(e,i)?r:null,a=0,l=!1,u="";for(let x of s){if(!e.startsWith(x.raw,a))return null;let p={text:x.raw,map:Array.from({length:x.raw.length},(h,d)=>a+d)};if(x.type==="paragraph"&&!l&&a===0){let h=x,d=vn([{tokens:h.tokens??[],text:h.text,at:0}],p,!1,i,L);if(!d||!Sn(d,C,L)||!r.draw(d,0,0,C))return o()}else if(x.type==="list"&&(!l||u==="list")){if(l=!0,!Fn(r,x,p,0,0,i))return o()}else if(x.type!=="space"||!l)return!L||!l?null:(r.halt(a),o());a+=x.raw.length,u=x.type}return l&&a===e.length&&i3(e,i)?r:null}
function Fn(e,C,t,L,n,i){if(C.items.length===0||C.items.length>dh)return!1;let s=C.start===""||C.start===void 0?1:Number(C.start),r=s+C.items.length-1,o=0;for(let[a,l]of C.items.entries()){if(!t.text.startsWith(l.raw,o))return!1;let u=C.ordered?B7(n,s+a,s,r):"-",x=a>0&&Rn(C.items[a-1]),p={text:l.raw,map:t.map.slice(o,o+l.raw.length)};if(!fh(e,l,p,u,L,n,x,i))return e.stop===1/0&&e.halt(p.map[0]??0),!1;o+=l.raw.length}return/^\s*$/.test(t.text.slice(o))}
function fh(e,C,t,L,n,i,s,r){if(C.task)return!1;let o=Q9(C,t);if(!o)return!1;let a=[],l=0,u;for(let b of C.tokens){if(b.type==="list"){let A=b;if(A.ordered&&A.items.every(D=>D.tokens.length===0))return!1;let k=o.text.indexOf(A.raw,l);if(k<0)return!1;a.push({kind:"list",list:A,raw:{text:A.raw,map:o.map.slice(k,k+A.raw.length)}}),l=k+A.raw.length;continue}let B=a.at(-1);if(B?.kind!=="inline"&&a.push(B={kind:"inline",runs:[],newlines:""}),b.type==="space")B.runs.push({space:!0});else if(b.type==="text"){let A=b,k=o.text.indexOf(A.text,l);if(k<0||!A.tokens)return!1;B.runs.push({tokens:A.tokens,text:A.text,at:k}),l=k+A.text.length}else{let A=o.text.indexOf(b.raw.trimStart(),l);u=o.map[A<0?l:A]??t.map[0]??0;break}}if(a[0]?.kind!=="inline")return!1;let x=Math.max(2,Z9(L)+1),p=Math.min(n+x,ph),h=n+x,d=e.width-h,m=s;for(let[b,B]of a.entries()){if(B.kind==="list"){let F=e.rows+(m?1:0);if(e.rows=F,!Fn(e,B.list,B.raw,p,i+1,r))return!1;m=!1;continue}let A=vn(B.runs,o,!0,r,e.partial);if(!A)return!1;let k=A.lead;if(A.text===""&&b>0&&A.stop===void 0){m||=A.newline;continue}if(d<hh)return!1;let D=Sn(A,d,e.partial);if(!D||D.text===""&&(b===0||D.stop===void 0))return D?.stop!==void 0&&e.halt(D.stop),!1;let v=e.rows+(m||b>0&&k?1:0);if(b===0&&e.put(L,v,n),!e.draw(D,v,h,d))return!1;m=A.blankAfter}return u===void 0?!0:(e.halt(u),!1)}
function vn(e,C,t,L,n=!1){let i={text:"",source:[]};for(let x of e){if(x.space){i.text+=`
`,i.source.push(-1);continue}let p={text:"",source:[]},h=U2(p,x.tokens,x.text,x.at,t,L);if(!h&&(!n||p.stop===void 0))return null;i.text+=p.text+(h?`
`:"");for(let d of p.source)i.source.push(d<0?-1:C.map[d]??-1);if(h){i.source.push(-1);continue}i.stop=C.map[p.stop]??C.map.at(-1)??0;break}let s=i.text,r=/^\n*/.exec(s)[0].length,o=i.stop===void 0?s.slice(r).trimEnd().length:s.length-r,a=s.slice(r,r+o),l=i.source.slice(r,r+o);return{...i.stop===void 0?{text:a,source:l}:K3({text:a,source:l},i.stop),lead:s.startsWith(`
`),blankAfter:i.stop===void 0&&/\n\s*\n$/.test(s)&&s.endsWith(`
`),newline:s.includes(`
`)}}
function Sn(e,C,t){let L=0;for(let n of e.text.split(`
`)){if(U4.test(n)&&!(l2(n)>=0&&l2(n)<=C))return t?{...e,...K3(e,e.stop??1/0,L===0?0:L)}:null;L+=n.length+1}return e}
function Q9(e,C){let t=e.text.split(`
`),L=C.text.split(`
`);if(t.length>L.length)return null;let n=[],i=0;for(let[s,r]of t.entries()){let o=L[s];if(!o.endsWith(r))return null;let a=i+o.length-r.length;for(let l=0;l<r.length;l++)n.push(C.map[a+l]);s<t.length-1&&n.push(C.map[i+o.length]??-1),i+=o.length+1}return{text:e.text,map:n}}
function Rn(e){let C=e.tokens.at(-1);if(C?.type==="space")return!0;if(C?.type==="list"){let t=C.items.at(-1);return t?Rn(t):!1}return!1}
function B7(e,C,t,L){return e===1&&t>=1?`${mh(C)}.`:e===2&&t>=1&&L<=3999?`${Mh(C)}.`:`${C}.`}
function mh(e){let C="";for(;e>0;)e-=1,C=String.fromCharCode(97+e%26)+C,e=Math.floor(e/26);return C}
function Mh(e){let C="";for(let[t,L]of gh)for(;e>=t;)C+=L,e-=t;return C}
function Z9(e){let C=0;for(let t of e)C+=Math.max(0,X4(t.codePointAt(0)));return C}
function Tn(e,C,t={},L=!1){let n=Y9(e,t,L);if(!n||!(C>=1))return null;let i=new E3(C,t.emojiSequences===!0,L);return i.draw(n,0,0,C)||i.stop<1/0?i:null}
function Y9(e,C={},t=!1){let L=Q3(e);if(L!==void 0){if(!t||L===0)return null;let m=Y9(e.slice(0,L-1),C,!0);return m&&{...m,stop:Math.min(m.stop??1/0,L)}}let n={hyperlinks:C.hyperlinks,linked:{value:!1}},i;try{i=_2.lexer(e)}catch{return null}let s=i[0];if(s?.type!=="heading")return null;let r=i.slice(1).some(m=>m.type!=="space");if(r&&!t)return null;let{text:o,raw:a}=s;if(!e.startsWith(a)||o==="")return null;let l=/^ {0,3}(?:#{1,6}[ \t]+)?/.exec(a)[0].length;if(!a.startsWith(o,l))return null;let u={text:"",source:[]},x=U2(u,s.tokens,o,l,!1,n);if(!x&&!(t&&u.stop!==void 0)||!i3(e,n))return null;let p=x?u.text.trimEnd().length:u.text.length,h={text:u.text.slice(0,p),source:u.source.slice(0,p)};if(x||(h=K3(h,u.stop)),x&&h.text===""||h.text.startsWith(`
`))return null;let d=U4.exec(h.text);if(d){if(!t)return null;h=K3(h,h.stop??1/0,d.index+1)}return r&&h.stop===void 0?{...h,stop:a.length}:h}
var bh=/\S {2}/;
function CC(e,C,t={},L=!1){if(!(C>G5))return null;let n=A=>{let k=e.lastIndexOf(`
`,A-1)+1;if(!L||k<=0||k>=e.length)return null;let D=CC(e.slice(0,k-1),C,t,!0);return D?.halt(k),D},i=Q3(e);if(i!==void 0)return n(i);let s=e.endsWith(`
`)?e:e+`
`,r;try{r=_2.lexer(s)}catch{return null}let o=r[0];if(o?.type!=="blockquote"||!s.startsWith(o.raw))return null;if(r.slice(1).some(A=>A.type!=="space"))return n(o.raw.length);let a={text:s,map:Array.from({length:s.length},(A,k)=>k)},l={hyperlinks:t.hyperlinks,linked:{value:!1}},u={at:1/0},x=On(o,a,0,0,l,u);if(!x)return u.at<1/0?n(u.at):null;if(!i3(e,l))return null;let p=/^\n*/.exec(x.text)[0].length,h=x.text.slice(p).trimEnd().length,d={text:x.text.slice(p,p+h),source:x.source.slice(p,p+h)};if(d.text==="")return null;let m=t.emojiSequences===!0,b=0;for(let A of d.text.split(`
`)){let k=l2(A,m);if(bh.test(A)&&!(k>=0&&k<=C-G5)){let D=d.source.slice(b,b+A.length).find(v=>v>=0);return D===void 0?null:n(D)}b+=A.length+1}let B=new E3(C,m,L);if(!B.draw(d,0,G5,C-G5)&&B.stop===1/0)return null;for(let A=0;A<B.rows;A++)B.put(J9,A,0);return B}
var Z3=class{text="";source=[];add(C,t=-1){this.text+=C;for(let L=0;L<C.length;L++)this.source.push(t<0?-1:t+L);return this}append(C){return this.text+=C.text,this.source.push(...C.source),this}lines(){let C=[],t=0;for(let L of this.text.split(`
`))C.push({text:L,source:this.source.slice(t,t+L.length)}),t+=L.length+1;return C}};
function On(e,C,t,L,n,i={at:1/0}){if(L>=Nn)return null;let s=Dh(C,t,e);if(!s){let l=e.raw.split(`
`),u=l.findIndex((x,p)=>p>0&&x.trim()!==""&&!/^ {0,3}>/.test(x));return u>0&&(i.at=Math.min(i.at,C.map[t+l.slice(0,u).join(`
`).length+1]??1/0)),null}let r=new Z3,o=0,a=l=>(i.at===1/0&&(i.at=s.map[l]??1/0),null);for(let l of e.tokens){let u=s.text.indexOf(l.raw,o);if(u<0||/\S/.test(s.text.slice(o,u)))return a(o);let x=yh(l,s,u,L,n,i);if(!x)return a(u);r.append(x),o=u+l.raw.length}return/\S/.test(s.text.slice(o))?a(o):r}
function Dh(e,C,t){if(!e.text.startsWith(t.raw,C))return null;let L="",n=[],i=C;for(let[s,r]of t.raw.split(`
`).entries()){s>0&&(L+=`
`,n.push(e.map[i-1]??-1));let o=/^ {0,3}>[ \t]?/.exec(r)?.[0].length??0;L+=r.slice(o);for(let a=o;a<r.length;a++)n.push(e.map[i+a]??-1);i+=r.length+1}return L===t.text?{text:L,map:n}:L.endsWith(`
`)&&L.slice(0,-1)===t.text?{text:t.text,map:n.slice(0,-1)}:null}
function yh(e,C,t,L,n,i){switch(e.type){case"space":return new Z3().add(`
`);case"paragraph":case"heading":{let s=e,r=e.type==="heading"?t+/^ {0,3}(?:#{1,6}[ \t]+)?/.exec(s.raw)[0].length:t;if(!C.text.startsWith(s.text,r)||s.text==="")return null;let o=In(s.tokens,s.text,r,C,!1,n,i);return o?o.add(e.type==="heading"?`

`:`
`):null}case"blockquote":{let s=On(e,C,t,L+1,n,i);if(!s)return null;let r=new Z3;for(let[o,a]of s.lines().entries())o>0&&r.add(`
`),a.text.trim()!==""&&r.add(J9+" "),r.append(a);return r}case"list":return Pn(e,{text:e.raw,map:C.map.slice(t,t+e.raw.length)},0,"",n,i);default:return null}}
function In(e,C,t,L,n,i,s){let r={text:"",source:[]};if(!U2(r,e,C,t,n,i))return s&&s.at===1/0&&r.stop!==void 0&&(s.at=L.map[r.stop]??1/0),null;let o=new Z3;return o.text=r.text,o.source=r.source.map(a=>a<0?-1:L.map[a]??-1),o}
function Pn(e,C,t,L,n,i){if(t>=Nn||e.items.length===0||e.items.length>Eh)return null;let s=e.start===""||e.start===void 0?1:Number(e.start),r=s+e.items.length-1,o=new Z3,a=0;for(let[l,u]of e.items.entries()){if(!C.text.startsWith(u.raw,a))return null;let x=e.ordered?B7(t,s+l,s,r):"-",p=kh(u,{text:u.raw,map:C.map.slice(a,a+u.raw.length)},x,t,L,n,i);if(!p)return null;o.append(p),a+=u.raw.length}return/^\s*$/.test(C.text.slice(a))?o:null}
function kh(e,C,t,L,n,i,s){if(e.task)return null;let r=Q9(e,C);if(!r)return null;let o=n+" ".repeat(Z9(t)+1),a=" ".repeat(Math.min(o.length,Ah)),l=e.tokens.slice(Math.max(0,e.tokens.findIndex(h=>h.type!=="space")));if(l[0]?.type!=="text")return null;let u=new Z3,x=!1,p=0;for(let h of l)if(h.type==="space")u.add(`
`);else if(h.type==="list"){let d=h;if(d.ordered&&d.items.every(B=>B.tokens.length===0))return null;let m=r.text.indexOf(d.raw,p);if(m<0)return null;let b=Pn(d,{text:d.raw,map:r.map.slice(m,m+d.raw.length)},L+1,a,i,s);if(!b)return null;u.append(b),p=m+d.raw.length}else if(h.type==="text"){let d=h,m=r.text.indexOf(d.text,p);if(m<0||!d.tokens)return null;let b=In(d.tokens,d.text,m,r,!0,i,s);if(!b)return null;for(let[B,A]of b.add(`
`).lines().entries())B>0&&u.add(`
`),B===0?u.add(x?o:`${n}${t} `):A.text!==""&&u.add(o),u.append(A);x=!0,p=m+d.text.length}else{let d=r.text.indexOf(h.raw.trimStart(),p);return s&&s.at===1/0&&(s.at=r.map[d<0?p:d]??1/0),null}return u}
function eC(e,C=-1){return{text:e,source:Array.from({length:e.length},()=>C)}}
function zn(...e){return{text:e.map(C=>C.text).join(""),source:e.flatMap(C=>C.source)}}
function jn(e,C,t=e.text.length){return{text:e.text.slice(C,t),source:e.source.slice(C,t)}}
function LC(e){let C=e.text.length-e.text.trimStart().length;return jn(e,C,C+e.text.trim().length)}
function nC(e,C,t,L){let n=jn(e,0,e.text.trimEnd().length);if(n.text==="")return[{units:[],width:0}];let i=A3(n.text,C,t,L);if(!i)return null;let s=Array.from({length:i.rows},()=>({units:[],width:0})),r=new Uint8Array(i.rows);for(let a=0;a<n.text.length;a++)i.hidden[a]&&(r[i.row[a]]=1);for(let a=0;a<n.text.length;a++){let l=s[i.row[a]],u=i.hidden[a]?0:i.col[a]+r[i.row[a]],x=i.cells[a];l.units.push({unit:n.text[a],source:n.source[a],col:u,cells:x}),l.width+=Math.max(0,x)}let o=s.filter(a=>a.units.length>0);return o.length>0?o:[{units:[],width:0}]}
function Wn(e){return{text:e.units.map(C=>C.unit).join(""),source:e.units.map(C=>C.source)}}
function qn(e,C,t=C-Hn,L={}){if(An(e)||!(C>=1)||!(t>=1))return null;let n;try{n=_2.lexer(e)}catch{return null}let i={hyperlinks:L.hyperlinks,linked:{value:!1}},s=L.emojiSequences===!0,r=new E3(C,s),o=0,a,l=0;for(let u of n){if(!e.startsWith(u.raw,o))return null;if(u.type==="paragraph"&&o===0){let x=F6(u.raw,L);if(!x)return null;let p=Un(r,x,t);if(p===null)return null;l=p+1}else if(u.type==="table"&&!a){if(a=u,!Rh(r,a,e.slice(o,o+u.raw.length),o,l,C,i,s))return null}else if(u.type!=="space"||!a)return null;o+=u.raw.length}return a&&o===e.length&&i3(e,i)?r:null}
function Un(e,C,t,L=0){return e.draw(C,L,0,t)?e.rows-L:null}
function $n(e,C,t){let L=[],n=0;for(let s=0;s<e.length;s++){if(e[s]!=="|")continue;let r=!1;for(let o=s-1;o>=0&&e[o]==="\\";o--)r=!r;r||(L.push([n,s]),n=s+1)}L.push([n,e.length]);let i=([s,r])=>e.slice(s,r).trim()==="";if(L.length>0&&i(L[0])&&L.shift(),L.length>0&&i(L.at(-1))&&L.pop(),t!==void 0)for(L.length>t&&L.splice(t);L.length<t;)L.push([e.length,e.length]);return L.map(([s,r])=>{let o=e.slice(s,r),a=o.length-o.trimStart().length,l=s+a+o.trim().length,u="",x=[];for(let p=s+a;p<l;p++)e[p]==="\\"&&e[p+1]==="|"&&p+1<l?(u+="|",x.push(C+p+1),p+=1):(u+=e[p],x.push(C+p));return{text:u,map:x}})}
function vh(e){if(!e.includes("`")||!e.includes("|"))return!0;let C=[],t=[];for(let i=0;i<e.length;){if(e[i]!=="`"){i++;continue}let s=0;for(;e[i+s]==="`";)s++;C.push(i),t.push(s),i+=s}let L=new Array(C.length).fill(-1),n=new Map;for(let i=C.length-1;i>=0;i--){let s=n.get(t[i]);s!==void 0&&(L[i]=s),n.set(t[i],i)}for(let i=0;i<C.length;){let s=L[i];if(s===-1){i++;continue}let r=e.slice(C[i]+t[i],C[s]);for(let o of r.matchAll(/(\\*)\|/g))if(o[1].length%2===0)return!1;i=s+1}return!0}
function Sh(e){let C=e.replace(/\|/g,(t,L,n)=>{let i=!1;for(let s=L-1;s>=0&&n[s]==="\\";s--)i=!i;return i?"|":" |"}).split(/ \|/);return C[0]?.trim()||C.shift(),C.length>0&&!C.at(-1)?.trim()&&C.pop(),C}
function Rh(e,C,t,L,n,i,s,r){let o=t.split(`
`);if(!o.every(vh))return!1;for(let z=2;z<o.length;z++){let j=Sh(o[z]);for(let W=C.header.length;W<j.length;W++)if(j[W].trim())return!1}if(C.rows.length>wh||C.header.length===0)return!1;let a=[];for(let z=0,j=L;z<o.length;z++)a.push(j),j+=o[z].length+1;let l=o.slice(2);for(;l.length>0&&l.at(-1).trim()==="";)l.pop();if(l.length!==C.rows.length)return!1;let u=(z,j)=>{if(!j||j.text!==z.text)return null;let W={text:"",source:[]};return!U2(W,z.tokens,z.text,0,!1,s)||l2(W.text,r)<0||/^\s|\s$/.test(W.text)?null:{text:W.text,source:W.source.map(X=>X<0?-1:j.map[X]??-1)}},x=$n(o[0],a[0]);if(x.length!==C.header.length)return!1;let p=[];for(let[z,j]of C.header.entries()){let W=u(j,x[z]);if(!W)return!1;p.push(W)}let h=[];for(let[z,j]of C.rows.entries()){let W=$n(l[z],a[z+2],C.header.length),X=[];for(let[t1,J]of j.entries()){let e1=u(J,W[t1]);if(!e1)return!1;X.push(e1)}if(X.length!==C.header.length)return!1;h.push(X)}let d=p.length,m=[p,...h],b=z=>Math.max(w7,...z.split(/\s+/).filter(j=>j.length>0).map(j=>l2(j,r))),B=p.map((z,j)=>Math.max(...m.map(W=>b(W[j].text)))),A=p.map((z,j)=>Math.max(...m.map(W=>Math.max(l2(W[j].text,r),w7)))),k=Math.max(i-(1+d*3)-_n,d*w7),D=B.reduce((z,j)=>z+j,0),v=A.reduce((z,j)=>z+j,0),F=!1,y;if(v<=k)y=A;else if(D<=k){let z=k-D,j=A.map((X,t1)=>X-B[t1]),W=j.reduce((X,t1)=>X+t1,0);y=B.map((X,t1)=>W===0?X:X+Math.floor(j[t1]/W*z))}else{F=!0;let z=k/D;y=B.map(j=>Math.max(Math.floor(j*z),w7))}let S=[];for(let z of m){let j=[];for(let[W,X]of z.entries()){let t1=nC(X,y[W],F,r);if(!t1)return!1;j.push(t1)}S.push(j)}if(Math.max(1,...S.flatMap(z=>z.map(j=>j.length)))>Bh)return Gn(e,p,h,n,i,r);let U=(z,j,W)=>{let X=z;for(let[t1,J]of y.entries())X+="\u2500".repeat(J+2)+(t1<d-1?j:W);return{put:[[X,0]],units:[],width:l2(X)}},H=(z,j)=>{let W=Math.max(1,...z.map(t1=>t1.length)),X=[];for(let t1=0;t1<W;t1++){let J={put:[["\u2502",0]],units:[],width:0},e1=1;for(let[u1,d1]of z.entries()){let m1=t1-Math.floor((W-d1.length)/2),p1=m1>=0&&m1<d1.length?d1[m1]:{units:[],width:0},l1=Math.max(0,y[u1]-p1.width),y1=j?"center":C.align[u1]??"left",w2=y1==="center"?Math.floor(l1/2):y1==="right"?l1:0;e1+=1;for(let g3 of p1.units)J.units.push({...g3,col:e1+w2+g3.col});e1+=p1.width+l1+1,J.put.push(["\u2502",e1]),e1+=1}J.width=e1,X.push(J)}return X},q=[U("\u250C","\u252C","\u2510"),...H(S[0],!0),U("\u251C","\u253C","\u2524")];for(let[z,j]of S.slice(1).entries())q.push(...H(j,!1)),z<h.length-1&&q.push(U("\u251C","\u253C","\u2524"));if(q.push(U("\u2514","\u2534","\u2518")),Math.max(...q.map(z=>z.width))>i-_n)return Gn(e,p,h,n,i,r);for(let[z,j]of q.entries()){e.grow(n+z+1);for(let[W,X]of j.put)e.put(W,n+z,X);for(let W of j.units)e.unit(W.unit,W.source,n+z,W.col,!0,W.cells)}return!0}
function Gn(e,C,t,L,n,i){let s=C.map(LC),r=eC("\u2500".repeat(Math.max(0,Math.min(n-1,Fh)))),o=[];for(let x of t){let p=[];for(let[h,d]of x.entries()){let m=s[h]??tC;if(/\s\s/.test(d.text))return!1;let b=LC({text:d.text.replace(/\s/g," "),source:d.source});if(m.text===""&&b.text==="")continue;let B=m.text!==""?n-l2(m.text,i)-3:n-1,A=n-3,k=nC(b,Math.max(B,10),!1,i);if(!k)return!1;let D=k.map(Wn);if(D.length>1){let v=[];for(let[y,S]of D.slice(1).entries())y>0&&v.push(eC(" ")),v.push(LC(S));let F=nC(zn(...v),A,!1,i);if(!F)return!1;D=[D[0],...F.map(Wn)]}p.push(m.text!==""?zn(m,eC(": "),D[0]??tC):D[0]??tC);for(let v of D.slice(1))v.text.trim()!==""&&p.push(v)}p.length!==0&&(o.length>0&&o.push(r),o.push(...p))}let a=n-Hn;if(a<1)return!1;for(let x of o)if(U4.test(x.text)&&l2(x.text.trimEnd(),i)>a)return!1;let l=o.map(x=>x.text).join(`
`);return Un(e,{text:l,source:o.flatMap((x,p)=>p>0?[-1,...x.source]:x.source)},a,L)!==null}
export{k7,_2,F6,A3,K9,Tn,CC,qn,l2,$5,fn,wn};
