import{I5,VL,R9,$4,H2,D6,O5,G2,b6,E6,nn,_p,fn,mn,gn,Gp,$p,Wp,zp,Xp,Up,Vp,Zp,W5,V9,yn,Ch,Jp,In,sh,D7,Sn,ih,rh,K9}from'./p19.js';export*from'./p19.js';
var z4=new I5;
function N1(e,C){return z4.parse(e,C)}
N1.options=N1.setOptions=function(e){return z4.setOptions(e),N1.defaults=z4.defaults,VL(N1.defaults),N1};
N1.getDefaults=R9;
N1.defaults=$4;
N1.use=function(...e){return z4.use(...e),N1.defaults=z4.defaults,VL(N1.defaults),N1};
N1.walkTokens=function(e,C){return z4.walkTokens(e,C)};
N1.parseInline=z4.parseInline;
N1.Parser=H2;
N1.parser=H2.parse;
N1.Renderer=D6;
N1.TextRenderer=O5;
N1.Lexer=G2;
N1.lexer=G2.lex;
N1.Tokenizer=b6;
N1.Hooks=E6;
N1.parse=N1;
var LM=N1.options;
var nM=N1.setOptions;
var iM=N1.use;
var sM=N1.walkTokens;
var rM=N1.parseInline;
var oM=H2.parse;
var aM=G2.lex;
var z9=/(^|[^\w./-])([A-Za-z0-9][\w-]*\/[A-Za-z0-9][\w.-]*)#(\d+)\b/g;
var sn=/[\x00-\x1f\x7f-\x9f]/;
var Sp=/^[a-z][a-z0-9+.-]*:/i;
var Rp=/^(?!.*(?:^|\/)\.\.(?:\/|#|$))[A-Za-z0-9_][A-Za-z0-9._~/=&+@,!*'()$;-]*(?:#[A-Za-z0-9._~/=&+@,!*'()$;:-]*)?$/;
function Tp(e){return sn.test(e)||e!==e.trim()||/^https:\/\/claude\.ai(?:[/?#]|$)/.test(e)?!1:Sp.test(e)?!/^file:/i.test(e):Rp.test(e)}
function G4(e,C){e.text+=C;for(let t=0;t<C.length;t++)e.source.push(-1)}
function W9(e,C){e.text+=C.text,e.source.push(...C.source)}
function rn(e,C,t,L,n){let{hyperlinks:i}=L;if(i===void 0)return!1;let s=C.href,r=C.title?` ("${C.title}")`:"";if(sn.test(s+r)||s.includes("\u29C9"))return!1;let o=C.raw.indexOf(C.text);if(C.text!==""&&o<0)return!1;if(s.startsWith("mailto:")){let u=s.slice(7);if(C.text!==""){let x={text:C.text,source:Array.from(C.text,(p,h)=>t+o+h)};W9(e,x),C.text!==u&&G4(e,` (${u})`)}else G4(e,u);return G4(e,r),!0}let c={text:"",source:[]};if(!n(c,C.tokens??[],C.text,t+o)||c.text.includes("\u29C9"))return!1;let l=c.text!==""&&c.text!==s;if(i){if(!Tp(s))return!1;L.linked&&(L.linked.value=!0),c.text!==""?W9(e,c):G4(e,s)}else{let u=c.text===s||s===`http://${c.text}`||s===`https://${c.text}`;l&&!u?(W9(e,c),G4(e,` (${s})`)):G4(e,s)}return G4(e,r),!0}
function on(e,C){if(!e.includes("#"))return!0;let t=e.replace(z9,(L,n,i,s)=>`${n}\0${i}#${s}\0`);return t===e?!0:t.replace(C,"\xA0$1").replaceAll("\0","")===e.replace(C,"\xA0$1")}
function an(e){return z9.lastIndex=0,z9.test(e)}
function cn(e){let C=e.FORCE_HYPERLINK;if(C!==void 0)return C.length>0?parseInt(C,10)!==0:void 0;let t=e.TERM_PROGRAM;if(t!==void 0&&nn.includes(t)||e.TERMINAL_EMULATOR==="JetBrains-JediTerm"||e.WT_SESSION&&t!=="tmux"&&!e.TMUX)return!0;if(t==="tmux"){let[L,n]=(e.TERM_PROGRAM_VERSION??"").split(".").map(i=>parseInt(i,10));if(L>3||L===3&&n>=4)return!0}if(e.LC_TERMINAL!==void 0&&nn.includes(e.LC_TERMINAL)||e.TERM?.includes("kitty")||e.NETLIFY)return!0;if(e.CI||e.TEAMCITY_VERSION)return!1;if(!(e.WT_SESSION||t==="WezTerm"||t==="vscode"||e.VTE_VERSION||e.TERM==="alacritty"))return!1}
var I2=new I5({gfm:!0,tokenizer:{del(e){let C=/^~~(?=[^\s~])((?:\\.|[^\\])*?(?:\\.|[^\s~\\]))~~(?=[^~]|$)/.exec(e),t=C?.[1];if(!(!C||t===void 0))return{type:"del",raw:C[0],text:t,tokens:this.lexer.inlineTokens(t)}},def(){}}});
var xn=/[#*`|[>\-_~]|\n[\r\n]|\r\r|\r\n[\r\n]|(?:^|[\r\n]) {0,3}(?:\d+[.)]|\+) |(?:^|[\r\n]) {0,3}=+ *(?:[\r\n]|$)|https?:\/\/|www\./;
var Op=/&(?:nbsp|#0{0,4}160|#[xX]0{0,4}[aA]0);/g;
var Ip=/^<(?:[a-zA-Z][a-zA-Z0-9+.-]{1,31}:[^\s\x00-\x1f<>]*|[a-zA-Z0-9.!#$%&'*+/=?_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+(?![-_]))>/;
var ln=/ (\d{1,9}[.)])(?!\w)/g;
function pn(e){return V3(e)!==void 0}
function V3(e){let C=e.search(/[\t\r\u0000-\u0008\u000b-\u001f\u007f]/);for(let t of e.matchAll(/<[A-Za-z/!?]/g)){if(C>=0&&t.index>=C)break;if(!Ip.test(e.slice(t.index))){C=t.index;break}}return C<0?void 0:e.lastIndexOf(`
`,C-1)+1}
function L3(e,C){return e.includes("\u29C9")?!C.linked?.value&&!(C.hyperlinks!==!1&&an(e)):!0}
var H4=/ {2}|(?:^|\n) /;
function U3(e,C,t=e.text.length){let L=t;for(;L>0&&e.text[L-1]!==" "&&e.text[L-1]!==`
`;)L--;L>0&&L--;for(let n=L;n<e.text.length;n++)e.source[n]>=0&&(C=Math.min(C,e.source[n]));return{text:e.text.slice(0,L),source:e.source.slice(0,L),stop:C}}
function B6(e,C={},t=!1){let L=!xn.test(e)&&!e.includes("&nbsp;"),n=V3(e);if(n===void 0)return un(e,C,t,L,e);if(!t)return null;let i=un(e.slice(0,n),C,!0,L,e);return i&&{...i,stop:Math.min(i.stop??1/0,n)}}
function un(e,C,t,L,n){let i={hyperlinks:C.hyperlinks,linked:{value:!1}},s={text:"",source:[]};if(L)k6(s,e,0);else{let u;try{u=I2.lexer(e)}catch{return null}let x=0;for(let p of u){if(e.indexOf(p.raw,x)!==x)return null;if(p.type==="space")s.text+=`
`,s.source.push(-1);else if(p.type==="paragraph"){let d=p;if(!e.startsWith(d.text,x))return null;if(!j2(s,d.tokens,d.text,x,!1,i)){if(!t||s.stop===void 0)return null;break}s.text+=`
`,s.source.push(-1)}else{if(!t)return null;s.stop=x;break}x+=p.raw.length}if(s.stop===void 0&&x!==e.length)return null}if(!L3(n,i))return null;let r=/^\n*/.exec(s.text)[0].length,o=s.text.slice(r).trimEnd().length,c={text:s.text.slice(r,r+o),source:s.source.slice(r,r+o)};s.stop!==void 0&&(c=U3(c,s.stop));let l=H4.exec(c.text);if(l){if(!t)return null;c=U3(c,c.stop??1/0,l.index+1)}return c}
function k6(e,C,t){e.text+=C;for(let L=0;L<C.length;L++)e.source.push(t+L)}
function j2(e,C,t,L,n=!1,i={}){let s=0;for(let r of C){if(!t.startsWith(r.raw,s))return $9(e,e.text.length,L+s);let o=L+s,c=e.text.length;if(!Pp(e,r,o,n,i))return $9(e,c,o);s+=r.raw.length}return s===t.length||$9(e,e.text.length,L+s)}
function $9(e,C,t){return e.text=e.text.slice(0,C),e.source.length=C,e.stop=Math.min(e.stop??1/0,t),!1}
function Pp(e,C,t,L,n){switch(C.type){case"text":{let i=C;if(i.tokens||i.text!==i.raw)return!1;if(n.inside){k6(e,i.raw,t);break}let s=e.text.length;if(i.escaped===!1){let r=0;for(let o of i.raw.matchAll(Op))k6(e,i.raw.slice(r,o.index),t+r),e.text+=" ",e.source.push(t+o.index),r=o.index+o[0].length;k6(e,i.raw.slice(r),t+r)}else k6(e,i.raw,t);if(L){let r=e.text.slice(s);if(n.hyperlinks!==!1&&!on(r,ln))return!1;e.text=e.text.slice(0,s)+r.replace(ln,"\xA0$1")}break}case"escape":{let i=C;if(i.raw.length!==i.text.length+1||!i.raw.endsWith(i.text))return!1;k6(e,i.text,t+1);break}case"codespan":{let i=C;e.text+=i.text;for(let s=0;s<i.text.length;s++)e.source.push(-1);break}case"em":case"strong":case"del":{let i=C,s=i.raw.indexOf(i.text),r=i.raw.length-s-i.text.length;if(s<1||s!==r||!j2(e,i.tokens,i.text,t+s,L,n))return!1;break}case"link":{if(!rn(e,C,t,n,(r,o,c,l)=>j2(r,o,c,l,!1,{...n,inside:!0})))return!1;break}case"br":e.text+=`
`,e.source.push(-1);break;default:return!1}return!0}
function E7(e){if(!xn.test(e)&&!e.includes("&nbsp;"))return e.trim()===""?[]:[{start:0,end:e.length,paragraph:!0}];let C;try{C=I2.lexer(e)}catch{return null}let t=[],L,n=()=>{if(!L)return;let s=L.types.join(",");t.push({start:L.start,end:L.end,paragraph:s==="paragraph",.../^(?:paragraph,)?list(?:,list)*$/.test(s)?{list:!0}:{},...s==="blockquote"?{quote:!0}:{},...s==="heading"?{heading:!0}:{},.../^(?:paragraph,)?table$/.test(s)?{table:!0}:{}}),L=void 0},i=0;for(let s of C){if(!e.startsWith(s.raw,i))return null;if(s.type==="space"&&/\n[ \t]*\n/.test(e.slice(Math.max(0,i-1),i+s.raw.length)))n();else if(s.type!=="space"||L){L||(L={start:i,end:i,types:[]});let r=s.raw.replace(/(?:\r?\n[ \t]*)+$/,"");L.end=i+(s.type==="space"?s.raw.length:r.length),s.type!=="space"&&L.types.push(s.type),s.type!=="space"&&/\n[ \t]*\n[ \t]*$/.test(s.raw)&&n()}i+=s.raw.length}return i!==e.length?null:(n(),t)}
function j4(e,C){let t=0,L=e.length-1;for(;t<=L;){let n=t+L>>1,[i,s]=e[n];if(C<i)L=n-1;else if(C>s)t=n+1;else return!0}return!1}
function q4(e){return j4(_p,e)?1:j4(fn,e)?0:j4(mn,e)?2:-1}
var Hp=e=>e>=127995&&e<=127999;
var hn=e=>e>=127462&&e<=127487;
var jp=e=>e===35||e===42||e>=48&&e<=57;
var G9=e=>e>65535?2:1;
function Mn(e,C,t=!1){let L=e.codePointAt(C),n=C+G9(L),i=q4(L);if(t){let s=qp(e,C);s>n&&(n=s,i=2)}for(;n<e.length&&j4(fn,e.charCodeAt(n));)(i===2||L===32)&&(i=-1),n+=1;return{start:C,end:n,width:i}}
function qp(e,C){let t=e.codePointAt(C),L=C+G9(t);if(hn(t))return hn(e.codePointAt(L)??0)?L+2:C;if(jp(t))return e.charCodeAt(L)===gn&&e.charCodeAt(L+1)===Gp?L+2:C;let n=dn(e,C,!0);for(;n>C&&e.charCodeAt(n)===$p;){let i=dn(e,n+1,!1);if(i<0)break;n=i}return Math.max(C,n)}
function dn(e,C,t){let L=e.codePointAt(C);if(L===void 0)return-1;let n=C+G9(L),i=j4(mn,L);if(!i&&!j4(Wp,L))return-1;let s=e.codePointAt(n)??0;return s===gn?n+1:Hp(s)&&j4(zp,L)?n+2:i||!t?n:-1}
function _5(e,C=!1){let t=[];for(let L=0;L<e.length;){let n=Mn(e,L,C);t.push(n),L=n.end}return t}
function c2(e,C=!1){let t=0;for(let L of _5(e,C)){if(L.width<0)return-1;t+=L.width}return t}
function g3(e,C,t=!0,L=!1,n=!1){if(!(C>=1))return null;let i=new Int32Array(e.length),s=new Int32Array(e.length),r=new Uint8Array(e.length),o=new Int8Array(e.length).fill(-1),c=_5(e,L),l=[],u=0,x=0,p;for(let E=0;E<=c.length;E++){let w=c[E];if(w===void 0||w.end-w.start===1&&e.charCodeAt(w.start)===32)l.push({first:u,last:E,width:x}),u=E+1,x=0;else if(w.width<0){if(!n)return null;p=u>0?c[u-1].start:0;break}else x+=w.width}let h=0,d=0,M=0,b=()=>{h+=1,d=0,M=0},y=E=>{for(let w=E.start;w<E.end;w++)i[w]=h,s[w]=d-M;o[E.start]=E.width,d+=E.width};for(let[E,w]of l.entries()){if(E>0){let D=c[w.first-1].start;i[D]=h,s[D]=d,o[D]=1,d>=C&&(b(),M=1,i[D]=h,s[D]=0,r[D]=1),d+=1}if(t&&w.width>C){let D=C-d,S=1+Math.floor((w.width-D-1)/C);Math.floor((w.width-1)/C)<S&&b();for(let k=w.first;k<w.last;k++){let v=c[k];v.width>0&&d>0&&d+v.width>C&&b(),y(v),d===C&&k+1<w.last&&b()}continue}d+w.width>C&&d>0&&w.width>0&&b();for(let D=w.first;D<w.last;D++)y(c[D])}return p===void 0?{rows:h+1,row:i,col:s,hidden:r,cells:o}:{rows:h+1,row:i,col:s,hidden:r,cells:o,known:p}}
function An(e,C,t=!1){let L=g3(e,C,!0,t);if(!L)return null;let n=Array.from({length:L.rows},()=>"");for(let i=0;i<e.length;i++){let s=L.row[i];L.hidden[i]||(n[s]=n[s]+e[i])}return n}
var M3=class{constructor(C,t=!1,L=!1){this.width=C;this.sequences=t;this.partial=L}width;sequences;partial;text=[];source=[];row=[];col=[];end=[];cells=[];rows=0;stop=1/0;halt(C){this.stop=Math.min(this.stop,C)}put(C,t,L){this.grow(t+1);for(let[n,i]of[...C].entries())this.cells[t][L+n]=i}draw(C,t,L,n){let i=t,s=0;for(let r of C.text.split(`
`)){let o=g3(r,n,!0,this.sequences,this.partial);if(!o)return!1;this.grow(i+o.rows);let c=o.known??r.length;for(let l=0;l<c;l++)this.unit(r[l],C.source[s+l],i+o.row[l],L+o.col[l],!o.hidden[l],o.cells[l]);if(c<r.length){for(let l=s+c;l<C.source.length;l++)C.source[l]>=0&&this.halt(C.source[l]);return C.stop!==void 0&&this.halt(C.stop),!1}this.text.push(`
`),this.source.push(-1),this.row.push(i+o.rows-1),this.col.push(-1),this.end.push(!1),i+=o.rows,s+=r.length+1}return this.text.pop(),this.source.pop(),this.row.pop(),this.col.pop(),this.end.pop(),C.stop!==void 0?(this.halt(C.stop),!1):(this.end.length>0&&(this.end[this.end.length-1]=!0),!0)}unit(C,t,L,n,i=!0,s){if(this.grow(L+1),this.text.push(C),this.source.push(t),this.row.push(L),this.col.push(n),this.end.push(!1),!i)return;let r=this.cells[L],o=C.charCodeAt(0),c;if(s===void 0?o>=56320&&o<=57343:s<0)r[n]=(r[n]??"")+C,c=s===void 0?q4(r[n].codePointAt(0)):0;else if(o<55296&&q4(o)===0){let l=Math.max(0,n-1);r[l]=(r[l]??"")+C;return}else r[n]=C,c=s??q4(o);c===2&&(r[n+1]="")}lines(){return this.grow(this.rows),this.cells.slice(0,this.rows).map(C=>Array.from(C,t=>t??" ").join("").replace(/ +$/,""))}grow(C){for(;this.cells.length<C;)this.cells.push([]);this.rows=Math.max(this.rows,C)}};
function H9(e,C,t={},L=!1){if(!(C>=1))return null;let n=V3(e);if(n!==void 0){if(!L||n===0)return null;let x=H9(e.slice(0,n),C,t,!0);return x?.halt(n),x}let i={hyperlinks:t.hyperlinks,linked:{value:!1}},s;try{s=I2.lexer(e)}catch{return null}let r=new M3(C,t.emojiSequences===!0,L),o=()=>L&&r.stop<1/0&&L3(e,i)?r:null,c=0,l=!1,u="";for(let x of s){if(!e.startsWith(x.raw,c))return null;let p={text:x.raw,map:Array.from({length:x.raw.length},(h,d)=>c+d)};if(x.type==="paragraph"&&!l&&c===0){let h=x,d=bn([{tokens:h.tokens??[],text:h.text,at:0}],p,!1,i,L);if(!d||!Dn(d,C,L)||!r.draw(d,0,0,C))return o()}else if(x.type==="list"&&(!l||u==="list")){if(l=!0,!En(r,x,p,0,0,i))return o()}else if(x.type!=="space"||!l)return!L||!l?null:(r.halt(c),o());c+=x.raw.length,u=x.type}return l&&c===e.length&&L3(e,i)?r:null}
function En(e,C,t,L,n,i){if(C.items.length===0||C.items.length>Xp)return!1;let s=C.start===""||C.start===void 0?1:Number(C.start),r=s+C.items.length-1,o=0;for(let[c,l]of C.items.entries()){if(!t.text.startsWith(l.raw,o))return!1;let u=C.ordered?b7(n,s+c,s,r):"-",x=c>0&&kn(C.items[c-1]),p={text:l.raw,map:t.map.slice(o,o+l.raw.length)};if(!Kp(e,l,p,u,L,n,x,i))return e.stop===1/0&&e.halt(p.map[0]??0),!1;o+=l.raw.length}return/^\s*$/.test(t.text.slice(o))}
function Kp(e,C,t,L,n,i,s,r){if(C.task)return!1;let o=j9(C,t);if(!o)return!1;let c=[],l=0,u;for(let b of C.tokens){if(b.type==="list"){let E=b;if(E.ordered&&E.items.every(D=>D.tokens.length===0))return!1;let w=o.text.indexOf(E.raw,l);if(w<0)return!1;c.push({kind:"list",list:E,raw:{text:E.raw,map:o.map.slice(w,w+E.raw.length)}}),l=w+E.raw.length;continue}let y=c.at(-1);if(y?.kind!=="inline"&&c.push(y={kind:"inline",runs:[],newlines:""}),b.type==="space")y.runs.push({space:!0});else if(b.type==="text"){let E=b,w=o.text.indexOf(E.text,l);if(w<0||!E.tokens)return!1;y.runs.push({tokens:E.tokens,text:E.text,at:w}),l=w+E.text.length}else{let E=o.text.indexOf(b.raw.trimStart(),l);u=o.map[E<0?l:E]??t.map[0]??0;break}}if(c[0]?.kind!=="inline")return!1;let x=Math.max(2,q9(L)+1),p=Math.min(n+x,Up),h=n+x,d=e.width-h,M=s;for(let[b,y]of c.entries()){if(y.kind==="list"){let F=e.rows+(M?1:0);if(e.rows=F,!En(e,y.list,y.raw,p,i+1,r))return!1;M=!1;continue}let E=bn(y.runs,o,!0,r,e.partial);if(!E)return!1;let w=E.lead;if(E.text===""&&b>0&&E.stop===void 0){M||=E.newline;continue}if(d<Vp)return!1;let D=Dn(E,d,e.partial);if(!D||D.text===""&&(b===0||D.stop===void 0))return D?.stop!==void 0&&e.halt(D.stop),!1;let S=e.rows+(M||b>0&&w?1:0);if(b===0&&e.put(L,S,n),!e.draw(D,S,h,d))return!1;M=E.blankAfter}return u===void 0?!0:(e.halt(u),!1)}
function bn(e,C,t,L,n=!1){let i={text:"",source:[]};for(let x of e){if(x.space){i.text+=`
`,i.source.push(-1);continue}let p={text:"",source:[]},h=j2(p,x.tokens,x.text,x.at,t,L);if(!h&&(!n||p.stop===void 0))return null;i.text+=p.text+(h?`
`:"");for(let d of p.source)i.source.push(d<0?-1:C.map[d]??-1);if(h){i.source.push(-1);continue}i.stop=C.map[p.stop]??C.map.at(-1)??0;break}let s=i.text,r=/^\n*/.exec(s)[0].length,o=i.stop===void 0?s.slice(r).trimEnd().length:s.length-r,c=s.slice(r,r+o),l=i.source.slice(r,r+o);return{...i.stop===void 0?{text:c,source:l}:U3({text:c,source:l},i.stop),lead:s.startsWith(`
`),blankAfter:i.stop===void 0&&/\n\s*\n$/.test(s)&&s.endsWith(`
`),newline:s.includes(`
`)}}
function Dn(e,C,t){let L=0;for(let n of e.text.split(`
`)){if(H4.test(n)&&!(c2(n)>=0&&c2(n)<=C))return t?{...e,...U3(e,e.stop??1/0,L===0?0:L)}:null;L+=n.length+1}return e}
function j9(e,C){let t=e.text.split(`
`),L=C.text.split(`
`);if(t.length>L.length)return null;let n=[],i=0;for(let[s,r]of t.entries()){let o=L[s];if(!o.endsWith(r))return null;let c=i+o.length-r.length;for(let l=0;l<r.length;l++)n.push(C.map[c+l]);s<t.length-1&&n.push(C.map[i+o.length]??-1),i+=o.length+1}return{text:e.text,map:n}}
function kn(e){let C=e.tokens.at(-1);if(C?.type==="space")return!0;if(C?.type==="list"){let t=C.items.at(-1);return t?kn(t):!1}return!1}
function b7(e,C,t,L){return e===1&&t>=1?`${Qp(C)}.`:e===2&&t>=1&&L<=3999?`${Yp(C)}.`:`${C}.`}
function Qp(e){let C="";for(;e>0;)e-=1,C=String.fromCharCode(97+e%26)+C,e=Math.floor(e/26);return C}
function Yp(e){let C="";for(let[t,L]of Zp)for(;e>=t;)C+=L,e-=t;return C}
function q9(e){let C=0;for(let t of e)C+=Math.max(0,q4(t.codePointAt(0)));return C}
function Bn(e,C,t={},L=!1){let n=U9(e,t,L);if(!n||!(C>=1))return null;let i=new M3(C,t.emojiSequences===!0,L);return i.draw(n,0,0,C)||i.stop<1/0?i:null}
function U9(e,C={},t=!1){let L=V3(e);if(L!==void 0){if(!t||L===0)return null;let M=U9(e.slice(0,L-1),C,!0);return M&&{...M,stop:Math.min(M.stop??1/0,L)}}let n={hyperlinks:C.hyperlinks,linked:{value:!1}},i;try{i=I2.lexer(e)}catch{return null}let s=i[0];if(s?.type!=="heading")return null;let r=i.slice(1).some(M=>M.type!=="space");if(r&&!t)return null;let{text:o,raw:c}=s;if(!e.startsWith(c)||o==="")return null;let l=/^ {0,3}(?:#{1,6}[ \t]+)?/.exec(c)[0].length;if(!c.startsWith(o,l))return null;let u={text:"",source:[]},x=j2(u,s.tokens,o,l,!1,n);if(!x&&!(t&&u.stop!==void 0)||!L3(e,n))return null;let p=x?u.text.trimEnd().length:u.text.length,h={text:u.text.slice(0,p),source:u.source.slice(0,p)};if(x||(h=U3(h,u.stop)),x&&h.text===""||h.text.startsWith(`
`))return null;let d=H4.exec(h.text);if(d){if(!t)return null;h=U3(h,h.stop??1/0,d.index+1)}return r&&h.stop===void 0?{...h,stop:c.length}:h}
var th=/\S {2}/;
function X9(e,C,t={},L=!1){if(!(C>W5))return null;let n=E=>{let w=e.lastIndexOf(`
`,E-1)+1;if(!L||w<=0||w>=e.length)return null;let D=X9(e.slice(0,w-1),C,t,!0);return D?.halt(w),D},i=V3(e);if(i!==void 0)return n(i);let s=e.endsWith(`
`)?e:e+`
`,r;try{r=I2.lexer(s)}catch{return null}let o=r[0];if(o?.type!=="blockquote"||!s.startsWith(o.raw))return null;if(r.slice(1).some(E=>E.type!=="space"))return n(o.raw.length);let c={text:s,map:Array.from({length:s.length},(E,w)=>w)},l={hyperlinks:t.hyperlinks,linked:{value:!1}},u={at:1/0},x=wn(o,c,0,0,l,u);if(!x)return u.at<1/0?n(u.at):null;if(!L3(e,l))return null;let p=/^\n*/.exec(x.text)[0].length,h=x.text.slice(p).trimEnd().length,d={text:x.text.slice(p,p+h),source:x.source.slice(p,p+h)};if(d.text==="")return null;let M=t.emojiSequences===!0,b=0;for(let E of d.text.split(`
`)){let w=c2(E,M);if(th.test(E)&&!(w>=0&&w<=C-W5)){let D=d.source.slice(b,b+E.length).find(S=>S>=0);return D===void 0?null:n(D)}b+=E.length+1}let y=new M3(C,M,L);if(!y.draw(d,0,W5,C-W5)&&y.stop===1/0)return null;for(let E=0;E<y.rows;E++)y.put(V9,E,0);return y}
var X3=class{text="";source=[];add(C,t=-1){this.text+=C;for(let L=0;L<C.length;L++)this.source.push(t<0?-1:t+L);return this}append(C){return this.text+=C.text,this.source.push(...C.source),this}lines(){let C=[],t=0;for(let L of this.text.split(`
`))C.push({text:L,source:this.source.slice(t,t+L.length)}),t+=L.length+1;return C}};
function wn(e,C,t,L,n,i={at:1/0}){if(L>=yn)return null;let s=eh(C,t,e);if(!s){let l=e.raw.split(`
`),u=l.findIndex((x,p)=>p>0&&x.trim()!==""&&!/^ {0,3}>/.test(x));return u>0&&(i.at=Math.min(i.at,C.map[t+l.slice(0,u).join(`
`).length+1]??1/0)),null}let r=new X3,o=0,c=l=>(i.at===1/0&&(i.at=s.map[l]??1/0),null);for(let l of e.tokens){let u=s.text.indexOf(l.raw,o);if(u<0||/\S/.test(s.text.slice(o,u)))return c(o);let x=Lh(l,s,u,L,n,i);if(!x)return c(u);r.append(x),o=u+l.raw.length}return/\S/.test(s.text.slice(o))?c(o):r}
function eh(e,C,t){if(!e.text.startsWith(t.raw,C))return null;let L="",n=[],i=C;for(let[s,r]of t.raw.split(`
`).entries()){s>0&&(L+=`
`,n.push(e.map[i-1]??-1));let o=/^ {0,3}>[ \t]?/.exec(r)?.[0].length??0;L+=r.slice(o);for(let c=o;c<r.length;c++)n.push(e.map[i+c]??-1);i+=r.length+1}return L===t.text?{text:L,map:n}:L.endsWith(`
`)&&L.slice(0,-1)===t.text?{text:t.text,map:n.slice(0,-1)}:null}
function Lh(e,C,t,L,n,i){switch(e.type){case"space":return new X3().add(`
`);case"paragraph":case"heading":{let s=e,r=e.type==="heading"?t+/^ {0,3}(?:#{1,6}[ \t]+)?/.exec(s.raw)[0].length:t;if(!C.text.startsWith(s.text,r)||s.text==="")return null;let o=Fn(s.tokens,s.text,r,C,!1,n,i);return o?o.add(e.type==="heading"?`

`:`
`):null}case"blockquote":{let s=wn(e,C,t,L+1,n,i);if(!s)return null;let r=new X3;for(let[o,c]of s.lines().entries())o>0&&r.add(`
`),c.text.trim()!==""&&r.add(V9+" "),r.append(c);return r}case"list":return vn(e,{text:e.raw,map:C.map.slice(t,t+e.raw.length)},0,"",n,i);default:return null}}
function Fn(e,C,t,L,n,i,s){let r={text:"",source:[]};if(!j2(r,e,C,t,n,i))return s&&s.at===1/0&&r.stop!==void 0&&(s.at=L.map[r.stop]??1/0),null;let o=new X3;return o.text=r.text,o.source=r.source.map(c=>c<0?-1:L.map[c]??-1),o}
function vn(e,C,t,L,n,i){if(t>=yn||e.items.length===0||e.items.length>Ch)return null;let s=e.start===""||e.start===void 0?1:Number(e.start),r=s+e.items.length-1,o=new X3,c=0;for(let[l,u]of e.items.entries()){if(!C.text.startsWith(u.raw,c))return null;let x=e.ordered?b7(t,s+l,s,r):"-",p=nh(u,{text:u.raw,map:C.map.slice(c,c+u.raw.length)},x,t,L,n,i);if(!p)return null;o.append(p),c+=u.raw.length}return/^\s*$/.test(C.text.slice(c))?o:null}
function nh(e,C,t,L,n,i,s){if(e.task)return null;let r=j9(e,C);if(!r)return null;let o=n+" ".repeat(q9(t)+1),c=" ".repeat(Math.min(o.length,Jp)),l=e.tokens.slice(Math.max(0,e.tokens.findIndex(h=>h.type!=="space")));if(l[0]?.type!=="text")return null;let u=new X3,x=!1,p=0;for(let h of l)if(h.type==="space")u.add(`
`);else if(h.type==="list"){let d=h;if(d.ordered&&d.items.every(y=>y.tokens.length===0))return null;let M=r.text.indexOf(d.raw,p);if(M<0)return null;let b=vn(d,{text:d.raw,map:r.map.slice(M,M+d.raw.length)},L+1,c,i,s);if(!b)return null;u.append(b),p=M+d.raw.length}else if(h.type==="text"){let d=h,M=r.text.indexOf(d.text,p);if(M<0||!d.tokens)return null;let b=Fn(d.tokens,d.text,M,r,!0,i,s);if(!b)return null;for(let[y,E]of b.add(`
`).lines().entries())y>0&&u.add(`
`),y===0?u.add(x?o:`${n}${t} `):E.text!==""&&u.add(o),u.append(E);x=!0,p=M+d.text.length}else{let d=r.text.indexOf(h.raw.trimStart(),p);return s&&s.at===1/0&&(s.at=r.map[d<0?p:d]??1/0),null}return u}
function Q9(e,C=-1){return{text:e,source:Array.from({length:e.length},()=>C)}}
function Rn(...e){return{text:e.map(C=>C.text).join(""),source:e.flatMap(C=>C.source)}}
function Pn(e,C,t=e.text.length){return{text:e.text.slice(C,t),source:e.source.slice(C,t)}}
function Z9(e){let C=e.text.length-e.text.trimStart().length;return Pn(e,C,C+e.text.trim().length)}
function Y9(e,C,t,L){let n=Pn(e,0,e.text.trimEnd().length);if(n.text==="")return[{units:[],width:0}];let i=g3(n.text,C,t,L);if(!i)return null;let s=Array.from({length:i.rows},()=>({units:[],width:0})),r=new Uint8Array(i.rows);for(let c=0;c<n.text.length;c++)i.hidden[c]&&(r[i.row[c]]=1);for(let c=0;c<n.text.length;c++){let l=s[i.row[c]],u=i.hidden[c]?0:i.col[c]+r[i.row[c]],x=i.cells[c];l.units.push({unit:n.text[c],source:n.source[c],col:u,cells:x}),l.width+=Math.max(0,x)}let o=s.filter(c=>c.units.length>0);return o.length>0?o:[{units:[],width:0}]}
function Tn(e){return{text:e.units.map(C=>C.unit).join(""),source:e.units.map(C=>C.source)}}
function _n(e,C,t=C-In,L={}){if(pn(e)||!(C>=1)||!(t>=1))return null;let n;try{n=I2.lexer(e)}catch{return null}let i={hyperlinks:L.hyperlinks,linked:{value:!1}},s=L.emojiSequences===!0,r=new M3(C,s),o=0,c,l=0;for(let u of n){if(!e.startsWith(u.raw,o))return null;if(u.type==="paragraph"&&o===0){let x=B6(u.raw,L);if(!x)return null;let p=Wn(r,x,t);if(p===null)return null;l=p+1}else if(u.type==="table"&&!c){if(c=u,!ch(r,c,e.slice(o,o+u.raw.length),o,l,C,i,s))return null}else if(u.type!=="space"||!c)return null;o+=u.raw.length}return c&&o===e.length&&L3(e,i)?r:null}
function Wn(e,C,t,L=0){return e.draw(C,L,0,t)?e.rows-L:null}
function Nn(e,C,t){let L=[],n=0;for(let s=0;s<e.length;s++){if(e[s]!=="|")continue;let r=!1;for(let o=s-1;o>=0&&e[o]==="\\";o--)r=!r;r||(L.push([n,s]),n=s+1)}L.push([n,e.length]);let i=([s,r])=>e.slice(s,r).trim()==="";if(L.length>0&&i(L[0])&&L.shift(),L.length>0&&i(L.at(-1))&&L.pop(),t!==void 0)for(L.length>t&&L.splice(t);L.length<t;)L.push([e.length,e.length]);return L.map(([s,r])=>{let o=e.slice(s,r),c=o.length-o.trimStart().length,l=s+c+o.trim().length,u="",x=[];for(let p=s+c;p<l;p++)e[p]==="\\"&&e[p+1]==="|"&&p+1<l?(u+="|",x.push(C+p+1),p+=1):(u+=e[p],x.push(C+p));return{text:u,map:x}})}
function oh(e){if(!e.includes("`")||!e.includes("|"))return!0;let C=[],t=[];for(let i=0;i<e.length;){if(e[i]!=="`"){i++;continue}let s=0;for(;e[i+s]==="`";)s++;C.push(i),t.push(s),i+=s}let L=new Array(C.length).fill(-1),n=new Map;for(let i=C.length-1;i>=0;i--){let s=n.get(t[i]);s!==void 0&&(L[i]=s),n.set(t[i],i)}for(let i=0;i<C.length;){let s=L[i];if(s===-1){i++;continue}let r=e.slice(C[i]+t[i],C[s]);for(let o of r.matchAll(/(\\*)\|/g))if(o[1].length%2===0)return!1;i=s+1}return!0}
function ah(e){let C=e.replace(/\|/g,(t,L,n)=>{let i=!1;for(let s=L-1;s>=0&&n[s]==="\\";s--)i=!i;return i?"|":" |"}).split(/ \|/);return C[0]?.trim()||C.shift(),C.length>0&&!C.at(-1)?.trim()&&C.pop(),C}
function ch(e,C,t,L,n,i,s,r){let o=t.split(`
`);if(!o.every(oh))return!1;for(let W=2;W<o.length;W++){let j=ah(o[W]);for(let z=C.header.length;z<j.length;z++)if(j[z].trim())return!1}if(C.rows.length>sh||C.header.length===0)return!1;let c=[];for(let W=0,j=L;W<o.length;W++)c.push(j),j+=o[W].length+1;let l=o.slice(2);for(;l.length>0&&l.at(-1).trim()==="";)l.pop();if(l.length!==C.rows.length)return!1;let u=(W,j)=>{if(!j||j.text!==W.text)return null;let z={text:"",source:[]};return!j2(z,W.tokens,W.text,0,!1,s)||c2(z.text,r)<0||/^\s|\s$/.test(z.text)?null:{text:z.text,source:z.source.map(X=>X<0?-1:j.map[X]??-1)}},x=Nn(o[0],c[0]);if(x.length!==C.header.length)return!1;let p=[];for(let[W,j]of C.header.entries()){let z=u(j,x[W]);if(!z)return!1;p.push(z)}let h=[];for(let[W,j]of C.rows.entries()){let z=Nn(l[W],c[W+2],C.header.length),X=[];for(let[t1,J]of j.entries()){let e1=u(J,z[t1]);if(!e1)return!1;X.push(e1)}if(X.length!==C.header.length)return!1;h.push(X)}let d=p.length,M=[p,...h],b=W=>Math.max(D7,...W.split(/\s+/).filter(j=>j.length>0).map(j=>c2(j,r))),y=p.map((W,j)=>Math.max(...M.map(z=>b(z[j].text)))),E=p.map((W,j)=>Math.max(...M.map(z=>Math.max(c2(z[j].text,r),D7)))),w=Math.max(i-(1+d*3)-Sn,d*D7),D=y.reduce((W,j)=>W+j,0),S=E.reduce((W,j)=>W+j,0),F=!1,k;if(S<=w)k=E;else if(D<=w){let W=w-D,j=E.map((X,t1)=>X-y[t1]),z=j.reduce((X,t1)=>X+t1,0);k=y.map((X,t1)=>z===0?X:X+Math.floor(j[t1]/z*W))}else{F=!0;let W=w/D;k=y.map(j=>Math.max(Math.floor(j*W),D7))}let v=[];for(let W of M){let j=[];for(let[z,X]of W.entries()){let t1=Y9(X,k[z],F,r);if(!t1)return!1;j.push(t1)}v.push(j)}if(Math.max(1,...v.flatMap(W=>W.map(j=>j.length)))>ih)return On(e,p,h,n,i,r);let V=(W,j,z)=>{let X=W;for(let[t1,J]of k.entries())X+="\u2500".repeat(J+2)+(t1<d-1?j:z);return{put:[[X,0]],units:[],width:c2(X)}},H=(W,j)=>{let z=Math.max(1,...W.map(t1=>t1.length)),X=[];for(let t1=0;t1<z;t1++){let J={put:[["\u2502",0]],units:[],width:0},e1=1;for(let[u1,d1]of W.entries()){let m1=t1-Math.floor((z-d1.length)/2),p1=m1>=0&&m1<d1.length?d1[m1]:{units:[],width:0},l1=Math.max(0,k[u1]-p1.width),k1=j?"center":C.align[u1]??"left",y2=k1==="center"?Math.floor(l1/2):k1==="right"?l1:0;e1+=1;for(let f3 of p1.units)J.units.push({...f3,col:e1+y2+f3.col});e1+=p1.width+l1+1,J.put.push(["\u2502",e1]),e1+=1}J.width=e1,X.push(J)}return X},q=[V("\u250C","\u252C","\u2510"),...H(v[0],!0),V("\u251C","\u253C","\u2524")];for(let[W,j]of v.slice(1).entries())q.push(...H(j,!1)),W<h.length-1&&q.push(V("\u251C","\u253C","\u2524"));if(q.push(V("\u2514","\u2534","\u2518")),Math.max(...q.map(W=>W.width))>i-Sn)return On(e,p,h,n,i,r);for(let[W,j]of q.entries()){e.grow(n+W+1);for(let[z,X]of j.put)e.put(z,n+W,X);for(let z of j.units)e.unit(z.unit,z.source,n+W,z.col,!0,z.cells)}return!0}
function On(e,C,t,L,n,i){let s=C.map(Z9),r=Q9("\u2500".repeat(Math.max(0,Math.min(n-1,rh)))),o=[];for(let x of t){let p=[];for(let[h,d]of x.entries()){let M=s[h]??K9;if(/\s\s/.test(d.text))return!1;let b=Z9({text:d.text.replace(/\s/g," "),source:d.source});if(M.text===""&&b.text==="")continue;let y=M.text!==""?n-c2(M.text,i)-3:n-1,E=n-3,w=Y9(b,Math.max(y,10),!1,i);if(!w)return!1;let D=w.map(Tn);if(D.length>1){let S=[];for(let[k,v]of D.slice(1).entries())k>0&&S.push(Q9(" ")),S.push(Z9(v));let F=Y9(Rn(...S),E,!1,i);if(!F)return!1;D=[D[0],...F.map(Tn)]}p.push(M.text!==""?Rn(M,Q9(": "),D[0]??K9):D[0]??K9);for(let S of D.slice(1))S.text.trim()!==""&&p.push(S)}p.length!==0&&(o.length>0&&o.push(r),o.push(...p))}let c=n-In;if(c<1)return!1;for(let x of o)if(H4.test(x.text)&&c2(x.text.trimEnd(),i)>c)return!1;let l=o.map(x=>x.text).join(`
`);return Wn(e,{text:l,source:o.flatMap((x,p)=>p>0?[-1,...x.source]:x.source)},c,L)!==null}
export{E7,I2,B6,g3,H9,Bn,X9,_n,c2,_5,cn,An};
