import{v7,_2,v6,A3,CC,zn,iC,Zn,u2,Yh,O7,oi,xC,ri,N7,I7,Cd,td,cd,Ei,ld,yi,xi,xd,Ri,V5}from'./p20.js';export*from'./p20.js';
var Jn=new Set(["table","blockquote"]);
var qh=new Set(["paragraph","list","heading","code","table","blockquote","hr"]);
function Ci(e){let C=v7(e);if(!C)return null;let t=[];for(let L of C){let n=t.length>0,i=L.paragraph||L.quote?null:Uh(e,L.start,L.end);if(i)t.push(...i.map((s,r)=>({...s,...r===0?{gap:n}:{},block:L.start})));else{let s=L.paragraph?"paragraph":L.list?"list":L.quote?"blockquote":L.heading?"heading":L.table?"table":"block";t.push({...L,type:s,gap:n,block:L.start})}}return t}
function Uh(e,C,t){let L=e.slice(C,t),n;try{n=_2.lexer(L)}catch{return null}let i=[],s=0;for(let r of n){if(!L.startsWith(r.raw,s))return null;if(!qh.has(r.type)||r.type==="code"&&r.text===""){let l=i.at(-1);return l?(l.end=t,i):null}let o=r.raw.replace(/(?:\r?\n[ \t]*)+$/,""),c=i.at(-1);r.type==="list"&&c?.type==="list"?c.end=C+s+o.length:i.push({start:C+s,end:C+s+o.length,paragraph:r.type==="paragraph",...r.type==="list"?{list:!0}:{},...r.type==="blockquote"?{quote:!0}:{},...r.type==="heading"?{heading:!0}:{},...r.type==="table"?{table:!0}:{},type:r.type,gap:c!==void 0&&ti(c.type,r.type)}),s+=r.raw.length}return s!==L.length||i.length===0?null:i}
function ti(e,C){return e==="heading"||Jn.has(e)||Jn.has(C)}
function Vh(e,C,t=[],L={},n=!1){let i=v6(e,L,n);if(!i)return null;let{text:s,source:r}=i,o=i.stop??1/0,c=new Int32Array(s.length),l=new Int32Array(s.length),u=[],x=0,p=0;for(let E of s.split(`
`)){let w=A3(E,C,!0,L.emojiSequences===!0,n);if(!w)return null;let b=w.known??E.length,B=u.length;for(let y=0;y<w.rows;y++)u.push("");for(let y=0;y<b;y++){c[p+y]=x+w.row[y],l[p+y]=w.col[y];let S=B+w.row[y];w.hidden[y]||(u[S]=u[S]+E[y])}if(x+=w.rows,b<E.length){for(let y=p+b;y<s.length;y++)r[y]>=0&&(o=Math.min(o,r[y]));s=s.slice(0,p+b),r=r.slice(0,p+b);break}p+=E.length+1}let h=o<1/0?()=>!1:E=>E===s.length-1,d=ei(r),m=t.map(E=>E.end>o?null:Li(e,E,s,r,c,l,C,h,L,d));return o<1/0?{rows:x,places:m,lines:u,stop:o}:{rows:x,places:m,lines:u}}
function Xh(e,C,t=[],L={},n=!1){return T7(e,CC(e,C,L,n),C,t,L)}
function Kh(e,C,t=[],L={},n=!1){return T7(e,zn(e,C,L,n),C,t,L)}
function Qh(e,C,t=[],L={},n=!1){return T7(e,iC(e,C,L,n),C,t,L)}
function Zh(e,C,t=[],L=C-2,n={}){return T7(e,Zn(e,C,L,n),C-2,t,n,()=>!1)}
function T7(e,C,t,L,n,i=s=>C?.end[s]===!0){if(!C)return null;let s=C.text.join(""),{stop:r}=C,o=r<1/0?()=>!1:i,c=ei(C.source),l=L.map(u=>u.end>r?null:Li(e,u,s,C.source,C.row,C.col,t,o,n,c));return r<1/0?{rows:C.rows,places:l,lines:C.lines(),stop:r}:{rows:C.rows,places:l,lines:C.lines()}}
function ei(e){let C=0;for(let n of e)n>=C&&(C=n+1);let t=new Int32Array(C).fill(-1),L=new Int32Array(C).fill(-1);for(let n=0;n<e.length;n++){let i=e[n];i<0||(t[i]<0&&(t[i]=n),L[i]=n)}return{first:t,last:L}}
function Li(e,C,t,L,n,i,s,r,o,c){let l=h=>L[h]>=C.start&&L[h]<C.end,u=-1,x=-1;for(let h=Math.max(0,C.start);h<Math.min(C.end,c.first.length);h++){let d=c.first[h];d<0||((u<0||d<u)&&(u=d),c.last[h]>x&&(x=c.last[h]))}if(u<0)return null;for(let h=u;h<=x;h++)if(!l(h)||n[h]!==n[u])return null;let p=Math.max(0,u2(t.slice(u,x+1),o.emojiSequences===!0));if(C.width!==void 0&&C.width!==p){let h=e.slice(L[x]+1,C.end);if(!r(x)||C.width<p||!/^\s*$/.test(h))return null;p=C.width}return i[u]+p>s?null:{row:n[u],col:i[u],columns:p}}
var cC=/[A-Za-z_:][-A-Za-z0-9_.:]*/y;
var lC=/[ \t\r\n]*/y;
var j5=class extends Error{};
function ni(e){let C=0,t=0,L=l=>{throw new j5(`XML: ${l} at ${C}`)},n=()=>{lC.lastIndex=C,lC.exec(e),C=lC.lastIndex},i=()=>{cC.lastIndex=C;let l=cC.exec(e);return l||L("name expected"),C=cC.lastIndex,l[0]},s=l=>{let u=e.indexOf(l,C);u<0&&L(`unclosed ${l}`),C=u+l.length},r=()=>{if(e.startsWith("<!--",C))s("-->");else if(e.startsWith("<?",C))s("?>");else if(e.startsWith("<![CDATA[",C))s("]]>");else if(e.startsWith("<!",C))s(">");else return!1;return!0},o=()=>{++t>2e5&&L("too many elements"),C++;let l=i(),u=Object.create(null);for(;;){n();let x=e[C];if(x==="/"&&e[C+1]===">")return C+=2,{el:{name:l,attrs:u,children:[]},closed:!0};if(x===">")return C++,{el:{name:l,attrs:u,children:[]},closed:!1};x===void 0&&L("unclosed tag");let p=i();n(),e[C]!=="="&&L("= expected"),C++,n();let h=e[C];h!=='"'&&h!=="'"&&L("quote expected");let d=e.indexOf(h,C+1);d<0&&L("unclosed attribute"),u[p]=Jh(e.slice(C+1,d)),C=d+1}},c=()=>{let l=o();if(l.closed)return l.el;let u=[l.el];for(;;){let x=e.indexOf("<",C),p=u[u.length-1];if(x<0&&L(`unclosed <${p.name}>`),C=x,r())continue;if(e[C+1]==="/"){C+=2;let d=i();if(d!==p.name&&L(`</${d}> closes <${p.name}>`),n(),e[C]!==">"&&L("> expected"),C++,u.pop(),u.length===0)return p;continue}let h=o();p.children.push(h.el),!h.closed&&(u.length>=2e4&&L("nested too deep"),u.push(h.el))}};for(;;){if(n(),C>=e.length&&L("no root element"),e[C]!=="<"&&L("< expected"),r())continue;return c()}}
function Jh(e){return e.includes("&")?e.replace(/&(#x[0-9A-Fa-f]{1,6}|#[0-9]{1,7}|[A-Za-z]+);/g,(C,t)=>{if(t[0]==="#"){let L=t[1]==="x"?parseInt(t.slice(2),16):parseInt(t.slice(1),10);return L>0&&L<=1114111?String.fromCodePoint(L):C}return Yh[t]??C}):e}
var l2=class extends Error{};
var ed={fill:O7,fillOpacity:1,fillRule:"nonzero",stroke:null,strokeOpacity:1,strokeWidth:1,cap:"butt",join:"miter",miterLimit:4,dash:void 0,dashOffset:0,opacity:1,color:O7,clip:void 0};
var Ld=new Set(["defs","clipPath","linearGradient","radialGradient","pattern","symbol","marker","title","desc","metadata","style","script"]);
var nd=new Set(["text","image","foreignObject","mask","svg","video","iframe"]);
function pC(e,C){let t=ni(e);if(t.name!=="svg")throw new l2("not an SVG document");let L=id(t),n=new Map,i=D=>{let k=D.attrs.id;k!==void 0&&!n.has(k)&&n.set(k,D);for(let F of D.children)i(F)};i(t);let s=C.emPerUnit,r=C.baseline==="origin"?0:L.y+L.height,o=[s,0,0,s,-L.x*s,-r*s],c=[],l=[],u=new Map,x=new Map,p=0,h=D=>{if(D.length>oi)throw new l2(`picture too complex (a path of ${D.length} characters)`);let k=x.get(D);if(k===void 0&&(k=ai(D),x.set(D,k)),p+=k,p>xC)throw new l2(`picture too complex (more than ${xC} path coordinates)`)},d=D=>{if(c.length>=ri)throw new l2("picture too complex");h(D.d),c.push(D)},m=(D,k,F)=>{if(D===null||!(k>0))return null;if("ref"in D){let N=od(D.ref,n,F.color);return N?{color:N.color,opacity:k*N.opacity}:null}return{color:D,opacity:k}},E=(D,k,F,N,U=!0)=>{if(D.trim()==="")return;let q=r3(o,k),K=U?m(F.fill,F.fillOpacity*F.opacity,F):null;K&&d({type:"fill",d:D,transform:q,rule:F.fillRule,paint:K,...N?{glyph:!0}:{},...F.clip!==void 0?{clip:F.clip}:{}});let P=m(F.stroke,F.strokeOpacity*F.opacity,F);if(P&&F.strokeWidth>0){let j={width:F.strokeWidth,cap:F.cap,join:F.join,miterLimit:F.miterLimit};F.dash&&(j.dash=F.dash,j.dashOffset=F.dashOffset),d({type:"stroke",d:D,transform:q,style:j,paint:P,...F.clip!==void 0?{clip:F.clip}:{}})}},w=(D,k,F)=>{let N=n.get(D);if(!N||N.name!=="clipPath")return F;let U=`${D}
${k.join(",")}
${F??""}`,q=u.get(U);if(q!==void 0)return q;let K=r3(k,uC(N.attrs.transform)),P=[],j=(G,J,C1)=>{if(C1>N7)throw new l2("clip path nested too deep");let e1=r3(J,uC(G.attrs.transform)),l1=(o2(G,"clip-rule")??"nonzero")==="evenodd"?"evenodd":"nonzero";if(G.name==="use"){let h1=n.get(P7(G)??"");h1&&j(h1,r3(e1,ii(G)),C1+1);return}let p1=si(G);if(p1!==void 0){h(p1),P.push({d:p1,transform:r3(o,e1),rule:l1});return}if(G.name==="g")for(let h1 of G.children)j(h1,e1,C1+1)};for(let G of N.children)j(G,K,0);l.push({paths:P,...F!==void 0?{within:F}:{}});let W=l.length-1;return u.set(U,W),W},b=[{el:t,ctm:I7,inherited:{...ed},root:!0,glyph:!1,uses:0}],B=0;for(;b.length>0;){let{el:D,ctm:k,inherited:F,root:N,glyph:U,uses:q}=b.pop();if(++B>Cd)throw new l2("picture too complex");if(Ld.has(D.name))continue;if(nd.has(D.name)&&!N)throw new l2(`<${D.name}> is not drawn`);if(o2(D,"display")==="none")continue;let K=D.name==="svg"?k:r3(k,uC(D.attrs.transform)),P=rd(D,F),j=hC(o2(D,"clip-path"));if(j!==void 0&&(P.clip=w(j,K,F.clip)),o2(D,"mask")!==void 0&&o2(D,"mask")!=="none")throw new l2("masks are not drawn");let W=o2(D,"visibility")==="hidden";switch(D.name){case"svg":case"g":case"a":case"switch":for(let G=D.children.length-1;G>=0;G--)b.push({el:D.children[G],ctm:K,inherited:P,root:!1,glyph:U,uses:q});continue;case"use":{let G=P7(D),J=G===void 0?void 0:n.get(G);if(!J||J===D)continue;if(q>=N7||sd(D,n)>N7)throw new l2("use nested too deep");let C1=J.name==="path"&&/^g\d*-/.test(G??"");b.push({el:J.name==="symbol"?{...J,name:"g"}:J,ctm:r3(K,ii(D)),inherited:P,root:!1,glyph:U||C1,uses:q+1});continue}default:{let G=si(D);if(G===void 0||W)continue;E(G,K,P,U,D.name!=="line")}}}let y=(r-L.y)*s,S=(L.y+L.height-r)*s;return{width:L.width*s,height:Math.max(0,y),depth:Math.max(0,S),ops:c,clips:l}}
function ai(e){let C=0,t=!1,L=!1,n=!1;for(let i=0;i<e.length;i++){let s=e.charCodeAt(i);s>=48&&s<=57?t||(C++,t=!0,L=!1,n=!1):s===46?((!t||L||n)&&(C++,t=!0,n=!1),L=!0):(s===101||s===69)&&t&&!n?n=!0:(s===43||s===45)&&t&&n&&(e.charCodeAt(i-1)===101||e.charCodeAt(i-1)===69)||(t=!1)}return C}
function id(e){let C=(e.attrs.viewBox??"").trim().split(/[\s,]+/).map(Number);if(C.length===4&&C.every(Number.isFinite)&&C[2]>0&&C[3]>0){let[n,i,s,r]=C;return{x:n,y:i,width:s,height:r}}let t=K4(e.attrs.width),L=K4(e.attrs.height);if(t&&L&&t>0&&L>0)return{x:0,y:0,width:t,height:L};throw new l2("the picture is empty")}
function K4(e){if(e===void 0)return;let C=parseFloat(e);return Number.isFinite(C)?C:void 0}
function P7(e){let C=e.attrs["xlink:href"]??e.attrs.href;return C?.startsWith("#")?C.slice(1):void 0}
function sd(e,C){let t=0,L=e,n=new Set;for(;L&&L.name==="use";){if(n.has(L))return 1/0;n.add(L),t++;let i=P7(L);L=i===void 0?void 0:C.get(i)}return t}
function ii(e){return[1,0,0,1,K4(e.attrs.x)??0,K4(e.attrs.y)??0]}
function o2(e,C){let t=e.attrs.style;if(t!==void 0)for(let n of t.split(";")){let i=n.indexOf(":");if(i>0&&n.slice(0,i).trim()===C)return n.slice(i+1).trim()}let L=e.attrs[C];return L===void 0?void 0:L.trim()}
function rd(e,C){let t={...C},L=o2(e,"color");L!==void 0&&L!=="inherit"&&(t.color=_7(L,C.color)??C.color);let n=(l,u)=>{if(l===void 0||l==="inherit")return u;if(l==="none")return null;let x=hC(l);return x!==void 0?{ref:x}:l==="currentColor"?t.color:_7(l,t.color)??u};t.fill=n(o2(e,"fill"),C.fill),t.stroke=n(o2(e,"stroke"),C.stroke);let i=(l,u)=>{let x=o2(e,l);if(x===void 0||x==="inherit")return u;let p=x.endsWith("%")?parseFloat(x)/100:parseFloat(x);return Number.isFinite(p)?p:u};t.fillOpacity=q5(i("fill-opacity",C.fillOpacity)),t.strokeOpacity=q5(i("stroke-opacity",C.strokeOpacity)),t.opacity=C.opacity*q5(i("opacity",1)),t.strokeWidth=Math.max(0,i("stroke-width",C.strokeWidth)),t.miterLimit=Math.max(1,i("stroke-miterlimit",C.miterLimit)),t.dashOffset=i("stroke-dashoffset",C.dashOffset);let s=o2(e,"fill-rule");(s==="evenodd"||s==="nonzero")&&(t.fillRule=s);let r=o2(e,"stroke-linecap");(r==="butt"||r==="round"||r==="square")&&(t.cap=r);let o=o2(e,"stroke-linejoin");o==="miter"||o==="round"||o==="bevel"?t.join=o:(o==="miter-clip"||o==="arcs")&&(t.join="miter");let c=o2(e,"stroke-dasharray");if(c!==void 0&&c!=="inherit"){let l=c==="none"?[]:c.split(/[\s,]+/).filter(Boolean).map(Number),u=l.length>0&&l.every(x=>Number.isFinite(x)&&x>=0)&&l.some(x=>x>0);t.dash=u?l.length%2===1?[...l,...l]:l:void 0}return t}
function hC(e){let C=e===void 0?null:/^url\(\s*['"]?#([^'")\s]+)['"]?\s*\)/.exec(e);return C?C[1]:void 0}
function od(e,C,t){let L=C.get(e);if(!L)return null;if(L.name==="linearGradient"||L.name==="radialGradient"){let n=ci(L,C,0);if(n.length===0)return null;if(n.length===1)return n[0].paint;let i=0,s=0,r=0,o=0,c=0;for(let l=0;l+1<n.length;l++){let u=Math.max(0,n[l+1].offset-n[l].offset);for(let x of[n[l],n[l+1]])s+=x.paint.color.r*u,r+=x.paint.color.g*u,o+=x.paint.color.b*u,c+=x.paint.opacity*u;i+=2*u}return i>0?{color:{r:Math.round(s/i),g:Math.round(r/i),b:Math.round(o/i)},opacity:c/i}:n[0].paint}if(L.name==="pattern"){let n=li(L,t);return n?{color:n,opacity:td}:null}return null}
function ci(e,C,t){let L=e.children.filter(i=>i.name==="stop").map(i=>{let s=o2(i,"offset")??"0",r=q5(s.endsWith("%")?parseFloat(s)/100:parseFloat(s)||0),o=_7(o2(i,"stop-color")??"black",O7)??O7,c=q5(parseFloat(o2(i,"stop-opacity")??"1"));return{offset:r,paint:{color:o,opacity:Number.isFinite(c)?c:1}}});if(L.length>0||t>N7)return L;let n=C.get(P7(e)??"");return n?ci(n,C,t+1):[]}
function li(e,C){for(let t of e.children){for(let n of["fill","stroke"]){let i=o2(t,n);if(i&&i!=="none"&&hC(i)===void 0){let s=i==="currentColor"?C:_7(i,C);if(s)return s}}let L=li(t,C);if(L)return L}}
function si(e){let C=e.attrs,t=L=>K4(L)??0;switch(e.name){case"path":return C.d??"";case"rect":{let L=t(C.width),n=t(C.height);if(!(L>0&&n>0))return"";let i=t(C.x),s=t(C.y),r=K4(C.rx),o=K4(C.ry);return r===void 0&&(r=o),o===void 0&&(o=r),r=Math.min(Math.max(0,r??0),L/2),o=Math.min(Math.max(0,o??0),n/2),r>0&&o>0?`M${i+r} ${s}H${i+L-r}A${r} ${o} 0 0 1 ${i+L} ${s+o}V${s+n-o}A${r} ${o} 0 0 1 ${i+L-r} ${s+n}H${i+r}A${r} ${o} 0 0 1 ${i} ${s+n-o}V${s+o}A${r} ${o} 0 0 1 ${i+r} ${s}Z`:`M${i} ${s}H${i+L}V${s+n}H${i}Z`}case"circle":case"ellipse":{let L=t(C.cx),n=t(C.cy),i=e.name==="circle"?t(C.r):t(C.rx),s=e.name==="circle"?t(C.r):t(C.ry);return i>0&&s>0?`M${L+i} ${n}A${i} ${s} 0 1 1 ${L-i} ${n}A${i} ${s} 0 1 1 ${L+i} ${n}Z`:""}case"line":return`M${t(C.x1)} ${t(C.y1)}L${t(C.x2)} ${t(C.y2)}`;case"polyline":case"polygon":{let L=(C.points??"").trim().split(/[\s,]+/).filter(Boolean).map(Number);if(L.length<4||L.some(i=>!Number.isFinite(i)))return"";let n=`M${L[0]} ${L[1]}`;for(let i=2;i+1<L.length;i+=2)n+=`L${L[i]} ${L[i+1]}`;return e.name==="polygon"?n+"Z":n}default:return}}
function r3(e,C){return[e[0]*C[0]+e[2]*C[1],e[1]*C[0]+e[3]*C[1],e[0]*C[2]+e[2]*C[3],e[1]*C[2]+e[3]*C[3],e[0]*C[4]+e[2]*C[5]+e[4],e[1]*C[4]+e[3]*C[5]+e[5]]}
function uC(e){if(e===void 0||e.trim()==="")return I7;let C=I7,t=/\s*(matrix|translate|scale|rotate|skewX|skewY)\s*\(([^)]*)\)\s*,?/gy,L=0;for(let n=t.exec(e);n;n=t.exec(e)){L=t.lastIndex;let i=n[2].trim().split(/[\s,]+/).filter(Boolean).map(Number);if(i.some(s=>!Number.isFinite(s)))throw new l2(`unreadable transform ${n[0]}`);C=r3(C,ad(n[1],i))}if(e.slice(L).trim()!=="")throw new l2(`unreadable transform ${e}`);return C}
function ad(e,C){let[t=0,L,n]=C;switch(e){case"matrix":if(C.length!==6)throw new l2("matrix() takes six numbers");return C;case"translate":return[1,0,0,1,t,L??0];case"scale":return[t,0,0,L??t,0,0];case"rotate":{let i=t*Math.PI/180,s=Math.cos(i),r=Math.sin(i),o=[s,r,-r,s,0,0];return L===void 0||n===void 0?o:r3(r3([1,0,0,1,L,n],o),[1,0,0,1,-L,-n])}case"skewX":return[1,0,Math.tan(t*Math.PI/180),1,0,0];case"skewY":return[1,Math.tan(t*Math.PI/180),0,1,0,0];default:return I7}}
function _7(e,C){let t=e.trim().toLowerCase();if(t==="currentcolor")return C;let L=/^#([0-9a-f]{3}|[0-9a-f]{6})$/.exec(t);if(L){let i=L[1],s=i.length===3?[...i].map(r=>r+r).join(""):i;return{r:parseInt(s.slice(0,2),16),g:parseInt(s.slice(2,4),16),b:parseInt(s.slice(4,6),16)}}let n=/^rgba?\(([^)]*)\)$/.exec(t);if(n){let i=n[1].split(/[\s,/]+/).filter(Boolean);if(i.length<3)return;let s=u=>u.endsWith("%")?parseFloat(u)/100*255:parseFloat(u),[r,o,c]=i.slice(0,3).map(s);if(![r,o,c].every(Number.isFinite))return;let l=u=>Math.min(255,Math.max(0,Math.round(u)));return{r:l(r),g:l(o),b:l(c)}}return cd[t]}
var q5=e=>Number.isFinite(e)?Math.min(1,Math.max(0,e)):1;
function gi(e){let C=e.trim().split(/\s+/,1)[0].toLowerCase();if(C==="latex"||C==="tex")return"latex";if(C==="tikz")return"tikz"}
function Mi(e,C){return C!=="latex"||Ai(e)?!0:/\\begin\{(?:tikzpicture|tikzcd|circuitikz|axis|semilogxaxis|semilogyaxis|loglogaxis|polaraxis|ternaryaxis|picture|forest|chemfig)\}|\\(?:tikz|chemfig|schemestart|chemname|ctikzset|draw|SI|qty|si|unit|num)\b/.test(e)}
function Ai(e){return/^(?:\s|%[^\n]*\n)*\\documentclass\b/.test(e)||/\\begin\{document\}/.test(e)}
var bi=["\\documentclass[dvisvgm,border=1pt]{standalone}",`\\makeatletter${Ei}\\makeatother`,"\\usepackage{amsmath,amssymb}","\\usepackage{tikz}",`\\usetikzlibrary{${ld}}`,"\\usepackage{pgfplots}","\\pgfplotsset{compat=1.18}","\\usepgfplotslibrary{fillbetween}","\\usepackage{chemfig}","\\usepackage{circuitikz}","\\usepackage{tikz-cd}","\\usepackage{siunitx}"];
var ui=/^[ \t]*\\(?:usepackage|RequirePackage|usetikzlibrary|usepgfplotslibrary|usepgflibrary|usegdlibrary)\b[^\n]*$/gm;
function Di(e,C){let t=e.replace(/^\s*\n/,"").replace(/\s+$/,"").replace(/shader\s*=\s*interp\b/g,"shader=flat");if(C==="latex"&&Ai(t)){let o=/^(?:\s|%[^\n]*\n)*\\documentclass\b/.test(t),c=o?t:`\\documentclass[dvisvgm,border=1pt]{standalone}
${t}`,l=`\\def\\pgfsysdriver{pgfsys-dvisvgm.def}\\PassOptionsToPackage{dvisvgm}{graphicx}\\makeatletter\\AddToHook{class/standalone/after}{${Ei}}\\makeatother`,u=c.replace(/\\documentclass\s*(?:\[([^\]]*)\])?\s*\{/,(p,h)=>h===void 0?"\\documentclass[dvisvgm]{":/(?:^|,)\s*dvisvgm\s*(?:,|$)/.test(h)?`\\documentclass[${h}]{`:`\\documentclass[${h},dvisvgm]{`);return{text:`${l}
${u.replace(/\\begin\{document\}/,"\\begin{document}\\pagestyle{empty}\\thispagestyle{empty}")}
`,offset:o?1:2,baseline:"bottom",fontSize:ud(c)}}let L=[...t.matchAll(ui)].map(o=>o[0].trim()),n=L.length>0?t.replace(ui,""):t;C==="tikz"&&!/\\begin\{tikzpicture\}|\\tikz\b/.test(n)&&(n=`\\begin{tikzpicture}
${n}
\\end{tikzpicture}`);let i=[...bi,yi,...L,"\\begin{document}"],s=C==="tikz"&&n!==t&&n.startsWith(`\\begin{tikzpicture}
`)&&!t.startsWith("\\begin{tikzpicture}"),r=i.length+(s?1:0);return{text:`${i.join(`
`)}
${n}
\\end{document}
`,offset:r,baseline:"bottom",fontSize:10,format:!0}}
var dC=`${[...bi,yi,"\\begin{document}","\\end{document}"].join(`
`)}
`;
function ki(e){let C=2166136261;for(let t of`3
${e}
${dC}`)C=Math.imul(C^t.charCodeAt(0),16777619);return`kittex-${(C>>>0).toString(16).padStart(8,"0")}`}
function Bi(e){return["latex","-ini","-no-shell-escape","-interaction=nonstopmode","-halt-on-error","-no-mktex=tex","-no-mktex=tfm","-no-mktex=pk",`-jobname=${e}`,"&latex","mylatexformat.ltx",`${e}.tex`]}
function wi(e){return e===void 0?[...U5]:[...U5.slice(0,-2),`-fmt=${e}`,...U5.slice(-2)]}
var pi=/^\\begin\{(equation|align|gather|multline|flalign|alignat|eqnarray)\*?\}/;
function Fi(e,C){let t=e.trim();if(!C){let i=[...xi.slice(0,3),"\\usepackage[active]{preview}","\\begin{document}"];return{text:`${i.join(`
`)}
\\begin{preview}$${t}$\\end{preview}
\\end{document}
`,offset:i.length,baseline:"origin",fontSize:10}}let L=[...xi,"\\begin{document}"],n=pi.test(t)?t:`\\[
${t}
\\]`;return{text:`${L.join(`
`)}
${n}
\\end{document}
`,offset:L.length+(pi.test(t)?0:1),baseline:"bottom",fontSize:10}}
function ud(e){let C=/\\documentclass\s*\[([^\]]*)\]/.exec(e)?.[1]??"",t=/(?:^|,)\s*(\d{1,2}(?:\.\d+)?)pt\s*(?:,|$)/.exec(C)?.[1],L=t===void 0?10:Number(t);return L>=5&&L<=25?L:10}
function fC(e){return 72.27/72/e.fontSize}
var pd=new RegExp(String.raw`\\(?:${xd.map(e=>e.replace(/[*]/g,"\\*")).join("|")})(?![A-Za-z@])`);
var hd=new Set(["shellesc","minted","pythontex","sagetex","bashful","gnuplottex","asymptote","svg","epstopdf","auto-pst-pdf","pst-pdf","luacode","luatextra","luapackageloader","fontspec","filecontents","catchfile","verbatim","fancyvrb","listings","import","standalone","datatool","csvsimple","readarray","pgfplotstable","xstring","docmute","subfiles","embedfile","attachfile","attachfile2","write18","pstricks","pst-node"]);
var dd=/\\(?:usepackage|RequirePackage|documentclass|LoadClass|usetikzlibrary|usepgfplotslibrary|usepgflibrary)\s*(?:\[[^\]]*\]\s*)?(?:\{([^}]*)\}|([^\s{\\][^\s\\]*))/g;
var fd=/\b(?:table|file|graphics)\s*(?:\[[^\]]*\]\s*)?\{([^}\\\n]*)\}/g;
var md=/\b(?:table|file|graphics)\s*(?:\[[^\]]*\]\s*)?\{\s*\\[A-Za-z]/;
function vi(e){if(e.length>24e3)return"source longer than 24000 characters";if(e.includes("^^"))return"uses ^^ character notation";if(/[\u0000-\u0008\u000b\u000e-\u001f\u007f]/.test(e))return"holds control characters";let C=pd.exec(e);if(C)return`uses ${C[0]}`;let t=/\\[A-Za-z]*@[A-Za-z@]*/.exec(e);if(t)return`uses ${t[0]}`;if(/\\begin\{(?:luacode\*?|filecontents\*?|verbatimwrite|VerbatimOut|lstlisting|minted|pycode|sagesilent|sageblock|bash|asy|asydef)\}/.test(e))return"uses an environment that runs code or writes files";for(let n of e.matchAll(dd)){let i=(n[1]??n[2]??"").split(",");for(let s of i){let r=s.trim();if(hi(r))return`reads ${r}`;if(/^\\(?:usepackage|RequirePackage)/.test(n[0])&&hd.has(r))return`uses the ${r} package`}}for(let n of e.matchAll(fd)){let i=n[1].trim();if(i!==""&&hi(i))return`reads ${i}`}if(md.test(e))return"reads a plot file named by a macro";if(/\bgnuplot\b|\\addplot[^;]*\bshell\b/.test(e))return"runs gnuplot or a shell";let L=/(?:^|[\s{=,(])((?:~|\$HOME|\$\{HOME\})\/|\.\.[/\\]|\/+(?:home|root|etc|Users|private|var|tmp|proc|sys|dev|run|mnt|media|srv|opt|usr|Library|Volumes|System|boot|snap|nix)\b)/.exec(e);if(L)return`names a path outside the picture (${L[1]})`}
function hi(e){return/^[/\\~]|^[A-Za-z]:|\.\.|^\.|\$|\||[`"'<>]|^\s*-/.test(e)||/[/\\]\./.test(e)}
var Si=64*1024*1024;
function Ti(e){return["bwrap",...Ni(e,void 0),"true"]}
function Ni(e,C,t=[]){let L=["--ro-bind","/","/","--dev","/dev","--proc","/proc"];for(let n of e)L.push("--tmpfs",n);for(let n of t)L.push("--ro-bind",n,n);return C!==void 0&&L.push("--bind",C,C,"--chdir",C),L.push("--unshare-all","--die-with-parent","--new-session"),L}
function Oi(e,C,t,L=[]){let n=[...e];return t.bwrap&&(n=["bwrap",...Ni(t.bwrap.hide,C,L),...n]),t.prlimit&&(n=["prlimit",`--fsize=${Si}`,`--cpu=${Ri}`,...n]),n}
var U5=["latex","-no-shell-escape","-interaction=nonstopmode","-halt-on-error","-no-mktex=tex","-no-mktex=tfm","-no-mktex=pk",`-jobname=${V5}`,`${V5}.tex`];
function Ii(e){return["dvisvgm","--no-fonts","--exact-bbox","--no-specials=ps,pdf,html",`--libgs=${e}/no-ghostscript`,"--no-mktexmf","--cache=none",`--tmpdir=${e}`,"--page=1","--stdout","--verbosity=1",`${V5}.dvi`]}
function Pi(e){return{shell_escape:"f",openin_any:"p",openout_any:"p",TEXMFOUTPUT:e,HOME:e,MKTEXTEX:"0",MKTEXTFM:"0",MKTEXPK:"0",MKTEXMF:"0",MKTEXFMT:"0",max_print_line:"1000",error_line:"254",half_error_line:"238"}}
function _i(e){return`${(e&&e.startsWith("/")?e:"/tmp").replace(/\/+$/,"")}/kittex-tex.XXXXXXXXXX`}
function zi(e){return/^\/(?:[^\n/]+\/)*kittex-tex\.[A-Za-z0-9]{10}$/.test(e)&&!e.includes("/../")&&!e.includes("/./")}
function Wi(e,C=0){let t=e.split(/\r?\n/),L=t.findIndex(s=>s.startsWith("! "));if(L<0)return/No pages of output/.test(e)?"the picture is empty":/Emergency stop|Fatal error/.test(e)?"TeX stopped":"TeX failed";let n=t[L].slice(2).trim().replace(/\.$/,"");n=n.replace(/^(?:LaTeX|Package \S+|Class \S+) Error:\s*/,"");let i;for(let s of t.slice(L+1,L+12)){let r=/^l\.(\d+) (.*)$/.exec(s);if(r){let o=Number(r[1])-C;if(o>=1&&(i=o),/^Undefined control sequence$/.test(n)){let c=/(\\[A-Za-z@]+|\\.)\s*$/.exec(r[2])?.[1];c&&(n+=` ${c}`)}break}}return i===void 0?n:`${n} (line ${i})`}
function W7(e){return z7(e).l>.5?{r:24,g:24,b:24}:{r:255,g:255,b:255}}
function $7(e,C,t){if(e.r<=2&&e.g<=2&&e.b<=2)return C.ink;if(e.r>=253&&e.g>=253&&e.b>=253)return"erase";let L=z7(e),n=z7(C.ink).l,i=z7(C.background).l,s=L.l;if(i<.5){let r=n+L.l*(i-n),o=Math.hypot(L.a,L.b),c=gC(o/.12)*gC(1-Math.abs(L.l-.55)/.4);s=r+(L.l-r)*c}if(s===L.l&&!(t&&Math.abs(s-i)<.3))return{...e};if(t&&Math.abs(s-i)<.3){let r=n>=i?1:-1;s=gC(i+r*.3)}return Md(s,L.a,L.b)}
var mC=e=>{let C=e/255;return C<=.04045?C/12.92:((C+.055)/1.055)**2.4};
var gd=e=>(e<=.0031308?12.92*e:1.055*e**(1/2.4)-.055)*255;
function z7(e){let C=mC(e.r),t=mC(e.g),L=mC(e.b),n=Math.cbrt(.4122214708*C+.5363325363*t+.0514459929*L),i=Math.cbrt(.2119034982*C+.6806995451*t+.1073969566*L),s=Math.cbrt(.0883024619*C+.2817188376*t+.6299787005*L);return{l:.2104542553*n+.793617785*i-.0040720468*s,a:1.9779984951*n-2.428592205*i+.4505937099*s,b:.0259040371*n+.7827717662*i-.808675766*s}}
function $i(e,C,t){let L=(e+.3963377774*C+.2158037573*t)**3,n=(e-.1055613458*C-.0638541728*t)**3,i=(e-.0894841775*C-1.291485548*t)**3;return[4.0767416621*L-3.3077115913*n+.2309699292*i,-1.2684380046*L+2.6097574011*n-.3413193965*i,-.0041960863*L-.7034186147*n+1.707614701*i]}
function Md(e,C,t){let L=c=>$i(e,C*c,t*c).every(l=>l>=-1e-6&&l<=1.000001),n=1;if(!L(1)){let c=0,l=1;for(let u=0;u<20;u++){let x=(c+l)/2;L(x)?c=x:l=x}n=c}let[i,s,r]=$i(e,C*n,t*n),o=c=>Math.min(255,Math.max(0,Math.round(gd(Math.min(1,Math.max(0,c))))));return{r:o(i),g:o(s),b:o(r)}}
var gC=e=>Math.min(1,Math.max(0,e));
function Ad(e,C){return pC(e,{baseline:C.baseline,emPerUnit:fC(C)})}
var S6=class{width;height;stride;acc;constructor(C,t){this.width=C,this.height=t,this.stride=C+2,this.acc=new Float32Array(this.stride*t)}fill(C,t){let L=C.length,n=C[L-2],i=C[L-1];for(let s=0;s<L;s+=2){let r=C[s],o=C[s+1];this.line(n,i,r,o,t),n=r,i=o}}line(C,t,L,n,i){if(t===n)return;let s=this.width;if(C>=0&&L>=0&&C<=s&&L<=s){this.edge(C,t,L,n,i);return}let r=[0,1];for(let o of[0,s])(C-o)*(L-o)<0&&r.push((o-C)/(L-C));r.sort((o,c)=>o-c);for(let o=1;o<r.length;o++){let c=r[o-1],l=r[o],u=C+(L-C)*c,x=C+(L-C)*l,p=t+(n-t)*c,h=t+(n-t)*l;this.edge(Math.min(s,Math.max(0,u)),p,Math.min(s,Math.max(0,x)),h,i)}}edge(C,t,L,n,i){if(t===n)return;let s=i,r=C,o=t,c=L,l=n;o>l&&(s=-i,r=L,o=n,c=C,l=t);let u=this.height;if(l<=0||o>=u)return;let x=this.acc,p=this.stride,h=(c-r)/(l-o),d=r;o<0&&(d-=o*h);let m=Math.max(0,Math.floor(o)),E=Math.min(u,Math.ceil(l));for(let w=m;w<E;w++){let b=w*p,B=Math.min(w+1,l)-Math.max(w,o),y=d+h*B,S=B*s,D=d<y?d:y,k=d<y?y:d,F=Math.floor(D),N=F,U=Math.ceil(k),q=U;if(q<=N+1){let K=.5*(d+y)-F;x[b+N]+=S-S*K,x[b+N+1]+=S*K}else{let K=1/(k-D),P=D-F,j=.5*K*(1-P)*(1-P),W=k-U+1,G=.5*K*W*W;if(x[b+N]+=S*j,q===N+2)x[b+N+1]+=S*(1-j-G);else{let J=K*(1.5-P);x[b+N+1]+=S*(J-j);for(let e1=N+2;e1<q-1;e1++)x[b+e1]+=S*K;let C1=J+(q-N-3)*K;x[b+q-1]+=S*(1-C1-G)}x[b+q]+=S*G}d=y}}toAlphaEvenOdd(){let{width:C,height:t,stride:L,acc:n}=this,i=new Uint8Array(C*t);for(let s=0;s<t;s++){let r=0,o=s*L,c=s*C;for(let l=0;l<C;l++){r+=n[o+l];let u=(r<0?-r:r)%2;u>1&&(u=2-u),i[c+l]=u*255+.5|0}}return i}toAlpha(C){let{width:t,height:L,stride:n,acc:i}=this,s=new Uint8Array(t*L);for(let r=0;r<L;r++){let o=0,c=r*n,l=r*t;for(let u=0;u<t;u++){o+=i[c+u];let x=o<0?-o:o,p=x>=1?255:x*255+.5|0;s[l+u]=C?C[p]:p}}return s}};
var X2=Uint8Array;
var F2=Uint16Array;
var DC=Int32Array;
var yC=new X2([0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,0,0,0]);
var kC=new X2([0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13,0,0]);
var Gi=new X2([16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15]);
var Ui=function(e,C){for(var t=new F2(31),L=0;L<31;++L)t[L]=C+=1<<e[L-1];for(var n=new DC(t[30]),L=1;L<30;++L)for(var i=t[L];i<t[L+1];++i)n[i]=i-t[L]<<5|L;return{b:t,r:n}};
export{Ui,yC,kC,F2,X2,Gi,DC,S6,W7,$7,dC,U5,l2,j5,Ci,Ti,Oi,Di,gi,Mi,Ii,Bi,ki,zi,_i,wi,Kh,Xh,Vh,Qh,Zh,Fi,Pi,Wi,Ad,vi};
