import{q2,w2,Fi,E3,Ei,V4,N7,q5,Hh,jh,H5,uC,xC,lC,oC,bi,qh,K4,G7,qi,cd,gC,y6,j7,xd}from'./p21.js';export*from'./p21.js';
var rC=function(e,C){for(var t=[],L=0;L<e.length;++L)e[L]&&t.push({s:L,f:e[L]});var n=t.length,i=t.slice();if(!n)return{t:Si,l:0};if(n==1){var s=new q2(t[0].s+1);return s[t[0].s]=1,{t:s,l:1}}t.sort(function(D,S){return D.f-S.f}),t.push({s:-1,f:25001});var r=t[0],o=t[1],c=0,l=1,u=2;for(t[0]={s:-1,f:r.f+o.f,l:r,r:o};l!=n-1;)r=t[t[c].f<t[u].f?c++:u++],o=t[c!=l&&t[c].f<t[u].f?c++:u++],t[l++]={s:-1,f:r.f+o.f,l:r,r:o};for(var x=i[0].s,L=1;L<n;++L)i[L].s>x&&(x=i[L].s);var p=new w2(x+1),h=cC(t[l-1],p,0);if(h>C){var L=0,d=0,M=h-C,b=1<<M;for(i.sort(function(S,F){return p[F.s]-p[S.s]||S.f-F.f});L<n;++L){var y=i[L].s;if(p[y]>C)d+=b-(1<<h-p[y]),p[y]=C;else break}for(d>>=M;d>0;){var E=i[L].s;p[E]<C?d-=1<<C-p[E]++-1:++L}for(;L>=0&&d;--L){var w=i[L].s;p[w]==C&&(--p[w],++d)}h=C}return{t:new q2(p),l:h}};
var cC=function(e,C,t){return e.s==-1?Math.max(cC(e.l,C,t+1),cC(e.r,C,t+1)):C[e.s]=t};
var Di=function(e){for(var C=e.length;C&&!e[--C];);for(var t=new w2(++C),L=0,n=e[0],i=1,s=function(o){t[L++]=o},r=1;r<=C;++r)if(e[r]==n&&r!=C)++i;else{if(!n&&i>2){for(;i>138;i-=138)s(32754);i>2&&(s(i>10?i-11<<5|28690:i-3<<5|12305),i=0)}else if(i>3){for(s(n),--i;i>6;i-=6)s(8304);i>2&&(s(i-3<<5|8208),i=0)}for(;i--;)s(n);i=1,n=e[r]}return{c:t.subarray(0,L),n:C}};
var j5=function(e,C){for(var t=0,L=0;L<C.length;++L)t+=e[L]*C[L];return t};
var vi=function(e,C,t){var L=t.length,n=Fi(C+2);e[n]=L&255,e[n+1]=L>>8,e[n+2]=e[n]^255,e[n+3]=e[n+1]^255;for(var i=0;i<L;++i)e[n+i+4]=t[i];return(n+4+L)*8};
var ki=function(e,C,t,L,n,i,s,r,o,c,l){E3(C,l++,t),++n[256];for(var u=rC(n,15),x=u.t,p=u.l,h=rC(i,15),d=h.t,M=h.l,b=Di(x),y=b.c,E=b.n,w=Di(d),D=w.c,S=w.n,F=new w2(19),k=0;k<y.length;++k)++F[y[k]&31];for(var k=0;k<D.length;++k)++F[D[k]&31];for(var v=rC(F,7),I=v.t,V=v.l,H=19;H>4&&!I[Ei[H-1]];--H);var q=c+5<<3,W=j5(n,V4)+j5(i,N7)+s,j=j5(n,x)+j5(i,d)+s+14+3*H+j5(F,I)+2*F[16]+3*F[17]+7*F[18];if(o>=0&&q<=W&&q<=j)return vi(C,l,e.subarray(o,o+c));var z,X,t1,J;if(E3(C,l,1+(j<W)),l+=2,j<W){z=q5(x,p,0),X=x,t1=q5(d,M,0),J=d;var e1=q5(I,V,0);E3(C,l,E-257),E3(C,l+5,S-1),E3(C,l+10,H-4),l+=14;for(var k=0;k<H;++k)E3(C,l+3*k,I[Ei[k]]);l+=3*H;for(var u1=[y,D],d1=0;d1<2;++d1)for(var m1=u1[d1],k=0;k<m1.length;++k){var p1=m1[k]&31;E3(C,l,e1[p1]),l+=I[p1],p1>15&&(E3(C,l,m1[k]>>5&127),l+=m1[k]>>12)}}else z=Hh,X=V4,t1=jh,J=N7;for(var k=0;k<r;++k){var l1=L[k];if(l1>255){var p1=l1>>18&31;H5(C,l,z[p1+257]),l+=X[p1+257],p1>7&&(E3(C,l,l1>>23&31),l+=uC[p1]);var k1=l1&31;H5(C,l,t1[k1]),l+=J[k1],k1>3&&(H5(C,l,l1>>5&8191),l+=xC[k1])}else H5(C,l,z[l1]),l+=X[l1]}return H5(C,l,z[256]),l+X[256]};
var Uh=new lC([65540,131080,131088,131104,262176,1048704,1048832,2114560,2117632]);
var Si=new q2(0);
var Vh=function(e,C,t,L,n,i){var s=i.z||e.length,r=new q2(L+s+5*(1+Math.ceil(s/7e3))+n),o=r.subarray(L,r.length-n),c=i.l,l=(i.r||0)&7;if(C){l&&(o[0]=i.r>>3);for(var u=Uh[C-1],x=u>>13,p=u&8191,h=(1<<t)-1,d=i.p||new w2(32768),M=i.h||new w2(h+1),b=Math.ceil(t/3),y=2*b,E=function(A6){return(e[A6]^e[A6+1]<<b^e[A6+2]<<y)&h},w=new lC(25e3),D=new w2(288),S=new w2(32),F=0,k=0,v=i.i||0,I=0,V=i.w||0,H=0;v+2<s;++v){var q=E(v),W=v&32767,j=M[q];if(d[W]=j,M[q]=W,V<=v){var z=s-v;if((F>7e3||I>24576)&&(z>423||!c)){l=ki(e,o,0,w,D,S,k,I,H,v-H,l),I=F=k=0,H=v;for(var X=0;X<286;++X)D[X]=0;for(var X=0;X<30;++X)S[X]=0}var t1=2,J=0,e1=p,u1=W-j&32767;if(z>2&&q==E(v-u1))for(var d1=Math.min(x,z)-1,m1=Math.min(32767,v),p1=Math.min(258,z);u1<=m1&&--e1&&W!=j;){if(e[v+t1]==e[v+t1-u1]){for(var l1=0;l1<p1&&e[v+l1]==e[v+l1-u1];++l1);if(l1>t1){if(t1=l1,J=u1,l1>d1)break;for(var k1=Math.min(u1,l1-2),y2=0,X=0;X<k1;++X){var f3=v-u1+X&32767,v5=d[f3],t3=f3-v5&32767;t3>y2&&(y2=t3,j=f3)}}}W=j,j=d[W],u1+=W-j&32767}if(J){w[I++]=268435456|oC[t1]<<18|bi[J];var m3=oC[t1]&31,S5=bi[J]&31;k+=uC[m3]+xC[S5],++D[257+m3],++S[S5],V=v+t1,++F}else w[I++]=e[v],++D[e[v]]}}for(v=Math.max(v,V);v<s;++v)w[I++]=e[v],++D[e[v]];l=ki(e,o,c,w,D,S,k,I,H,v-H,l),c||(i.r=l&7|o[l/8|0]<<3,l-=7,i.h=M,i.p=d,i.i=v,i.w=V)}else{for(var v=i.w||0;v<s+c;v+=65535){var M6=v+65535;M6>=s&&(o[l/8|0]=c,M6=s),l=vi(o,l+1,e.subarray(v,M6))}i.i=s}return qh(r,0,L+Fi(l)+n)};
var Ri=function(){var e=1,C=0;return{p:function(t){for(var L=e,n=C,i=t.length|0,s=0;s!=i;){for(var r=Math.min(s+2655,i);s<r;++s)n+=L+=t[s];L=(L&65535)+15*(L>>16),n=(n&65535)+15*(n>>16)}e=L,C=n},d:function(){return e%=65521,C%=65521,(e&255)<<24|(e&65280)<<8|(C&255)<<8|C>>8}}};
var Xh=function(e,C,t,L,n){if(!n&&(n={l:1},C.dictionary)){var i=C.dictionary.subarray(-32768),s=new q2(i.length+e.length);s.set(i),s.set(e,i.length),e=s,n.w=i.length}return Vh(e,C.level==null?6:C.level,C.mem==null?n.l?Math.ceil(Math.max(8,Math.min(13,Math.log(e.length)))*1.5):20:12+C.mem,t,L,n)};
var Ti=function(e,C,t){for(;t;++C)e[C]=t,t>>>=8};
var Kh=function(e,C){var t=C.level,L=t==0?0:t<6?1:t==9?3:2;if(e[0]=120,e[1]=L<<6|(C.dictionary&&32),e[1]|=31-(e[0]<<8|e[1])%31,C.dictionary){var n=Ri();n.p(C.dictionary),Ti(e,2,n.d())}};
function pC(e,C){C||(C={});var t=Ri();t.p(e);var L=Xh(e,C,C.dictionary?6:2,4);return Kh(L,C),Ti(L,L.length-4,t.d()),L}
var Qh=typeof TextDecoder<"u"&&new TextDecoder;
var Zh=0;
try{Qh.decode(Si,{stream:!0}),Zh=1}catch{}
var Ii=Uint8Array.of(137,80,78,71,13,10,26,10);
var X4=K4+12+768;
function Pi(e,C,t,L,n){let i=new Uint8Array(13),s=new DataView(i.buffer);return s.setUint32(0,C),s.setUint32(4,t),i.set([8,3,0,0,0],8),$i([Ii,i3("IHDR",i),i3("PLTE",zi(L)),i3("tRNS",Wi(L,n)),i3("IDAT",pC(Jh(e,C,t),{level:6})),i3("IEND",new Uint8Array(0))])}
function _i(e,C,t){let L=new Uint8Array(13),n=new DataView(L.buffer);return n.setUint32(0,C),n.setUint32(4,t),L.set([8,6,0,0,0],8),$i([Ii,i3("IHDR",L),i3("IDAT",pC(Yh(e,C,t),{level:6})),i3("IEND",new Uint8Array(0))])}
function Yh(e,C,t){let L=C*4,n=new Uint8Array(t*(L+1)),i=[new Uint8Array(L),new Uint8Array(L),new Uint8Array(L),new Uint8Array(L)],s=r=>{let o=0;for(let c=0;c<r.length;c++)o+=r[c]<128?r[c]:256-r[c];return o};for(let r=0;r<t;r++){let o=r*L,c=r>0?o-L:-1,[l,u,x,p]=i;for(let b=0;b<L;b++){let y=e[o+b],E=b>=4?e[o+b-4]:0,w=c>=0?e[c+b]:0,D=c>=0&&b>=4?e[c+b-4]:0;l[b]=y,u[b]=y-E&255,x[b]=y-w&255;let S=E+w-D,F=S>E?S-E:E-S,k=S>w?S-w:w-S,v=S>D?S-D:D-S;p[b]=y-(F<=k&&F<=v?E:k<=v?w:D)&255}let h=0,d=1/0;for(let b=0;b<4;b++){let y=s(i[b]);y<d&&(d=y,h=b)}let M=[0,1,2,4][h];n[r*(L+1)]=M,n.set(i[h],r*(L+1)+1)}return n}
function I7(e,C,t){let L=new DataView(e.buffer,e.byteOffset,e.byteLength);if(!(e.length>X4+12+256&&L.getUint32(K4)===768&&e[K4+4]===80&&e[K4+5]===76&&e[K4+6]===84&&e[K4+7]===69&&L.getUint32(X4)===256&&e[X4+4]===116&&e[X4+5]===82&&e[X4+6]===78&&e[X4+7]===83))throw new Error("recolorPng: not a kittex palette PNG");let i=e.slice();return i.set(i3("PLTE",zi(C)),K4),i.set(i3("tRNS",Wi(C,t)),X4),i}
function F6(e,C,t){let L=Oi(C),n=Oi(t);if(!(Math.abs(L-n)>.001))return e;let i=O7(Ni(L)*e+Ni(n)*(1-e));return Math.min(1,Math.max(0,(i-n)/(L-n)))}
function Wi(e,C){let t=new Uint8Array(256);for(let L=0;L<256;L++)t[L]=C&&L>0&&L<255?Math.round(255*F6(L/255,e,C)):L;return t}
var O7=e=>e<=.04045?e/12.92:((e+.055)/1.055)**2.4;
var Ni=e=>e<=.0031308?e*12.92:1.055*e**(1/2.4)-.055;
var Oi=e=>.2126*O7(w6(e.r)/255)+.7152*O7(w6(e.g)/255)+.0722*O7(w6(e.b)/255);
function zi(e){let C=new Uint8Array(768),t=w6(e.r),L=w6(e.g),n=w6(e.b);for(let i=0;i<768;i+=3)C[i]=t,C[i+1]=L,C[i+2]=n;return C}
var w6=e=>Math.min(255,Math.max(0,Math.round(e)))||0;
function Jh(e,C,t){let L=new Uint8Array(t*(C+1));for(let n=0;n<t;n++)L.set(e.subarray(n*C,n*C+C),n*(C+1)+1);return L}
function i3(e,C){let t=new Uint8Array(12+C.length),L=new DataView(t.buffer);L.setUint32(0,C.length);for(let n=0;n<4;n++)t[4+n]=e.charCodeAt(n);return t.set(C,8),L.setUint32(8+C.length,td(t,4,8+C.length)),t}
var Cd;
function td(e,C,t){let L=Cd??=Uint32Array.from({length:256},(i,s)=>{let r=s;for(let o=0;o<8;o++)r=r&1?3988292384^r>>>1:r>>>1;return r>>>0}),n=4294967295;for(let i=C;i<t;i++)n=L[(n^e[i])&255]^n>>>8;return(n^4294967295)>>>0}
function $i(e){let C=new Uint8Array(e.reduce((L,n)=>L+n.length,0)),t=0;for(let L of e)C.set(L,t),t+=L.length;return C}
var P7=class{constructor(C,t){this.width=C;this.height=t;this.pixels=new Uint8Array(C*t*4)}width;height;pixels;paint(C,t,L,n,i,s,r,o){let c=this.pixels,l=this.width,u=s==="erase",x=u?0:s.r,p=u?0:s.g,h=u?0:s.b,d=Math.min(1,Math.max(0,r))/255;for(let M=0;M<i;M++){let b=L+M;if(!(b<0||b>=this.height))for(let y=0;y<n;y++){let E=C[M*n+y];if(E===0)continue;let w=t+y;if(w<0||w>=l)continue;let D=b*l+w,S=E*d;if(o){let v=o[D];if(v===0)continue;S=S*v/255}let F=1-S,k=D*4;u?(c[k]=c[k]*F+.5,c[k+1]=c[k+1]*F+.5,c[k+2]=c[k+2]*F+.5,c[k+3]=c[k+3]*F+.5):(c[k]=x*S+c[k]*F+.5,c[k+1]=p*S+c[k+1]*F+.5,c[k+2]=h*S+c[k+2]*F+.5,c[k+3]=255*S+c[k+3]*F+.5)}}}straight(C){let t=this.pixels,L=new Uint8Array(t.length),n=new Map;for(let i=0;i<t.length;i+=4){let s=t[i+3];if(s===0)continue;let r=s>>1,o=(t[i]*255+r)/s|0,c=(t[i+1]*255+r)/s|0,l=(t[i+2]*255+r)/s|0,u=o>255?255:o,x=c>255?255:c,p=l>255?255:l;if(L[i]=u,L[i+1]=x,L[i+2]=p,!C||s===255){L[i+3]=s;continue}let h=u<<16|x<<8|p,d=n.get(h);if(!d){if(n.size>=4096){L[i+3]=Math.round(255*F6(s/255,{r:u,g:x,b:p},C));continue}d=ed({r:u,g:x,b:p},C),n.set(h,d)}L[i+3]=d[s]}return L}};
function ed(e,C){let t=new Uint8Array(256);for(let L=0;L<256;L++)t[L]=L===0||L===255?L:Math.round(255*F6(L/255,e,C));return t}
function _7(e,C){let t=[];return Gi(e,C,.05,L=>{L.length>=6&&t.push(L)}),t}
function dC(e,C,t=.05){let L=[];return Gi(e,C,t,(n,i)=>{n.length>=4&&L.push({points:n,closed:i})}),L}
function Gi(e,C,t,L){let n=[],[i,s,r,o,c,l]=C,u=(H,q)=>i*H+r*q+c,x=(H,q)=>s*H+o*q+l,p=0,h=0,d=0,M=0,b=0,y=0,E="",w=(H=!1)=>{n.length>0&&L(n,H),n=[]},D=()=>{n.length===0&&n.push(u(p,h),x(p,h))},S=(H,q)=>{D(),n.push(u(H,q),x(H,q)),p=H,h=q},F=(H,q,W,j)=>{D();let z=u(p,h),X=x(p,h),t1=u(H,q),J=x(H,q),e1=u(W,j),u1=x(W,j),d1=z-2*t1+e1,m1=X-2*J+u1,p1=Math.min(100,Math.ceil(Math.sqrt(Math.hypot(d1,m1)/(4*t))));for(let l1=1;l1<p1;l1++){let k1=l1/p1,y2=1-k1;n.push(y2*y2*z+2*y2*k1*t1+k1*k1*e1,y2*y2*X+2*y2*k1*J+k1*k1*u1)}n.push(e1,u1),p=W,h=j},k=(H,q,W,j,z,X)=>{D();let t1=u(p,h),J=x(p,h),e1=u(H,q),u1=x(H,q),d1=u(W,j),m1=x(W,j),p1=u(z,X),l1=x(z,X),k1=Math.hypot(t1-2*e1+d1,J-2*u1+m1),y2=Math.hypot(e1-2*d1+p1,u1-2*m1+l1),f3=Math.min(100,Math.ceil(Math.sqrt(.75*Math.max(k1,y2)/t)));for(let v5=1;v5<f3;v5++){let t3=v5/f3,m3=1-t3,S5=m3*m3*m3,M6=3*m3*m3*t3,A6=3*m3*t3*t3,$L=t3*t3*t3;n.push(S5*t1+M6*e1+A6*d1+$L*p1,S5*J+M6*u1+A6*m1+$L*l1)}n.push(p1,l1),p=z,h=X},v=(H,q,W,j,z,X,t1)=>{for(let J of Ld(p,h,H,q,W,j,z,X,t1))k(...J);p=X,h=t1},I=new hC(e),V="";for(;I.skip(),!I.done();){let H=I.command();if(H)V=H;else{if(!V||V==="Z"||V==="z")break;V==="M"?V="L":V==="m"&&(V="l")}let q=V===V.toLowerCase(),W=q?p:0,j=q?h:0,z=V.toUpperCase(),X=NaN,t1=NaN;if(z==="Z")w(!0),p=d,h=M;else if(z==="M"){let J=I.number()+W,e1=I.number()+j;if(Number.isNaN(J+e1))break;w(),p=d=J,h=M=e1}else if(z==="L"){let J=I.number()+W,e1=I.number()+j;if(Number.isNaN(J+e1))break;S(J,e1)}else if(z==="H"){let J=I.number()+W;if(Number.isNaN(J))break;S(J,h)}else if(z==="V"){let J=I.number()+j;if(Number.isNaN(J))break;S(p,J)}else if(z==="C"||z==="S"){let J,e1;z==="C"?(J=I.number()+W,e1=I.number()+j):E==="C"||E==="S"?(J=2*p-b,e1=2*h-y):(J=p,e1=h);let u1=I.number()+W,d1=I.number()+j,m1=I.number()+W,p1=I.number()+j;if(Number.isNaN(J+e1+u1+d1+m1+p1))break;k(J,e1,u1,d1,m1,p1),X=u1,t1=d1}else if(z==="Q"||z==="T"){let J,e1;z==="Q"?(J=I.number()+W,e1=I.number()+j):E==="Q"||E==="T"?(J=2*p-b,e1=2*h-y):(J=p,e1=h);let u1=I.number()+W,d1=I.number()+j;if(Number.isNaN(J+e1+u1+d1))break;F(J,e1,u1,d1),X=J,t1=e1}else if(z==="A"){let J=I.number(),e1=I.number(),u1=I.number(),d1=I.flag(),m1=I.flag(),p1=I.number()+W,l1=I.number()+j;if(Number.isNaN(J+e1+u1+d1+m1+p1+l1))break;v(J,e1,u1,d1===1,m1===1,p1,l1)}else break;b=X,y=t1,E=z}w()}
var hC=class{constructor(C){this.s=C}s;i=0;done(){return this.i>=this.s.length}skip(){for(;this.i<this.s.length;){let C=this.s.charCodeAt(this.i);if(C===32||C===44||C===9||C===10||C===13||C===12)this.i++;else break}}command(){let C=this.s[this.i];return"MmLlHhVvCcSsQqTtAaZz".includes(C)?(this.i++,C):""}number(){this.skip();let C=this.s,t=this.i,L=t;(C[L]==="+"||C[L]==="-")&&L++;let n=L;for(;L<C.length&&C.charCodeAt(L)>=48&&C.charCodeAt(L)<=57;)L++;if(C[L]===".")for(L++;L<C.length&&C.charCodeAt(L)>=48&&C.charCodeAt(L)<=57;)L++;if(L===n||L===n+1&&C[n]===".")return NaN;if(C[L]==="e"||C[L]==="E"){let i=L+1;(C[i]==="+"||C[i]==="-")&&i++;let s=i;for(;i<C.length&&C.charCodeAt(i)>=48&&C.charCodeAt(i)<=57;)i++;i>s&&(L=i)}return this.i=L,Number(C.slice(t,L))}flag(){this.skip();let C=this.s[this.i];return C==="0"||C==="1"?(this.i++,C==="1"?1:0):NaN}};
function Ld(e,C,t,L,n,i,s,r,o){if(e===r&&C===o)return[];if(t=Math.abs(t),L=Math.abs(L),t===0||L===0)return[[e,C,r,o,r,o]];let c=n*Math.PI/180,l=Math.cos(c),u=Math.sin(c),x=(e-r)/2,p=(C-o)/2,h=l*x+u*p,d=-u*x+l*p,M=h*h/(t*t)+d*d/(L*L);M>1&&(t*=Math.sqrt(M),L*=Math.sqrt(M));let b=t*t*L*L-t*t*d*d-L*L*h*h,y=t*t*d*d+L*L*h*h,E=Math.sqrt(Math.max(0,b/y));i===s&&(E=-E);let w=E*t*d/L,D=-E*L*h/t,S=l*w-u*D+(e+r)/2,F=u*w+l*D+(C+o)/2,k=(e1,u1,d1,m1)=>Math.atan2(e1*m1-u1*d1,e1*d1+u1*m1),v=k(1,0,(h-w)/t,(d-D)/L),I=k((h-w)/t,(d-D)/L,(-h-w)/t,(-d-D)/L);!s&&I>0&&(I-=2*Math.PI),s&&I<0&&(I+=2*Math.PI);let V=Math.max(1,Math.ceil(Math.abs(I)/(Math.PI/2)-1e-9)),H=I/V,q=4/3*Math.tan(H/4),W=e1=>{let u1=Math.cos(e1),d1=Math.sin(e1);return[S+t*u1*l-L*d1*u,F+t*u1*u+L*d1*l,-t*d1*l-L*u1*u,-t*d1*u+L*u1*l]},j=[],[z,X,t1,J]=W(v);for(let e1=1;e1<=V;e1++){let[u1,d1,m1,p1]=W(v+e1*H),l1=e1===V?r:u1,k1=e1===V?o:d1;j.push([z+q*t1,X+q*J,l1-q*m1,k1-q*p1,l1,k1]),z=l1,X=k1,t1=m1,J=p1}return j}
function fC(e,C){let t=C.width/2;if(!(t>0))return[];let L=[];for(let n of nd(e,C))id(n,t,C,L);for(let n of L)rd(n)<0&&od(n);return L}
function nd(e,C){let t=C.dash;if(!t||t.length===0)return[...e];let L=t.reduce((i,s)=>i+s,0);if(!(L>=.5))return[...e];let n=[];for(let i of e){let s=i.points.slice();i.closed&&s.push(s[0],s[1]);let r=((C.dashOffset??0)%L+L)%L,o=0;for(;r>=t[o];)r-=t[o],o=(o+1)%t.length;let c=t[o]-r,l=o%2===0,u=l?[s[0],s[1]]:[];for(let x=0;x+3<s.length;x+=2){let p=s[x],h=s[x+1],d=s[x+2],M=s[x+3],b=Math.hypot(d-p,M-h),y=0;for(;b-y>c;){y+=c;let E=y/b,w=p+(d-p)*E,D=h+(M-h)*E;if(l){if(u.push(w,D),n.push({points:u,closed:!1}),n.length>2e4)return[...e];u=[]}else u=[w,D];l=!l,o=(o+1)%t.length,c=t[o]}c-=b-y,l&&u.push(d,M)}l&&u.length>=4&&n.push({points:u,closed:!1})}return n}
function id(e,C,t,L){let n=[];for(let x=0;x+1<e.points.length;x+=2){let p=e.points[x],h=e.points[x+1],d=n.length;d>=2&&Math.abs(p-n[d-2])<.01&&Math.abs(h-n[d-1])<.01||n.push(p,h)}let i=e.closed;i&&n.length>=4&&Math.abs(n[0]-n[n.length-2])<.01&&Math.abs(n[1]-n[n.length-1])<.01&&(n.length-=2);let s=n.length/2;if(s<2){if(s===1&&t.cap!=="butt"&&e.points.length>=4){let x=n[0],p=n[1];L.push(t.cap==="round"?mC(x,p,C):[x-C,p-C,x+C,p-C,x+C,p+C,x-C,p+C])}return}s===2&&(i=!1);let r=i?s:s-1,o=new Float64Array(r),c=new Float64Array(r);for(let x=0;x<r;x++){let p=(x+1)%s,h=n[2*p]-n[2*x],d=n[2*p+1]-n[2*x+1],M=Math.hypot(h,d);o[x]=h/M,c[x]=d/M}for(let x=0;x<r;x++){let p=(x+1)%s,h=-c[x]*C,d=o[x]*C,M=n[2*x],b=n[2*x+1],y=n[2*p],E=n[2*p+1];L.push([M+h,b+d,y+h,E+d,y-h,E-d,M-h,b-d])}let l=i?0:1,u=i?s-1:s-2;for(let x=l;x<=u;x++){let p=(x-1+r)%r,h=x%r;sd(n[2*x],n[2*x+1],o[p],c[p],o[h],c[h],C,t,L)}i||(Hi(n[0],n[1],-o[0],-c[0],C,t.cap,L),Hi(n[2*s-2],n[2*s-1],o[r-1],c[r-1],C,t.cap,L))}
function sd(e,C,t,L,n,i,s,r,o){let c=t*i-L*n,l=t*n+L*i,u=Math.atan2(Math.abs(c),l);if(s*u<.02)return;let x=c>0?-1:1,p=e+x*-L*s,h=C+x*t*s,d=e+x*-i*s,M=C+x*n*s;if(r.join==="round"&&s*u>.25){o.push(mC(e,C,s));return}if(r.join==="miter"){let b=1/Math.sqrt(Math.max(1e-12,(1+l)/2));if(b<=r.miterLimit){let y=-L-i,E=t+n,w=Math.hypot(y,E);if(w>1e-9){y=y/w*x*s*b,E=E/w*x*s*b,o.push([e,C,p,h,e+y,C+E,d,M]);return}}}o.push([e,C,p,h,d,M])}
function Hi(e,C,t,L,n,i,s){if(i==="round")s.push(mC(e,C,n));else if(i==="square"){let r=-L*n,o=t*n,c=e+t*n,l=C+L*n;s.push([e+r,C+o,c+r,l+o,c-r,l-o,e-r,C-o])}}
function mC(e,C,t){let L=t<=.05?6:Math.min(128,Math.max(6,Math.ceil(Math.PI/Math.acos(1-.05/t)))),n=[];for(let i=0;i<L;i++){let s=2*Math.PI*i/L;n.push(e+t*Math.cos(s),C+t*Math.sin(s))}return n}
function rd(e){let C=0,t=e.length,L=e[t-2],n=e[t-1];for(let i=0;i<t;i+=2)C+=L*e[i+1]-e[i]*n,L=e[i],n=e[i+1];return C/2}
function od(e){for(let C=0,t=e.length-2;C<t;C+=2,t-=2){let L=e[C],n=e[C+1];e[C]=e[t],e[C+1]=e[t+1],e[t]=L,e[t+1]=n}}
function ji(e,C){let t=Math.max(1,Math.round(C)),L=i=>t%2===1?Math.floor(i)+.5:Math.round(i),n=!1;for(let i of e){let s=i.points;i.closed&&s.length>=6&&Math.abs(s[0]-s[s.length-2])<.01&&Math.abs(s[1]-s[s.length-1])<.01&&(s.length-=2);let r=s.length/2,o=i.closed?r:r-1,c=new Uint8Array(r),l=new Uint8Array(r);for(let u=0;u<o;u++){let x=(u+1)%r,p=s[2*x]-s[2*u],h=s[2*x+1]-s[2*u+1],d=Math.hypot(p,h);d>0&&(Math.abs(h)<.001*d?l[u]=l[x]=1:Math.abs(p)<.001*d&&(c[u]=c[x]=1))}for(let u=0;u<r;u++)c[u]&&(s[2*u]=L(s[2*u])),l[u]&&(s[2*u+1]=L(s[2*u+1])),(c[u]||l[u])&&(n=!0)}return n?t:C}
var U5=[[300,12],[400,G7],[500,20],[600,23],[700,26]];
function ad(e){if(e===void 0||!Number.isFinite(e))return G7;let C=U5[0],t=U5.at(-1);if(e<=C[0])return C[1];if(e>=t[0])return t[1];let L=U5.findIndex(([o])=>o>=e),[n,i]=U5[L-1],[s,r]=U5[L];return Math.round(i+(r-i)*(e-n)/(s-n))}
function MC(e,C){let{emPx:t,cellWidth:L,cellHeight:n}=C;if(!(t>0&&L>0&&n>0))throw new RangeError("raster: emPx and cell sizes must be positive");let i=Math.max(1,Math.min(255,Math.floor(C.maxColumns)||1)),s=Math.max(1,Math.min(255,Math.ceil(C.minRows??1))),r=Math.max(0,C.weight??G7),o=Math.max(0,e.width),c=Math.max(0,e.height+e.depth),l=r/1e3*t,u=Math.ceil(l-1e-9),x=C.align==="left"&&C.centerInk?ld(e,t,l,u):void 0,p=x??o*t,h=i*L-(x===void 0?2*u:0),d=255*n-2*u,M=C.baselinePx!==void 0,b=1,y=0;if(p>h&&(b=Math.max(0,h-(x===void 0?0:qi))/p),M){let q=Math.max(1,Math.round(s*n)),W=Math.min(q,Math.max(0,Math.round(C.baselinePx))),j=Math.max(0,e.height)*t+l,z=Math.max(0,e.depth)*t+l,X=Math.max(1,Math.round(n*cd)),t1=C.minScale??0,J=m1=>p1=>Math.min(b,j>0?Math.max(0,p1-m1)/j:1/0,z>0?(q-p1)/z:1/0),e1=m1=>{let p1=W;for(let l1=1;l1<=X;l1++)for(let k1 of[W-l1,W+l1])k1>=0&&k1<=q&&m1(k1)>m1(p1)+1e-9&&(p1=k1);return{at:p1,scale:m1(p1)}},u1=e1(J(gC));u1.scale<t1&&(u1=e1(J(0))),y=u1.at,b=u1.scale;let d1=Math.max(0,C.overflowPx??0);if(b<t1&&d1>0){let m1=l1=>Math.min(j>0?(l1+d1)/j:1/0,z>0?(q-l1+d1)/z:1/0),p1=W;for(let l1=1;l1<=X;l1++)for(let k1 of[W-l1,W+l1])k1>=0&&k1<=q&&m1(k1)>m1(p1)+1e-9&&(p1=k1);m1(p1)>=t1-1e-9&&(p*t1<=h||h<=0)&&(y=p1,b=t1)}}else c*t*b>d&&(b=Math.max(0,d)/(c*t));let E=t*b,w=x===void 0?o*E+2*u:b===1?x:x*b+qi,D=c*E+2*u,S=Math.max(1,Math.floor(C.minColumns??1)),F=C.align==="center"?i:Math.min(i,Math.max(S,Math.ceil(w/L-1e-9))),k=M?s:Math.min(255,Math.max(s,Math.ceil(D/n-1e-9))),v=Math.max(1,Math.round(F*L)),I=Math.max(1,Math.round(k*n)),V=C.align==="center"?Math.round((v-o*E)/2):u,H=M?y:Math.round((I-D)/2+u+Math.max(0,e.height)*E);return{columns:F,rows:k,scale:b,widthPx:v,heightPx:I,k:E,dilation:l*b,originX:V,baselinePx:H}}
function K3(e,C){let{columns:t,rows:L,scale:n}=MC(e,C);return{columns:t,rows:L,scale:n}}
function v6(e,C){let t=MC(e,C),{widthPx:L,heightPx:n,k:i,dilation:s,originX:r,baselinePx:o}=t,c=new y6(L,n),l=[i,0,0,i,r,o],u=Math.max(j7,.15*i),x=e.ops.flatMap(h=>Vi(h,l,s,u)??[]),p=C.align==="left"&&C.centerInk?ud(x,L,C.inkPlace??"center"):0;for(let{contours:h,sign:d}of x)for(let M of h){if(p!==0)for(let b=0;b<M.length;b+=2)M[b]=M[b]+p;c.fill(M,d)}return{columns:t.columns,rows:t.rows,scale:t.scale,alpha:c.toAlpha(),widthPx:L,heightPx:n,baselinePx:o}}
function H7(e,C,t){return Pi(e.alpha,e.widthPx,e.heightPx,C,t)}
function ld(e,C,t,L){let n=[C,0,0,C,L,0],i=e.ops.flatMap(o=>Vi(o,n,t,Math.max(j7,.15*C))??[]),{x0:s,x1:r}=Ui(i);return r>s?Math.ceil(r-1e-9)-Math.floor(s+1e-9):void 0}
function Ui(e){let C=1/0,t=-1/0;for(let{contours:L}of e)for(let n of L)for(let i=0;i<n.length;i+=2)n[i]<C&&(C=n[i]),n[i]>t&&(t=n[i]);return{x0:C,x1:t}}
function ud(e,C,t){let{x0:L,x1:n}=Ui(e);if(!(n>L)||n-L>C)return 0;let i=C-(n-L),s=Math.round((t==="start"?0:t==="end"?i:i/2)-L);return Math.min(Math.max(s,Math.ceil(-L-1e-9)),Math.floor(C-n+1e-9))}
function Vi(e,C,t,L){let n;if(e.type==="rect"){let[o,,,,c,l]=C,u=c+o*Math.min(e.x,e.x+e.width),x=c+o*Math.max(e.x,e.x+e.width),p=l+o*Math.min(e.y,e.y+e.height),h=l+o*Math.max(e.y,e.y+e.height);if(!(x>u&&h>p))return;n=[[u,p,x,p,x,h,u,h]]}else n=_7(e.d,z7(C,e.transform));let i=0;for(let o of n)i+=$7(o);if(!(Math.abs(i)>1e-9))return;let s=i>0?1:-1,r=[];for(let o of n)t>0&&(o=Xi(o,t,s)),Ki(o,L),r.push(o);return{contours:r,sign:s}}
function z7(e,C){return[e[0]*C[0]+e[2]*C[1],e[1]*C[0]+e[3]*C[1],e[0]*C[2]+e[2]*C[3],e[1]*C[2]+e[3]*C[3],e[0]*C[4]+e[2]*C[5]+e[4],e[1]*C[4]+e[3]*C[5]+e[5]]}
function $7(e){let C=0,t=e.length,L=e[t-2],n=e[t-1];for(let i=0;i<t;i+=2){let s=e[i],r=e[i+1];C+=L*r-s*n,L=s,n=r}return C/2}
function Xi(e,C,t){let L=[];for(let o=0;o<e.length;o+=2){let c=e[o],l=e[o+1],u=L.length;u>=2&&Math.abs(c-L[u-2])<1e-6&&Math.abs(l-L[u-1])<1e-6||L.push(c,l)}for(;L.length>=4&&Math.abs(L[0]-L[L.length-2])<1e-6&&Math.abs(L[1]-L[L.length-1])<1e-6;)L.length-=2;let n=L.length/2;if(n<3)return e;let i=new Float64Array(n),s=new Float64Array(n);for(let o=0;o<n;o++){let c=(o+1)%n,l=L[2*c]-L[2*o],u=L[2*c+1]-L[2*o+1],x=Math.hypot(l,u);i[o]=t*u/x,s[o]=-t*l/x}let r=new Array(2*n);for(let o=0;o<n;o++){let c=(o+n-1)%n,l=i[c]+i[o],u=s[c]+s[o],x=1+i[c]*i[o]+s[c]*s[o],p=0,h=0;if(x>=.5)p=l/x,h=u/x;else{let d=Math.hypot(l,u);d>1e-9&&(p=2*l/d,h=2*u/d)}r[2*o]=L[2*o]+C*p,r[2*o+1]=L[2*o+1]+C*h}return r}
function Ki(e,C=j7){let t=1/0,L=1/0,n=-1/0,i=-1/0;for(let h=0;h<e.length;h+=2){let d=e[h],M=e[h+1];d<t&&(t=d),d>n&&(n=d),M<L&&(L=M),M>i&&(i=M)}let s=n-t,r=i-L;if(!(s>0&&r>0)||Math.abs($7(e))<xd*s*r)return;let o=r<=C&&s>=2*r?1:s<=C&&r>=2*s?0:-1;if(o<0)return;let c=o===1?L:t,l=o===1?r:s,u=Math.max(1,Math.round(l)),x=Math.round(c+l/2-u/2),p=u/l;for(let h=o;h<e.length;h+=2)e[h]=x+(e[h]-c)*p}
export{MC,P7,_7,z7,$7,Xi,Ki,dC,ji,fC,_i,K3,v6,H7,I7,F6,ad};
