import{V2,F2,Ii,D3,Fi,Q4,_7,X5,ld,ud,U5,mC,gC,fC,pC,vi,xd,Y4,V7,Yi,Rd,yC,v6,K7,Od}from'./p21.js';export*from'./p21.js';
var xC=function(e,C){for(var t=[],L=0;L<e.length;++L)e[L]&&t.push({s:L,f:e[L]});var n=t.length,i=t.slice();if(!n)return{t:_i,l:0};if(n==1){var s=new V2(t[0].s+1);return s[t[0].s]=1,{t:s,l:1}}t.sort(function(D,v){return D.f-v.f}),t.push({s:-1,f:25001});var r=t[0],o=t[1],a=0,l=1,u=2;for(t[0]={s:-1,f:r.f+o.f,l:r,r:o};l!=n-1;)r=t[t[a].f<t[u].f?a++:u++],o=t[a!=l&&t[a].f<t[u].f?a++:u++],t[l++]={s:-1,f:r.f+o.f,l:r,r:o};for(var x=i[0].s,L=1;L<n;++L)i[L].s>x&&(x=i[L].s);var p=new F2(x+1),h=dC(t[l-1],p,0);if(h>C){var L=0,d=0,m=h-C,b=1<<m;for(i.sort(function(v,F){return p[F.s]-p[v.s]||v.f-F.f});L<n;++L){var B=i[L].s;if(p[B]>C)d+=b-(1<<h-p[B]),p[B]=C;else break}for(d>>=m;d>0;){var A=i[L].s;p[A]<C?d-=1<<C-p[A]++-1:++L}for(;L>=0&&d;--L){var k=i[L].s;p[k]==C&&(--p[k],++d)}h=C}return{t:new V2(p),l:h}};
var dC=function(e,C,t){return e.s==-1?Math.max(dC(e.l,C,t+1),dC(e.r,C,t+1)):C[e.s]=t};
var Si=function(e){for(var C=e.length;C&&!e[--C];);for(var t=new F2(++C),L=0,n=e[0],i=1,s=function(o){t[L++]=o},r=1;r<=C;++r)if(e[r]==n&&r!=C)++i;else{if(!n&&i>2){for(;i>138;i-=138)s(32754);i>2&&(s(i>10?i-11<<5|28690:i-3<<5|12305),i=0)}else if(i>3){for(s(n),--i;i>6;i-=6)s(8304);i>2&&(s(i-3<<5|8208),i=0)}for(;i--;)s(n);i=1,n=e[r]}return{c:t.subarray(0,L),n:C}};
var V5=function(e,C){for(var t=0,L=0;L<C.length;++L)t+=e[L]*C[L];return t};
var Pi=function(e,C,t){var L=t.length,n=Ii(C+2);e[n]=L&255,e[n+1]=L>>8,e[n+2]=e[n]^255,e[n+3]=e[n+1]^255;for(var i=0;i<L;++i)e[n+i+4]=t[i];return(n+4+L)*8};
var Ri=function(e,C,t,L,n,i,s,r,o,a,l){D3(C,l++,t),++n[256];for(var u=xC(n,15),x=u.t,p=u.l,h=xC(i,15),d=h.t,m=h.l,b=Si(x),B=b.c,A=b.n,k=Si(d),D=k.c,v=k.n,F=new F2(19),y=0;y<B.length;++y)++F[B[y]&31];for(var y=0;y<D.length;++y)++F[D[y]&31];for(var S=xC(F,7),I=S.t,U=S.l,H=19;H>4&&!I[Fi[H-1]];--H);var q=a+5<<3,z=V5(n,Q4)+V5(i,_7)+s,j=V5(n,x)+V5(i,d)+s+14+3*H+V5(F,I)+2*F[16]+3*F[17]+7*F[18];if(o>=0&&q<=z&&q<=j)return Pi(C,l,e.subarray(o,o+a));var W,X,t1,J;if(D3(C,l,1+(j<z)),l+=2,j<z){W=X5(x,p,0),X=x,t1=X5(d,m,0),J=d;var e1=X5(I,U,0);D3(C,l,A-257),D3(C,l+5,v-1),D3(C,l+10,H-4),l+=14;for(var y=0;y<H;++y)D3(C,l+3*y,I[Fi[y]]);l+=3*H;for(var u1=[B,D],d1=0;d1<2;++d1)for(var m1=u1[d1],y=0;y<m1.length;++y){var p1=m1[y]&31;D3(C,l,e1[p1]),l+=I[p1],p1>15&&(D3(C,l,m1[y]>>5&127),l+=m1[y]>>12)}}else W=ld,X=Q4,t1=ud,J=_7;for(var y=0;y<r;++y){var l1=L[y];if(l1>255){var p1=l1>>18&31;U5(C,l,W[p1+257]),l+=X[p1+257],p1>7&&(D3(C,l,l1>>23&31),l+=mC[p1]);var y1=l1&31;U5(C,l,t1[y1]),l+=J[y1],y1>3&&(U5(C,l,l1>>5&8191),l+=gC[y1])}else U5(C,l,W[l1]),l+=X[l1]}return U5(C,l,W[256]),l+X[256]};
var pd=new fC([65540,131080,131088,131104,262176,1048704,1048832,2114560,2117632]);
var _i=new V2(0);
var hd=function(e,C,t,L,n,i){var s=i.z||e.length,r=new V2(L+s+5*(1+Math.ceil(s/7e3))+n),o=r.subarray(L,r.length-n),a=i.l,l=(i.r||0)&7;if(C){l&&(o[0]=i.r>>3);for(var u=pd[C-1],x=u>>13,p=u&8191,h=(1<<t)-1,d=i.p||new F2(32768),m=i.h||new F2(h+1),b=Math.ceil(t/3),B=2*b,A=function(D6){return(e[D6]^e[D6+1]<<b^e[D6+2]<<B)&h},k=new fC(25e3),D=new F2(288),v=new F2(32),F=0,y=0,S=i.i||0,I=0,U=i.w||0,H=0;S+2<s;++S){var q=A(S),z=S&32767,j=m[q];if(d[z]=j,m[q]=z,U<=S){var W=s-S;if((F>7e3||I>24576)&&(W>423||!a)){l=Ri(e,o,0,k,D,v,y,I,H,S-H,l),I=F=y=0,H=S;for(var X=0;X<286;++X)D[X]=0;for(var X=0;X<30;++X)v[X]=0}var t1=2,J=0,e1=p,u1=z-j&32767;if(W>2&&q==A(S-u1))for(var d1=Math.min(x,W)-1,m1=Math.min(32767,S),p1=Math.min(258,W);u1<=m1&&--e1&&z!=j;){if(e[S+t1]==e[S+t1-u1]){for(var l1=0;l1<p1&&e[S+l1]==e[S+l1-u1];++l1);if(l1>t1){if(t1=l1,J=u1,l1>d1)break;for(var y1=Math.min(u1,l1-2),w2=0,X=0;X<y1;++X){var g3=S-u1+X&32767,T5=d[g3],L3=g3-T5&32767;L3>w2&&(w2=L3,j=g3)}}}z=j,j=d[z],u1+=z-j&32767}if(J){k[I++]=268435456|pC[t1]<<18|vi[J];var M3=pC[t1]&31,N5=vi[J]&31;y+=mC[M3]+gC[N5],++D[257+M3],++v[N5],U=S+t1,++F}else k[I++]=e[S],++D[e[S]]}}for(S=Math.max(S,U);S<s;++S)k[I++]=e[S],++D[e[S]];l=Ri(e,o,a,k,D,v,y,I,H,S-H,l),a||(i.r=l&7|o[l/8|0]<<3,l-=7,i.h=m,i.p=d,i.i=S,i.w=U)}else{for(var S=i.w||0;S<s+a;S+=65535){var b6=S+65535;b6>=s&&(o[l/8|0]=a,b6=s),l=Pi(o,l+1,e.subarray(S,b6))}i.i=s}return xd(r,0,L+Ii(l)+n)};
var zi=function(){var e=1,C=0;return{p:function(t){for(var L=e,n=C,i=t.length|0,s=0;s!=i;){for(var r=Math.min(s+2655,i);s<r;++s)n+=L+=t[s];L=(L&65535)+15*(L>>16),n=(n&65535)+15*(n>>16)}e=L,C=n},d:function(){return e%=65521,C%=65521,(e&255)<<24|(e&65280)<<8|(C&255)<<8|C>>8}}};
var dd=function(e,C,t,L,n){if(!n&&(n={l:1},C.dictionary)){var i=C.dictionary.subarray(-32768),s=new V2(i.length+e.length);s.set(i),s.set(e,i.length),e=s,n.w=i.length}return hd(e,C.level==null?6:C.level,C.mem==null?n.l?Math.ceil(Math.max(8,Math.min(13,Math.log(e.length)))*1.5):20:12+C.mem,t,L,n)};
var Wi=function(e,C,t){for(;t;++C)e[C]=t,t>>>=8};
var fd=function(e,C){var t=C.level,L=t==0?0:t<6?1:t==9?3:2;if(e[0]=120,e[1]=L<<6|(C.dictionary&&32),e[1]|=31-(e[0]<<8|e[1])%31,C.dictionary){var n=zi();n.p(C.dictionary),Wi(e,2,n.d())}};
function MC(e,C){C||(C={});var t=zi();t.p(e);var L=dd(e,C,C.dictionary?6:2,4);return fd(L,C),Wi(L,L.length-4,t.d()),L}
var md=typeof TextDecoder<"u"&&new TextDecoder;
var gd=0;
try{md.decode(_i,{stream:!0}),gd=1}catch{}
var Gi=Uint8Array.of(137,80,78,71,13,10,26,10);
var Z4=Y4+12+768;
function Hi(e,C,t,L,n,i){let s=new Uint8Array(13),r=new DataView(s.buffer);return r.setUint32(0,C),r.setUint32(4,t),s.set([8,3,0,0,0],8),Xi([Gi,r3("IHDR",s),r3("PLTE",Vi(L)),r3("tRNS",Ui(L,n,i)),r3("IDAT",MC(Ad(e,C,t),{level:6})),r3("IEND",new Uint8Array(0))])}
function ji(e,C,t){let L=new Uint8Array(13),n=new DataView(L.buffer);return n.setUint32(0,C),n.setUint32(4,t),L.set([8,6,0,0,0],8),Xi([Gi,r3("IHDR",L),r3("IDAT",MC(Md(e,C,t),{level:6})),r3("IEND",new Uint8Array(0))])}
function Md(e,C,t){let L=C*4,n=new Uint8Array(t*(L+1)),i=[new Uint8Array(L),new Uint8Array(L),new Uint8Array(L),new Uint8Array(L)],s=r=>{let o=0;for(let a=0;a<r.length;a++)o+=r[a]<128?r[a]:256-r[a];return o};for(let r=0;r<t;r++){let o=r*L,a=r>0?o-L:-1,[l,u,x,p]=i;for(let b=0;b<L;b++){let B=e[o+b],A=b>=4?e[o+b-4]:0,k=a>=0?e[a+b]:0,D=a>=0&&b>=4?e[a+b-4]:0;l[b]=B,u[b]=B-A&255,x[b]=B-k&255;let v=A+k-D,F=v>A?v-A:A-v,y=v>k?v-k:k-v,S=v>D?v-D:D-v;p[b]=B-(F<=y&&F<=S?A:y<=S?k:D)&255}let h=0,d=1/0;for(let b=0;b<4;b++){let B=s(i[b]);B<d&&(d=B,h=b)}let m=[0,1,2,4][h];n[r*(L+1)]=m,n.set(i[h],r*(L+1)+1)}return n}
function $7(e,C,t,L){let n=new DataView(e.buffer,e.byteOffset,e.byteLength);if(!(e.length>Z4+12+256&&n.getUint32(Y4)===768&&e[Y4+4]===80&&e[Y4+5]===76&&e[Y4+6]===84&&e[Y4+7]===69&&n.getUint32(Z4)===256&&e[Z4+4]===116&&e[Z4+5]===82&&e[Z4+6]===78&&e[Z4+7]===83))throw new Error("recolorPng: not a kittex palette PNG");let s=e.slice();return s.set(r3("PLTE",Vi(C)),Y4),s.set(r3("tRNS",Ui(C,t,L)),Z4),s}
function R6(e,C,t){let L=W7(C),n=W7(t);if(!(Math.abs(L-n)>.001))return e;let i=z7($i(L)*e+$i(n)*(1-e));return Math.min(1,Math.max(0,(i-n)/(L-n)))}
function qi(e,C,t,L){let n=L.gamma<.01?1:1/L.gamma,i=(1-W7(C)+W7(t))*.5,s=e+(e**n-e)*i;return Math.min(1,Math.max(0,s*(1+L.contrast*.01)))}
function Ui(e,C,t){let L=new Uint8Array(256);for(let n=0;n<256;n++)!C||n===0||n===255&&!t?L[n]=n:L[n]=Math.round(255*(t?qi(n/255,e,C,t):R6(n/255,e,C)));return L}
var z7=e=>e<=.04045?e/12.92:((e+.055)/1.055)**2.4;
var $i=e=>e<=.0031308?e*12.92:1.055*e**(1/2.4)-.055;
var W7=e=>.2126*z7(S6(e.r)/255)+.7152*z7(S6(e.g)/255)+.0722*z7(S6(e.b)/255);
function Vi(e){let C=new Uint8Array(768),t=S6(e.r),L=S6(e.g),n=S6(e.b);for(let i=0;i<768;i+=3)C[i]=t,C[i+1]=L,C[i+2]=n;return C}
var S6=e=>Math.min(255,Math.max(0,Math.round(e)))||0;
function Ad(e,C,t){let L=new Uint8Array(t*(C+1));for(let n=0;n<t;n++)L.set(e.subarray(n*C,n*C+C),n*(C+1)+1);return L}
function r3(e,C){let t=new Uint8Array(12+C.length),L=new DataView(t.buffer);L.setUint32(0,C.length);for(let n=0;n<4;n++)t[4+n]=e.charCodeAt(n);return t.set(C,8),L.setUint32(8+C.length,bd(t,4,8+C.length)),t}
var Ed;
function bd(e,C,t){let L=Ed??=Uint32Array.from({length:256},(i,s)=>{let r=s;for(let o=0;o<8;o++)r=r&1?3988292384^r>>>1:r>>>1;return r>>>0}),n=4294967295;for(let i=C;i<t;i++)n=L[(n^e[i])&255]^n>>>8;return(n^4294967295)>>>0}
function Xi(e){let C=new Uint8Array(e.reduce((L,n)=>L+n.length,0)),t=0;for(let L of e)C.set(L,t),t+=L.length;return C}
var G7=class{constructor(C,t){this.width=C;this.height=t;this.pixels=new Uint8Array(C*t*4)}width;height;pixels;paint(C,t,L,n,i,s,r,o){let a=this.pixels,l=this.width,u=s==="erase",x=u?0:s.r,p=u?0:s.g,h=u?0:s.b,d=Math.min(1,Math.max(0,r))/255;for(let m=0;m<i;m++){let b=L+m;if(!(b<0||b>=this.height))for(let B=0;B<n;B++){let A=C[m*n+B];if(A===0)continue;let k=t+B;if(k<0||k>=l)continue;let D=b*l+k,v=A*d;if(o){let S=o[D];if(S===0)continue;v=v*S/255}let F=1-v,y=D*4;u?(a[y]=a[y]*F+.5,a[y+1]=a[y+1]*F+.5,a[y+2]=a[y+2]*F+.5,a[y+3]=a[y+3]*F+.5):(a[y]=x*v+a[y]*F+.5,a[y+1]=p*v+a[y+1]*F+.5,a[y+2]=h*v+a[y+2]*F+.5,a[y+3]=255*v+a[y+3]*F+.5)}}}straight(C){let t=this.pixels,L=new Uint8Array(t.length),n=new Map;for(let i=0;i<t.length;i+=4){let s=t[i+3];if(s===0)continue;let r=s>>1,o=(t[i]*255+r)/s|0,a=(t[i+1]*255+r)/s|0,l=(t[i+2]*255+r)/s|0,u=o>255?255:o,x=a>255?255:a,p=l>255?255:l;if(L[i]=u,L[i+1]=x,L[i+2]=p,!C||s===255){L[i+3]=s;continue}let h=u<<16|x<<8|p,d=n.get(h);if(!d){if(n.size>=4096){L[i+3]=Math.round(255*R6(s/255,{r:u,g:x,b:p},C));continue}d=Dd({r:u,g:x,b:p},C),n.set(h,d)}L[i+3]=d[s]}return L}};
function Dd(e,C){let t=new Uint8Array(256);for(let L=0;L<256;L++)t[L]=L===0||L===255?L:Math.round(255*R6(L/255,e,C));return t}
function H7(e,C){let t=[];return Ki(e,C,.05,L=>{L.length>=6&&t.push(L)}),t}
function EC(e,C,t=.05){let L=[];return Ki(e,C,t,(n,i)=>{n.length>=4&&L.push({points:n,closed:i})}),L}
function Ki(e,C,t,L){let n=[],[i,s,r,o,a,l]=C,u=(H,q)=>i*H+r*q+a,x=(H,q)=>s*H+o*q+l,p=0,h=0,d=0,m=0,b=0,B=0,A="",k=(H=!1)=>{n.length>0&&L(n,H),n=[]},D=()=>{n.length===0&&n.push(u(p,h),x(p,h))},v=(H,q)=>{D(),n.push(u(H,q),x(H,q)),p=H,h=q},F=(H,q,z,j)=>{D();let W=u(p,h),X=x(p,h),t1=u(H,q),J=x(H,q),e1=u(z,j),u1=x(z,j),d1=W-2*t1+e1,m1=X-2*J+u1,p1=Math.min(100,Math.ceil(Math.sqrt(Math.hypot(d1,m1)/(4*t))));for(let l1=1;l1<p1;l1++){let y1=l1/p1,w2=1-y1;n.push(w2*w2*W+2*w2*y1*t1+y1*y1*e1,w2*w2*X+2*w2*y1*J+y1*y1*u1)}n.push(e1,u1),p=z,h=j},y=(H,q,z,j,W,X)=>{D();let t1=u(p,h),J=x(p,h),e1=u(H,q),u1=x(H,q),d1=u(z,j),m1=x(z,j),p1=u(W,X),l1=x(W,X),y1=Math.hypot(t1-2*e1+d1,J-2*u1+m1),w2=Math.hypot(e1-2*d1+p1,u1-2*m1+l1),g3=Math.min(100,Math.ceil(Math.sqrt(.75*Math.max(y1,w2)/t)));for(let T5=1;T5<g3;T5++){let L3=T5/g3,M3=1-L3,N5=M3*M3*M3,b6=3*M3*M3*L3,D6=3*M3*L3*L3,XL=L3*L3*L3;n.push(N5*t1+b6*e1+D6*d1+XL*p1,N5*J+b6*u1+D6*m1+XL*l1)}n.push(p1,l1),p=W,h=X},S=(H,q,z,j,W,X,t1)=>{for(let J of yd(p,h,H,q,z,j,W,X,t1))y(...J);p=X,h=t1},I=new AC(e),U="";for(;I.skip(),!I.done();){let H=I.command();if(H)U=H;else{if(!U||U==="Z"||U==="z")break;U==="M"?U="L":U==="m"&&(U="l")}let q=U===U.toLowerCase(),z=q?p:0,j=q?h:0,W=U.toUpperCase(),X=NaN,t1=NaN;if(W==="Z")k(!0),p=d,h=m;else if(W==="M"){let J=I.number()+z,e1=I.number()+j;if(Number.isNaN(J+e1))break;k(),p=d=J,h=m=e1}else if(W==="L"){let J=I.number()+z,e1=I.number()+j;if(Number.isNaN(J+e1))break;v(J,e1)}else if(W==="H"){let J=I.number()+z;if(Number.isNaN(J))break;v(J,h)}else if(W==="V"){let J=I.number()+j;if(Number.isNaN(J))break;v(p,J)}else if(W==="C"||W==="S"){let J,e1;W==="C"?(J=I.number()+z,e1=I.number()+j):A==="C"||A==="S"?(J=2*p-b,e1=2*h-B):(J=p,e1=h);let u1=I.number()+z,d1=I.number()+j,m1=I.number()+z,p1=I.number()+j;if(Number.isNaN(J+e1+u1+d1+m1+p1))break;y(J,e1,u1,d1,m1,p1),X=u1,t1=d1}else if(W==="Q"||W==="T"){let J,e1;W==="Q"?(J=I.number()+z,e1=I.number()+j):A==="Q"||A==="T"?(J=2*p-b,e1=2*h-B):(J=p,e1=h);let u1=I.number()+z,d1=I.number()+j;if(Number.isNaN(J+e1+u1+d1))break;F(J,e1,u1,d1),X=J,t1=e1}else if(W==="A"){let J=I.number(),e1=I.number(),u1=I.number(),d1=I.flag(),m1=I.flag(),p1=I.number()+z,l1=I.number()+j;if(Number.isNaN(J+e1+u1+d1+m1+p1+l1))break;S(J,e1,u1,d1===1,m1===1,p1,l1)}else break;b=X,B=t1,A=W}k()}
var AC=class{constructor(C){this.s=C}s;i=0;done(){return this.i>=this.s.length}skip(){for(;this.i<this.s.length;){let C=this.s.charCodeAt(this.i);if(C===32||C===44||C===9||C===10||C===13||C===12)this.i++;else break}}command(){let C=this.s[this.i];return"MmLlHhVvCcSsQqTtAaZz".includes(C)?(this.i++,C):""}number(){this.skip();let C=this.s,t=this.i,L=t;(C[L]==="+"||C[L]==="-")&&L++;let n=L;for(;L<C.length&&C.charCodeAt(L)>=48&&C.charCodeAt(L)<=57;)L++;if(C[L]===".")for(L++;L<C.length&&C.charCodeAt(L)>=48&&C.charCodeAt(L)<=57;)L++;if(L===n||L===n+1&&C[n]===".")return NaN;if(C[L]==="e"||C[L]==="E"){let i=L+1;(C[i]==="+"||C[i]==="-")&&i++;let s=i;for(;i<C.length&&C.charCodeAt(i)>=48&&C.charCodeAt(i)<=57;)i++;i>s&&(L=i)}return this.i=L,Number(C.slice(t,L))}flag(){this.skip();let C=this.s[this.i];return C==="0"||C==="1"?(this.i++,C==="1"?1:0):NaN}};
function yd(e,C,t,L,n,i,s,r,o){if(e===r&&C===o)return[];if(t=Math.abs(t),L=Math.abs(L),t===0||L===0)return[[e,C,r,o,r,o]];let a=n*Math.PI/180,l=Math.cos(a),u=Math.sin(a),x=(e-r)/2,p=(C-o)/2,h=l*x+u*p,d=-u*x+l*p,m=h*h/(t*t)+d*d/(L*L);m>1&&(t*=Math.sqrt(m),L*=Math.sqrt(m));let b=t*t*L*L-t*t*d*d-L*L*h*h,B=t*t*d*d+L*L*h*h,A=Math.sqrt(Math.max(0,b/B));i===s&&(A=-A);let k=A*t*d/L,D=-A*L*h/t,v=l*k-u*D+(e+r)/2,F=u*k+l*D+(C+o)/2,y=(e1,u1,d1,m1)=>Math.atan2(e1*m1-u1*d1,e1*d1+u1*m1),S=y(1,0,(h-k)/t,(d-D)/L),I=y((h-k)/t,(d-D)/L,(-h-k)/t,(-d-D)/L);!s&&I>0&&(I-=2*Math.PI),s&&I<0&&(I+=2*Math.PI);let U=Math.max(1,Math.ceil(Math.abs(I)/(Math.PI/2)-1e-9)),H=I/U,q=4/3*Math.tan(H/4),z=e1=>{let u1=Math.cos(e1),d1=Math.sin(e1);return[v+t*u1*l-L*d1*u,F+t*u1*u+L*d1*l,-t*d1*l-L*u1*u,-t*d1*u+L*u1*l]},j=[],[W,X,t1,J]=z(S);for(let e1=1;e1<=U;e1++){let[u1,d1,m1,p1]=z(S+e1*H),l1=e1===U?r:u1,y1=e1===U?o:d1;j.push([W+q*t1,X+q*J,l1-q*m1,y1-q*p1,l1,y1]),W=l1,X=y1,t1=m1,J=p1}return j}
function bC(e,C){let t=C.width/2;if(!(t>0))return[];let L=[];for(let n of kd(e,C))Bd(n,t,C,L);for(let n of L)Fd(n)<0&&vd(n);return L}
function kd(e,C){let t=C.dash;if(!t||t.length===0)return[...e];let L=t.reduce((i,s)=>i+s,0);if(!(L>=.5))return[...e];let n=[];for(let i of e){let s=i.points.slice();i.closed&&s.push(s[0],s[1]);let r=((C.dashOffset??0)%L+L)%L,o=0;for(;r>=t[o];)r-=t[o],o=(o+1)%t.length;let a=t[o]-r,l=o%2===0,u=l?[s[0],s[1]]:[];for(let x=0;x+3<s.length;x+=2){let p=s[x],h=s[x+1],d=s[x+2],m=s[x+3],b=Math.hypot(d-p,m-h),B=0;for(;b-B>a;){B+=a;let A=B/b,k=p+(d-p)*A,D=h+(m-h)*A;if(l){if(u.push(k,D),n.push({points:u,closed:!1}),n.length>2e4)return[...e];u=[]}else u=[k,D];l=!l,o=(o+1)%t.length,a=t[o]}a-=b-B,l&&u.push(d,m)}l&&u.length>=4&&n.push({points:u,closed:!1})}return n}
function Bd(e,C,t,L){let n=[];for(let x=0;x+1<e.points.length;x+=2){let p=e.points[x],h=e.points[x+1],d=n.length;d>=2&&Math.abs(p-n[d-2])<.01&&Math.abs(h-n[d-1])<.01||n.push(p,h)}let i=e.closed;i&&n.length>=4&&Math.abs(n[0]-n[n.length-2])<.01&&Math.abs(n[1]-n[n.length-1])<.01&&(n.length-=2);let s=n.length/2;if(s<2){if(s===1&&t.cap!=="butt"&&e.points.length>=4){let x=n[0],p=n[1];L.push(t.cap==="round"?DC(x,p,C):[x-C,p-C,x+C,p-C,x+C,p+C,x-C,p+C])}return}s===2&&(i=!1);let r=i?s:s-1,o=new Float64Array(r),a=new Float64Array(r);for(let x=0;x<r;x++){let p=(x+1)%s,h=n[2*p]-n[2*x],d=n[2*p+1]-n[2*x+1],m=Math.hypot(h,d);o[x]=h/m,a[x]=d/m}for(let x=0;x<r;x++){let p=(x+1)%s,h=-a[x]*C,d=o[x]*C,m=n[2*x],b=n[2*x+1],B=n[2*p],A=n[2*p+1];L.push([m+h,b+d,B+h,A+d,B-h,A-d,m-h,b-d])}let l=i?0:1,u=i?s-1:s-2;for(let x=l;x<=u;x++){let p=(x-1+r)%r,h=x%r;wd(n[2*x],n[2*x+1],o[p],a[p],o[h],a[h],C,t,L)}i||(Qi(n[0],n[1],-o[0],-a[0],C,t.cap,L),Qi(n[2*s-2],n[2*s-1],o[r-1],a[r-1],C,t.cap,L))}
function wd(e,C,t,L,n,i,s,r,o){let a=t*i-L*n,l=t*n+L*i,u=Math.atan2(Math.abs(a),l);if(s*u<.02)return;let x=a>0?-1:1,p=e+x*-L*s,h=C+x*t*s,d=e+x*-i*s,m=C+x*n*s;if(r.join==="round"&&s*u>.25){o.push(DC(e,C,s));return}if(r.join==="miter"){let b=1/Math.sqrt(Math.max(1e-12,(1+l)/2));if(b<=r.miterLimit){let B=-L-i,A=t+n,k=Math.hypot(B,A);if(k>1e-9){B=B/k*x*s*b,A=A/k*x*s*b,o.push([e,C,p,h,e+B,C+A,d,m]);return}}}o.push([e,C,p,h,d,m])}
function Qi(e,C,t,L,n,i,s){if(i==="round")s.push(DC(e,C,n));else if(i==="square"){let r=-L*n,o=t*n,a=e+t*n,l=C+L*n;s.push([e+r,C+o,a+r,l+o,a-r,l-o,e-r,C-o])}}
function DC(e,C,t){let L=t<=.05?6:Math.min(128,Math.max(6,Math.ceil(Math.PI/Math.acos(1-.05/t)))),n=[];for(let i=0;i<L;i++){let s=2*Math.PI*i/L;n.push(e+t*Math.cos(s),C+t*Math.sin(s))}return n}
function Fd(e){let C=0,t=e.length,L=e[t-2],n=e[t-1];for(let i=0;i<t;i+=2)C+=L*e[i+1]-e[i]*n,L=e[i],n=e[i+1];return C/2}
function vd(e){for(let C=0,t=e.length-2;C<t;C+=2,t-=2){let L=e[C],n=e[C+1];e[C]=e[t],e[C+1]=e[t+1],e[t]=L,e[t+1]=n}}
function Zi(e,C){let t=Math.max(1,Math.round(C)),L=i=>t%2===1?Math.floor(i)+.5:Math.round(i),n=!1;for(let i of e){let s=i.points;i.closed&&s.length>=6&&Math.abs(s[0]-s[s.length-2])<.01&&Math.abs(s[1]-s[s.length-1])<.01&&(s.length-=2);let r=s.length/2,o=i.closed?r:r-1,a=new Uint8Array(r),l=new Uint8Array(r);for(let u=0;u<o;u++){let x=(u+1)%r,p=s[2*x]-s[2*u],h=s[2*x+1]-s[2*u+1],d=Math.hypot(p,h);d>0&&(Math.abs(h)<.001*d?l[u]=l[x]=1:Math.abs(p)<.001*d&&(a[u]=a[x]=1))}for(let u=0;u<r;u++)a[u]&&(s[2*u]=L(s[2*u])),l[u]&&(s[2*u+1]=L(s[2*u+1])),(a[u]||l[u])&&(n=!0)}return n?t:C}
var K5=[[300,12],[400,V7],[500,20],[600,23],[700,26]];
function Sd(e){if(e===void 0||!Number.isFinite(e))return V7;let C=K5[0],t=K5.at(-1);if(e<=C[0])return C[1];if(e>=t[0])return t[1];let L=K5.findIndex(([o])=>o>=e),[n,i]=K5[L-1],[s,r]=K5[L];return Math.round(i+(r-i)*(e-n)/(s-n))}
function kC(e,C){let{emPx:t,cellWidth:L,cellHeight:n}=C;if(!(t>0&&L>0&&n>0))throw new RangeError("raster: emPx and cell sizes must be positive");let i=Math.max(1,Math.min(255,Math.floor(C.maxColumns)||1)),s=Math.max(1,Math.min(255,Math.ceil(C.minRows??1))),r=Math.max(0,C.weight??V7),o=Math.max(0,e.width),a=Math.max(0,e.height+e.depth),l=r/1e3*t,u=Math.ceil(l-1e-9),x=C.align==="left"&&C.centerInk?Td(e,t,l,u):void 0,p=x??o*t,h=i*L-(x===void 0?2*u:0),d=255*n-2*u,m=C.baselinePx!==void 0,b=1,B=0;if(p>h&&(b=Math.max(0,h-(x===void 0?0:Yi))/p),m){let q=Math.max(1,Math.round(s*n)),z=Math.min(q,Math.max(0,Math.round(C.baselinePx))),j=Math.max(0,e.height)*t+l,W=Math.max(0,e.depth)*t+l,X=Math.max(1,Math.round(n*Rd)),t1=C.minScale??0,J=m1=>p1=>Math.min(b,j>0?Math.max(0,p1-m1)/j:1/0,W>0?(q-p1)/W:1/0),e1=m1=>{let p1=z;for(let l1=1;l1<=X;l1++)for(let y1 of[z-l1,z+l1])y1>=0&&y1<=q&&m1(y1)>m1(p1)+1e-9&&(p1=y1);return{at:p1,scale:m1(p1)}},u1=e1(J(yC));u1.scale<t1&&(u1=e1(J(0))),B=u1.at,b=u1.scale;let d1=Math.max(0,C.overflowPx??0);if(b<t1&&d1>0){let m1=l1=>Math.min(j>0?(l1+d1)/j:1/0,W>0?(q-l1+d1)/W:1/0),p1=z;for(let l1=1;l1<=X;l1++)for(let y1 of[z-l1,z+l1])y1>=0&&y1<=q&&m1(y1)>m1(p1)+1e-9&&(p1=y1);m1(p1)>=t1-1e-9&&(p*t1<=h||h<=0)&&(B=p1,b=t1)}}else a*t*b>d&&(b=Math.max(0,d)/(a*t));let A=t*b,k=x===void 0?o*A+2*u:b===1?x:x*b+Yi,D=a*A+2*u,v=Math.max(1,Math.floor(C.minColumns??1)),F=C.align==="center"?i:Math.min(i,Math.max(v,Math.ceil(k/L-1e-9))),y=m?s:Math.min(255,Math.max(s,Math.ceil(D/n-1e-9))),S=Math.max(1,Math.round(F*L)),I=Math.max(1,Math.round(y*n)),U=C.align==="center"?Math.round((S-o*A)/2):u,H=m?B:Math.round((I-D)/2+u+Math.max(0,e.height)*A);return{columns:F,rows:y,scale:b,widthPx:S,heightPx:I,k:A,dilation:l*b,originX:U,baselinePx:H}}
function Y3(e,C){let{columns:t,rows:L,scale:n}=kC(e,C);return{columns:t,rows:L,scale:n}}
function T6(e,C){let t=kC(e,C),{widthPx:L,heightPx:n,k:i,dilation:s,originX:r,baselinePx:o}=t,a=new v6(L,n),l=[i,0,0,i,r,o],u=Math.max(K7,.15*i),x=e.ops.flatMap(h=>Cs(h,l,s,u)??[]),p=C.align==="left"&&C.centerInk?Nd(x,L,C.inkPlace??"center"):0;for(let{contours:h,sign:d}of x)for(let m of h){if(p!==0)for(let b=0;b<m.length;b+=2)m[b]=m[b]+p;a.fill(m,d)}return{columns:t.columns,rows:t.rows,scale:t.scale,alpha:a.toAlpha(),widthPx:L,heightPx:n,baselinePx:o}}
function X7(e,C,t,L){return Hi(e.alpha,e.widthPx,e.heightPx,C,t,L)}
function Td(e,C,t,L){let n=[C,0,0,C,L,0],i=e.ops.flatMap(o=>Cs(o,n,t,Math.max(K7,.15*C))??[]),{x0:s,x1:r}=Ji(i);return r>s?Math.ceil(r-1e-9)-Math.floor(s+1e-9):void 0}
function Ji(e){let C=1/0,t=-1/0;for(let{contours:L}of e)for(let n of L)for(let i=0;i<n.length;i+=2)n[i]<C&&(C=n[i]),n[i]>t&&(t=n[i]);return{x0:C,x1:t}}
function Nd(e,C,t){let{x0:L,x1:n}=Ji(e);if(!(n>L)||n-L>C)return 0;let i=C-(n-L),s=Math.round((t==="start"?0:t==="end"?i:i/2)-L);return Math.min(Math.max(s,Math.ceil(-L-1e-9)),Math.floor(C-n+1e-9))}
function Cs(e,C,t,L){let n;if(e.type==="rect"){let[o,,,,a,l]=C,u=a+o*Math.min(e.x,e.x+e.width),x=a+o*Math.max(e.x,e.x+e.width),p=l+o*Math.min(e.y,e.y+e.height),h=l+o*Math.max(e.y,e.y+e.height);if(!(x>u&&h>p))return;n=[[u,p,x,p,x,h,u,h]]}else n=H7(e.d,q7(C,e.transform));let i=0;for(let o of n)i+=U7(o);if(!(Math.abs(i)>1e-9))return;let s=i>0?1:-1,r=[];for(let o of n)t>0&&(o=ts(o,t,s)),es(o,L),r.push(o);return{contours:r,sign:s}}
function q7(e,C){return[e[0]*C[0]+e[2]*C[1],e[1]*C[0]+e[3]*C[1],e[0]*C[2]+e[2]*C[3],e[1]*C[2]+e[3]*C[3],e[0]*C[4]+e[2]*C[5]+e[4],e[1]*C[4]+e[3]*C[5]+e[5]]}
function U7(e){let C=0,t=e.length,L=e[t-2],n=e[t-1];for(let i=0;i<t;i+=2){let s=e[i],r=e[i+1];C+=L*r-s*n,L=s,n=r}return C/2}
function ts(e,C,t){let L=[];for(let o=0;o<e.length;o+=2){let a=e[o],l=e[o+1],u=L.length;u>=2&&Math.abs(a-L[u-2])<1e-6&&Math.abs(l-L[u-1])<1e-6||L.push(a,l)}for(;L.length>=4&&Math.abs(L[0]-L[L.length-2])<1e-6&&Math.abs(L[1]-L[L.length-1])<1e-6;)L.length-=2;let n=L.length/2;if(n<3)return e;let i=new Float64Array(n),s=new Float64Array(n);for(let o=0;o<n;o++){let a=(o+1)%n,l=L[2*a]-L[2*o],u=L[2*a+1]-L[2*o+1],x=Math.hypot(l,u);i[o]=t*u/x,s[o]=-t*l/x}let r=new Array(2*n);for(let o=0;o<n;o++){let a=(o+n-1)%n,l=i[a]+i[o],u=s[a]+s[o],x=1+i[a]*i[o]+s[a]*s[o],p=0,h=0;if(x>=.5)p=l/x,h=u/x;else{let d=Math.hypot(l,u);d>1e-9&&(p=2*l/d,h=2*u/d)}r[2*o]=L[2*o]+C*p,r[2*o+1]=L[2*o+1]+C*h}return r}
function es(e,C=K7){let t=1/0,L=1/0,n=-1/0,i=-1/0;for(let h=0;h<e.length;h+=2){let d=e[h],m=e[h+1];d<t&&(t=d),d>n&&(n=d),m<L&&(L=m),m>i&&(i=m)}let s=n-t,r=i-L;if(!(s>0&&r>0)||Math.abs(U7(e))<Od*s*r)return;let o=r<=C&&s>=2*r?1:s<=C&&r>=2*s?0:-1;if(o<0)return;let a=o===1?L:t,l=o===1?r:s,u=Math.max(1,Math.round(l)),x=Math.round(a+l/2-u/2),p=u/l;for(let h=o;h<e.length;h+=2)e[h]=x+(e[h]-a)*p}
export{kC,G7,H7,q7,U7,ts,es,EC,Zi,bC,ji,Y3,T6,X7,$7,R6,Sd};
